// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifact_retention.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CountActiveArtifactRetentionHolds = `-- name: CountActiveArtifactRetentionHolds :one
SELECT COUNT(*)::integer AS active_hold_count
FROM artifact_retention_holds
WHERE tenant_id = $1::uuid
  AND artifact_id = $2::uuid
  AND status = 'active'
  AND released_at IS NULL
`

type CountActiveArtifactRetentionHoldsParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	ArtifactID uuid.UUID `json:"artifact_id"`
}

func (q *Queries) CountActiveArtifactRetentionHolds(ctx context.Context, arg CountActiveArtifactRetentionHoldsParams) (int32, error) {
	row := q.db.QueryRow(ctx, CountActiveArtifactRetentionHolds, arg.TenantID, arg.ArtifactID)
	var active_hold_count int32
	err := row.Scan(&active_hold_count)
	return active_hold_count, err
}

const CreateArtifactRetentionHold = `-- name: CreateArtifactRetentionHold :one
INSERT INTO artifact_retention_holds (
    tenant_id,
    artifact_id,
    hold_type,
    resource_type,
    resource_id,
    reason,
    status,
    created_event_id
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::varchar,
    $4::varchar,
    $5::uuid,
    $6::text,
    $7::varchar,
    $8::uuid
) RETURNING id, tenant_id, artifact_id, hold_type, resource_type, resource_id, reason, status, created_event_id, created_at, released_at
`

type CreateArtifactRetentionHoldParams struct {
	TenantID       uuid.UUID     `json:"tenant_id"`
	ArtifactID     uuid.UUID     `json:"artifact_id"`
	HoldType       string        `json:"hold_type"`
	ResourceType   string        `json:"resource_type"`
	ResourceID     uuid.UUID     `json:"resource_id"`
	Reason         pgtype.Text   `json:"reason"`
	Status         string        `json:"status"`
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
}

func (q *Queries) CreateArtifactRetentionHold(ctx context.Context, arg CreateArtifactRetentionHoldParams) (ArtifactRetentionHold, error) {
	row := q.db.QueryRow(ctx, CreateArtifactRetentionHold,
		arg.TenantID,
		arg.ArtifactID,
		arg.HoldType,
		arg.ResourceType,
		arg.ResourceID,
		arg.Reason,
		arg.Status,
		arg.CreatedEventID,
	)
	var i ArtifactRetentionHold
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ArtifactID,
		&i.HoldType,
		&i.ResourceType,
		&i.ResourceID,
		&i.Reason,
		&i.Status,
		&i.CreatedEventID,
		&i.CreatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const ListArtifactRetentionHolds = `-- name: ListArtifactRetentionHolds :many
SELECT id, tenant_id, artifact_id, hold_type, resource_type, resource_id, reason, status, created_event_id, created_at, released_at FROM artifact_retention_holds
WHERE tenant_id = $1::uuid
  AND artifact_id = $2::uuid
  AND status = 'active'
  AND released_at IS NULL
ORDER BY created_at DESC
`

type ListArtifactRetentionHoldsParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	ArtifactID uuid.UUID `json:"artifact_id"`
}

func (q *Queries) ListArtifactRetentionHolds(ctx context.Context, arg ListArtifactRetentionHoldsParams) ([]ArtifactRetentionHold, error) {
	rows, err := q.db.Query(ctx, ListArtifactRetentionHolds, arg.TenantID, arg.ArtifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtifactRetentionHold{}
	for rows.Next() {
		var i ArtifactRetentionHold
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ArtifactID,
			&i.HoldType,
			&i.ResourceType,
			&i.ResourceID,
			&i.Reason,
			&i.Status,
			&i.CreatedEventID,
			&i.CreatedAt,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
