// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit.sql

package queries

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountAuditEvents = `-- name: CountAuditEvents :one
SELECT COUNT(*) FROM audit_events
WHERE ($1::varchar IS NULL OR event_type = $1)
  AND ($2::varchar IS NULL OR actor_type = $2)
  AND ($3::varchar IS NULL OR actor_id = $3)
  AND ($4::varchar IS NULL OR resource_type = $4)
  AND ($5::varchar IS NULL OR resource_id = $5)
  AND ($6::timestamptz IS NULL OR created_at >= $6)
  AND ($7::timestamptz IS NULL OR created_at <= $7)
`

type CountAuditEventsParams struct {
	EventType    pgtype.Text        `json:"event_type"`
	ActorType    pgtype.Text        `json:"actor_type"`
	ActorID      pgtype.Text        `json:"actor_id"`
	ResourceType pgtype.Text        `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	EndTime      pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) CountAuditEvents(ctx context.Context, arg CountAuditEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountAuditEvents,
		arg.EventType,
		arg.ActorType,
		arg.ActorID,
		arg.ResourceType,
		arg.ResourceID,
		arg.StartTime,
		arg.EndTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (
    event_type,
    actor_type,
    actor_id,
    resource_type,
    resource_id,
    action,
    details,
    ip_address
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, event_type, actor_type, actor_id, resource_type, resource_id, action, details, ip_address, created_at
`

type CreateAuditEventParams struct {
	EventType    string      `json:"event_type"`
	ActorType    string      `json:"actor_type"`
	ActorID      string      `json:"actor_id"`
	ResourceType pgtype.Text `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
	Action       string      `json:"action"`
	Details      []byte      `json:"details"`
	IpAddress    *netip.Addr `json:"ip_address"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, CreateAuditEvent,
		arg.EventType,
		arg.ActorType,
		arg.ActorID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Action,
		arg.Details,
		arg.IpAddress,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.ActorType,
		&i.ActorID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Action,
		&i.Details,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const GetAuditEvent = `-- name: GetAuditEvent :one
SELECT id, event_type, actor_type, actor_id, resource_type, resource_id, action, details, ip_address, created_at FROM audit_events
WHERE id = $1
`

func (q *Queries) GetAuditEvent(ctx context.Context, id int64) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, GetAuditEvent, id)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.ActorType,
		&i.ActorID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Action,
		&i.Details,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const ListAuditEvents = `-- name: ListAuditEvents :many
SELECT id, event_type, actor_type, actor_id, resource_type, resource_id, action, details, ip_address, created_at FROM audit_events
WHERE ($1::varchar IS NULL OR event_type = $1)
  AND ($2::varchar IS NULL OR actor_type = $2)
  AND ($3::varchar IS NULL OR actor_id = $3)
  AND ($4::varchar IS NULL OR resource_type = $4)
  AND ($5::varchar IS NULL OR resource_id = $5)
  AND ($6::timestamptz IS NULL OR created_at >= $6)
  AND ($7::timestamptz IS NULL OR created_at <= $7)
ORDER BY created_at DESC
LIMIT $9 OFFSET $8
`

type ListAuditEventsParams struct {
	EventType    pgtype.Text        `json:"event_type"`
	ActorType    pgtype.Text        `json:"actor_type"`
	ActorID      pgtype.Text        `json:"actor_id"`
	ResourceType pgtype.Text        `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	EndTime      pgtype.Timestamptz `json:"end_time"`
	Offset       int32              `json:"offset"`
	Limit        int32              `json:"limit"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, ListAuditEvents,
		arg.EventType,
		arg.ActorType,
		arg.ActorID,
		arg.ResourceType,
		arg.ResourceID,
		arg.StartTime,
		arg.EndTime,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ActorType,
			&i.ActorID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
