// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authz_center.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CountAuthzDecisionsSince = `-- name: CountAuthzDecisionsSince :one
SELECT
  COUNT(*)::bigint AS total,
  COUNT(*) FILTER (WHERE result = 'succeeded')::bigint AS allowed,
  COUNT(*) FILTER (WHERE result = 'failed')::bigint AS denied
FROM web_operation_logs
WHERE module = 'authz'
  AND tenant_id = $1::uuid
  AND created_at >= $2::timestamptz
`

type CountAuthzDecisionsSinceParams struct {
	TenantID uuid.UUID          `json:"tenant_id"`
	Since    pgtype.Timestamptz `json:"since"`
}

type CountAuthzDecisionsSinceRow struct {
	Total   int64 `json:"total"`
	Allowed int64 `json:"allowed"`
	Denied  int64 `json:"denied"`
}

func (q *Queries) CountAuthzDecisionsSince(ctx context.Context, arg CountAuthzDecisionsSinceParams) (CountAuthzDecisionsSinceRow, error) {
	row := q.db.QueryRow(ctx, CountAuthzDecisionsSince, arg.TenantID, arg.Since)
	var i CountAuthzDecisionsSinceRow
	err := row.Scan(&i.Total, &i.Allowed, &i.Denied)
	return i, err
}

const CreateRuntimeNodeScope = `-- name: CreateRuntimeNodeScope :one
INSERT INTO runtime_node_scopes (
  tenant_id,
  runtime_node_id,
  team_id,
  scope_type,
  scope_value,
  status
) SELECT
  rn.tenant_id,
  rn.id,
  input.team_id,
  input.scope_type,
  input.scope_value,
  'active'
FROM runtime_nodes rn
CROSS JOIN (
  SELECT
    $1::uuid AS tenant_id,
    $2::uuid AS runtime_node_id,
    $3::uuid AS team_id,
    $4::varchar AS scope_type,
    $5::varchar AS scope_value
) input
LEFT JOIN tenant_teams tt
  ON tt.id = input.team_id
 AND tt.tenant_id = input.tenant_id
WHERE rn.id = input.runtime_node_id
  AND rn.tenant_id = input.tenant_id
  AND rn.archived_at IS NULL
  AND (
    (
      input.scope_type = 'tenant'
      AND input.team_id IS NULL
      AND input.scope_value = input.tenant_id::text
    )
    OR (
      input.scope_type = 'team'
      AND input.team_id IS NOT NULL
      AND input.scope_value = input.team_id::text
      AND tt.id IS NOT NULL
    )
  )
ON CONFLICT (runtime_node_id, scope_type, scope_value) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  team_id = EXCLUDED.team_id,
  status = 'active',
  disabled_at = NULL,
  updated_at = NOW()
RETURNING id, tenant_id, runtime_node_id, team_id, scope_type, scope_value, status, disabled_at, created_at, updated_at
`

type CreateRuntimeNodeScopeParams struct {
	TenantID      uuid.UUID     `json:"tenant_id"`
	RuntimeNodeID uuid.UUID     `json:"runtime_node_id"`
	TeamID        uuid.NullUUID `json:"team_id"`
	ScopeType     string        `json:"scope_type"`
	ScopeValue    string        `json:"scope_value"`
}

func (q *Queries) CreateRuntimeNodeScope(ctx context.Context, arg CreateRuntimeNodeScopeParams) (RuntimeNodeScope, error) {
	row := q.db.QueryRow(ctx, CreateRuntimeNodeScope,
		arg.TenantID,
		arg.RuntimeNodeID,
		arg.TeamID,
		arg.ScopeType,
		arg.ScopeValue,
	)
	var i RuntimeNodeScope
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeNodeID,
		&i.TeamID,
		&i.ScopeType,
		&i.ScopeValue,
		&i.Status,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAuthzDecisions = `-- name: ListAuthzDecisions :many
SELECT id, tenant_id, user_id, username, module, resource_type, resource_id, action, result, request_id, client_ip, user_agent, details, created_at
FROM web_operation_logs
WHERE module = 'authz'
  AND tenant_id = $1::uuid
  AND ($2::varchar IS NULL OR result = $2::varchar)
  AND ($3::varchar IS NULL OR action = $3::varchar)
  AND ($4::varchar IS NULL OR details->>'actor_type' = $4::varchar OR details->'actor'->>'type' = $4::varchar)
  AND ($5::varchar IS NULL OR details->>'actor_id' = $5::varchar OR details->'actor'->>'id' = $5::varchar)
  AND ($6::varchar IS NULL OR resource_type = $6::varchar)
  AND ($7::varchar IS NULL OR resource_id = $7::varchar)
  AND ($8::varchar IS NULL OR request_id = $8::varchar)
ORDER BY created_at DESC, id DESC
LIMIT $10 OFFSET $9
`

type ListAuthzDecisionsParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	Result       pgtype.Text `json:"result"`
	Action       pgtype.Text `json:"action"`
	ActorType    pgtype.Text `json:"actor_type"`
	ActorID      pgtype.Text `json:"actor_id"`
	ResourceType pgtype.Text `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
	RequestID    pgtype.Text `json:"request_id"`
	Offset       int32       `json:"offset"`
	Limit        int32       `json:"limit"`
}

func (q *Queries) ListAuthzDecisions(ctx context.Context, arg ListAuthzDecisionsParams) ([]WebOperationLog, error) {
	rows, err := q.db.Query(ctx, ListAuthzDecisions,
		arg.TenantID,
		arg.Result,
		arg.Action,
		arg.ActorType,
		arg.ActorID,
		arg.ResourceType,
		arg.ResourceID,
		arg.RequestID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebOperationLog{}
	for rows.Next() {
		var i WebOperationLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Username,
			&i.Module,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.Result,
			&i.RequestID,
			&i.ClientIp,
			&i.UserAgent,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAuthzMembers = `-- name: ListAuthzMembers :many
WITH paged_users AS (
  SELECT
    au.id,
    au.username AS user_username,
    au.display_name AS user_display_name,
    au.email AS user_email,
    au.status AS account_status,
    au.created_at
  FROM auth_users au
  JOIN tenant_members tm
    ON tm.principal_type = 'user'
   AND tm.principal_id = au.id
   AND tm.tenant_id = $1::uuid
   AND tm.disabled_at IS NULL
  WHERE au.deleted_at IS NULL
  GROUP BY au.id, au.username, au.display_name, au.email, au.status, au.created_at
  ORDER BY au.created_at DESC, au.id DESC
  LIMIT $3 OFFSET $2
)
SELECT
  pu.id AS user_id,
  pu.user_username,
  pu.user_display_name,
  pu.user_email,
  pu.account_status,
  tm.tenant_id,
  tm.team_id,
  tm.principal_type,
  tm.principal_id,
  tm.role,
  tm.status AS membership_status
FROM paged_users pu
JOIN tenant_members tm
  ON tm.principal_type = 'user'
 AND tm.principal_id = pu.id
 AND tm.tenant_id = $1::uuid
 AND tm.disabled_at IS NULL
ORDER BY pu.created_at DESC, pu.id DESC, tm.created_at DESC, tm.id DESC
`

type ListAuthzMembersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Offset   int32     `json:"offset"`
	Limit    int32     `json:"limit"`
}

type ListAuthzMembersRow struct {
	UserID           uuid.UUID     `json:"user_id"`
	UserUsername     string        `json:"user_username"`
	UserDisplayName  pgtype.Text   `json:"user_display_name"`
	UserEmail        pgtype.Text   `json:"user_email"`
	AccountStatus    string        `json:"account_status"`
	TenantID         uuid.UUID     `json:"tenant_id"`
	TeamID           uuid.NullUUID `json:"team_id"`
	PrincipalType    string        `json:"principal_type"`
	PrincipalID      uuid.UUID     `json:"principal_id"`
	Role             string        `json:"role"`
	MembershipStatus string        `json:"membership_status"`
}

func (q *Queries) ListAuthzMembers(ctx context.Context, arg ListAuthzMembersParams) ([]ListAuthzMembersRow, error) {
	rows, err := q.db.Query(ctx, ListAuthzMembers, arg.TenantID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthzMembersRow{}
	for rows.Next() {
		var i ListAuthzMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserUsername,
			&i.UserDisplayName,
			&i.UserEmail,
			&i.AccountStatus,
			&i.TenantID,
			&i.TeamID,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.Role,
			&i.MembershipStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRuntimeNodesWithScopes = `-- name: ListRuntimeNodesWithScopes :many
SELECT
  rn.id AS runtime_node_id,
  rn.tenant_id AS runtime_tenant_id,
  rn.node_id,
  rn.name,
  rn.supported_providers,
  rn.max_slots,
  rn.current_load,
  rn.status AS runtime_status,
  rn.last_heartbeat_at,
  rns.id AS scope_id,
  rns.tenant_id AS scope_tenant_id,
  rns.runtime_node_id AS scope_runtime_node_id,
  rns.team_id AS scope_team_id,
  rns.scope_type,
  rns.scope_value,
  rns.status AS scope_status,
  rns.disabled_at AS scope_disabled_at,
  rns.created_at AS scope_created_at,
  rns.updated_at AS scope_updated_at
FROM runtime_nodes rn
LEFT JOIN runtime_node_scopes rns
  ON rns.runtime_node_id = rn.id
 AND rns.tenant_id = $1::uuid
WHERE rn.archived_at IS NULL
  AND rn.tenant_id = $1::uuid
ORDER BY rn.created_at DESC, rns.created_at DESC
`

type ListRuntimeNodesWithScopesRow struct {
	RuntimeNodeID      uuid.UUID          `json:"runtime_node_id"`
	RuntimeTenantID    uuid.UUID          `json:"runtime_tenant_id"`
	NodeID             string             `json:"node_id"`
	Name               string             `json:"name"`
	SupportedProviders []byte             `json:"supported_providers"`
	MaxSlots           int32              `json:"max_slots"`
	CurrentLoad        int32              `json:"current_load"`
	RuntimeStatus      string             `json:"runtime_status"`
	LastHeartbeatAt    pgtype.Timestamptz `json:"last_heartbeat_at"`
	ScopeID            uuid.NullUUID      `json:"scope_id"`
	ScopeTenantID      uuid.NullUUID      `json:"scope_tenant_id"`
	ScopeRuntimeNodeID uuid.NullUUID      `json:"scope_runtime_node_id"`
	ScopeTeamID        uuid.NullUUID      `json:"scope_team_id"`
	ScopeType          pgtype.Text        `json:"scope_type"`
	ScopeValue         pgtype.Text        `json:"scope_value"`
	ScopeStatus        pgtype.Text        `json:"scope_status"`
	ScopeDisabledAt    pgtype.Timestamptz `json:"scope_disabled_at"`
	ScopeCreatedAt     pgtype.Timestamptz `json:"scope_created_at"`
	ScopeUpdatedAt     pgtype.Timestamptz `json:"scope_updated_at"`
}

func (q *Queries) ListRuntimeNodesWithScopes(ctx context.Context, tenantID uuid.UUID) ([]ListRuntimeNodesWithScopesRow, error) {
	rows, err := q.db.Query(ctx, ListRuntimeNodesWithScopes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimeNodesWithScopesRow{}
	for rows.Next() {
		var i ListRuntimeNodesWithScopesRow
		if err := rows.Scan(
			&i.RuntimeNodeID,
			&i.RuntimeTenantID,
			&i.NodeID,
			&i.Name,
			&i.SupportedProviders,
			&i.MaxSlots,
			&i.CurrentLoad,
			&i.RuntimeStatus,
			&i.LastHeartbeatAt,
			&i.ScopeID,
			&i.ScopeTenantID,
			&i.ScopeRuntimeNodeID,
			&i.ScopeTeamID,
			&i.ScopeType,
			&i.ScopeValue,
			&i.ScopeStatus,
			&i.ScopeDisabledAt,
			&i.ScopeCreatedAt,
			&i.ScopeUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTopDeniedAuthzActionsSince = `-- name: ListTopDeniedAuthzActionsSince :many
SELECT action, COUNT(*)::bigint AS count
FROM web_operation_logs
WHERE module = 'authz'
  AND tenant_id = $1::uuid
  AND result = 'failed'
  AND created_at >= $2::timestamptz
GROUP BY action
ORDER BY count DESC, action ASC
LIMIT $3
`

type ListTopDeniedAuthzActionsSinceParams struct {
	TenantID uuid.UUID          `json:"tenant_id"`
	Since    pgtype.Timestamptz `json:"since"`
	Limit    int32              `json:"limit"`
}

type ListTopDeniedAuthzActionsSinceRow struct {
	Action string `json:"action"`
	Count  int64  `json:"count"`
}

func (q *Queries) ListTopDeniedAuthzActionsSince(ctx context.Context, arg ListTopDeniedAuthzActionsSinceParams) ([]ListTopDeniedAuthzActionsSinceRow, error) {
	rows, err := q.db.Query(ctx, ListTopDeniedAuthzActionsSince, arg.TenantID, arg.Since, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopDeniedAuthzActionsSinceRow{}
	for rows.Next() {
		var i ListTopDeniedAuthzActionsSinceRow
		if err := rows.Scan(&i.Action, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateRuntimeNodeScopeStatus = `-- name: UpdateRuntimeNodeScopeStatus :one
UPDATE runtime_node_scopes
SET status = $1::varchar,
    disabled_at = CASE
      WHEN $1::varchar = 'disabled' THEN COALESCE(disabled_at, NOW())
      WHEN $1::varchar = 'active' THEN NULL
      ELSE disabled_at
    END,
    updated_at = NOW()
WHERE id = $2::uuid
  AND tenant_id = $3::uuid
RETURNING id, tenant_id, runtime_node_id, team_id, scope_type, scope_value, status, disabled_at, created_at, updated_at
`

type UpdateRuntimeNodeScopeStatusParams struct {
	Status   string    `json:"status"`
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateRuntimeNodeScopeStatus(ctx context.Context, arg UpdateRuntimeNodeScopeStatusParams) (RuntimeNodeScope, error) {
	row := q.db.QueryRow(ctx, UpdateRuntimeNodeScopeStatus, arg.Status, arg.ID, arg.TenantID)
	var i RuntimeNodeScope
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeNodeID,
		&i.TeamID,
		&i.ScopeType,
		&i.ScopeValue,
		&i.Status,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
