// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: demand_adversarial_judgements.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const CreateAdversarialJudgement = `-- name: CreateAdversarialJudgement :exec
INSERT INTO demand_adversarial_judgements (
    tenant_id,
    project_id,
    demand_id,
    plan_revision_id,
    criterion_id,
    reviewed_task_id,
    lens,
    verdict,
    reason,
    evidence_refs
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::uuid,
    $5::text,
    $6::uuid,
    $7::varchar,
    $8::varchar,
    $9::text,
    COALESCE($10::jsonb, '[]'::jsonb)
)
ON CONFLICT (tenant_id, demand_id, plan_revision_id, criterion_id, lens)
    DO UPDATE SET
        reviewed_task_id = EXCLUDED.reviewed_task_id,
        verdict = EXCLUDED.verdict,
        reason = EXCLUDED.reason,
        evidence_refs = EXCLUDED.evidence_refs,
        created_at = NOW()
`

type CreateAdversarialJudgementParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	DemandID       uuid.UUID `json:"demand_id"`
	PlanRevisionID uuid.UUID `json:"plan_revision_id"`
	CriterionID    string    `json:"criterion_id"`
	ReviewedTaskID uuid.UUID `json:"reviewed_task_id"`
	Lens           string    `json:"lens"`
	Verdict        string    `json:"verdict"`
	Reason         string    `json:"reason"`
	EvidenceRefs   []byte    `json:"evidence_refs"`
}

// 单个判官明细行：一 lens 一行，ON CONFLICT 命中 uq_adversarial_judgement
// (tenant_id, demand_id, plan_revision_id, criterion_id, lens)，重跑覆盖同 lens 判定。
func (q *Queries) CreateAdversarialJudgement(ctx context.Context, arg CreateAdversarialJudgementParams) error {
	_, err := q.db.Exec(ctx, CreateAdversarialJudgement,
		arg.TenantID,
		arg.ProjectID,
		arg.DemandID,
		arg.PlanRevisionID,
		arg.CriterionID,
		arg.ReviewedTaskID,
		arg.Lens,
		arg.Verdict,
		arg.Reason,
		arg.EvidenceRefs,
	)
	return err
}

const CreateAdversarialVerdict = `-- name: CreateAdversarialVerdict :exec

INSERT INTO demand_criterion_verdicts (
    tenant_id,
    project_id,
    demand_id,
    plan_revision_id,
    criterion_id,
    verdict,
    judge_type,
    judge_id,
    reason,
    evidence_refs,
    project_task_id
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::uuid,
    $5::text,
    $6::varchar,
    'adversarial'::varchar,
    $7::uuid,
    $8::text,
    COALESCE($9::jsonb, '[]'::jsonb),
    NULL
)
ON CONFLICT (tenant_id, demand_id, plan_revision_id, criterion_id)
    WHERE project_task_id IS NULL AND judge_type = 'adversarial'
    DO UPDATE SET
        verdict = EXCLUDED.verdict,
        reason = EXCLUDED.reason,
        evidence_refs = EXCLUDED.evidence_refs,
        created_at = NOW()
`

type CreateAdversarialVerdictParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	DemandID       uuid.UUID `json:"demand_id"`
	PlanRevisionID uuid.UUID `json:"plan_revision_id"`
	CriterionID    string    `json:"criterion_id"`
	Verdict        string    `json:"verdict"`
	JudgeID        uuid.UUID `json:"judge_id"`
	Reason         string    `json:"reason"`
	EvidenceRefs   []byte    `json:"evidence_refs"`
}

// 对抗判官投影写入：聚合行（demand_criterion_verdicts, judge_type=adversarial, project_task_id 为空，
// 一 criterion 一行）+ 逐判官明细行（demand_adversarial_judgements, 一 lens 一行）。
// 二者均 upsert，供任务重试幂等重跑。
// 对抗评审聚合行：judge_type 固定 adversarial、project_task_id 恒为 NULL，命中 uq_demand_verdicts_adversarial
// 唯一索引（谓词 project_task_id IS NULL AND judge_type='adversarial'）。不能复用 CreateDemandCriterionVerdict，
// 后者 ON CONFLICT 只对 project_task_id IS NOT NULL 的 executor 行去重，对本聚合行不命中。
func (q *Queries) CreateAdversarialVerdict(ctx context.Context, arg CreateAdversarialVerdictParams) error {
	_, err := q.db.Exec(ctx, CreateAdversarialVerdict,
		arg.TenantID,
		arg.ProjectID,
		arg.DemandID,
		arg.PlanRevisionID,
		arg.CriterionID,
		arg.Verdict,
		arg.JudgeID,
		arg.Reason,
		arg.EvidenceRefs,
	)
	return err
}

const ListAdversarialJudgements = `-- name: ListAdversarialJudgements :many
SELECT id, tenant_id, project_id, demand_id, plan_revision_id, criterion_id, reviewed_task_id, lens, verdict, reason, evidence_refs, created_at FROM demand_adversarial_judgements
WHERE tenant_id = $1::uuid
  AND demand_id = $2::uuid
  AND plan_revision_id = $3::uuid
ORDER BY created_at ASC, id ASC
`

type ListAdversarialJudgementsParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	DemandID       uuid.UUID `json:"demand_id"`
	PlanRevisionID uuid.UUID `json:"plan_revision_id"`
}

// 逐判官明细回读：血缘/审计面板按租户+需求+计划修订版本列出全部 lens 判定。
func (q *Queries) ListAdversarialJudgements(ctx context.Context, arg ListAdversarialJudgementsParams) ([]DemandAdversarialJudgement, error) {
	rows, err := q.db.Query(ctx, ListAdversarialJudgements, arg.TenantID, arg.DemandID, arg.PlanRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DemandAdversarialJudgement{}
	for rows.Next() {
		var i DemandAdversarialJudgement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.DemandID,
			&i.PlanRevisionID,
			&i.CriterionID,
			&i.ReviewedTaskID,
			&i.Lens,
			&i.Verdict,
			&i.Reason,
			&i.EvidenceRefs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
