// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: employee_execution.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateDigitalEmployee = `-- name: CreateDigitalEmployee :one
INSERT INTO digital_employees (
    tenant_id,
    team_id,
    name,
    role,
    description,
    status,
    permission_policy,
    context_policy,
    approval_policy,
    risk_level,
    metadata
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::varchar,
    $4::varchar,
    $5::text,
    $6::varchar,
    COALESCE($7::jsonb, '{}'::jsonb),
    COALESCE($8::jsonb, '{}'::jsonb),
    COALESCE($9::jsonb, '{}'::jsonb),
    $10::varchar,
    COALESCE($11::jsonb, '{}'::jsonb)
) RETURNING id, tenant_id, team_id, name, role, description, status, permission_policy, context_policy, approval_policy, risk_level, metadata, disabled_at, archived_at, deleted_at, created_at, updated_at
`

type CreateDigitalEmployeeParams struct {
	TenantID         uuid.UUID     `json:"tenant_id"`
	TeamID           uuid.NullUUID `json:"team_id"`
	Name             string        `json:"name"`
	Role             string        `json:"role"`
	Description      pgtype.Text   `json:"description"`
	Status           string        `json:"status"`
	PermissionPolicy []byte        `json:"permission_policy"`
	ContextPolicy    []byte        `json:"context_policy"`
	ApprovalPolicy   []byte        `json:"approval_policy"`
	RiskLevel        string        `json:"risk_level"`
	Metadata         []byte        `json:"metadata"`
}

func (q *Queries) CreateDigitalEmployee(ctx context.Context, arg CreateDigitalEmployeeParams) (DigitalEmployee, error) {
	row := q.db.QueryRow(ctx, CreateDigitalEmployee,
		arg.TenantID,
		arg.TeamID,
		arg.Name,
		arg.Role,
		arg.Description,
		arg.Status,
		arg.PermissionPolicy,
		arg.ContextPolicy,
		arg.ApprovalPolicy,
		arg.RiskLevel,
		arg.Metadata,
	)
	var i DigitalEmployee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.Name,
		&i.Role,
		&i.Description,
		&i.Status,
		&i.PermissionPolicy,
		&i.ContextPolicy,
		&i.ApprovalPolicy,
		&i.RiskLevel,
		&i.Metadata,
		&i.DisabledAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteDigitalEmployee = `-- name: DeleteDigitalEmployee :exec
UPDATE digital_employees
SET deleted_at = COALESCE(deleted_at, NOW()),
    updated_at = NOW()
WHERE id = $1::uuid
  AND tenant_id = $2::uuid
`

type DeleteDigitalEmployeeParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteDigitalEmployee(ctx context.Context, arg DeleteDigitalEmployeeParams) error {
	_, err := q.db.Exec(ctx, DeleteDigitalEmployee, arg.ID, arg.TenantID)
	return err
}

const DeleteDigitalEmployeeExecutionInstance = `-- name: DeleteDigitalEmployeeExecutionInstance :exec
UPDATE digital_employee_execution_instances
SET deleted_at = COALESCE(deleted_at, NOW()),
    updated_at = NOW()
WHERE id = $1::uuid
  AND tenant_id = $2::uuid
`

type DeleteDigitalEmployeeExecutionInstanceParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteDigitalEmployeeExecutionInstance(ctx context.Context, arg DeleteDigitalEmployeeExecutionInstanceParams) error {
	_, err := q.db.Exec(ctx, DeleteDigitalEmployeeExecutionInstance, arg.ID, arg.TenantID)
	return err
}

const GetDigitalEmployee = `-- name: GetDigitalEmployee :one
SELECT id, tenant_id, team_id, name, role, description, status, permission_policy, context_policy, approval_policy, risk_level, metadata, disabled_at, archived_at, deleted_at, created_at, updated_at
FROM digital_employees
WHERE id = $1::uuid
  AND tenant_id = $2::uuid
  AND deleted_at IS NULL
`

type GetDigitalEmployeeParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetDigitalEmployee(ctx context.Context, arg GetDigitalEmployeeParams) (DigitalEmployee, error) {
	row := q.db.QueryRow(ctx, GetDigitalEmployee, arg.ID, arg.TenantID)
	var i DigitalEmployee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.Name,
		&i.Role,
		&i.Description,
		&i.Status,
		&i.PermissionPolicy,
		&i.ContextPolicy,
		&i.ApprovalPolicy,
		&i.RiskLevel,
		&i.Metadata,
		&i.DisabledAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetDigitalEmployeeExecutionInstance = `-- name: GetDigitalEmployeeExecutionInstance :one
SELECT id, tenant_id, digital_employee_id, runtime_node_id, provider_type, agent_home_dir, workspace_policy, session_policy, runtime_selector, capacity_requirements, fallback_policy, status, ready_at, disabled_at, error_at, error_message, deleted_at, metadata, created_at, updated_at
FROM digital_employee_execution_instances
WHERE id = $1::uuid
  AND tenant_id = $2::uuid
  AND deleted_at IS NULL
`

type GetDigitalEmployeeExecutionInstanceParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetDigitalEmployeeExecutionInstance(ctx context.Context, arg GetDigitalEmployeeExecutionInstanceParams) (DigitalEmployeeExecutionInstance, error) {
	row := q.db.QueryRow(ctx, GetDigitalEmployeeExecutionInstance, arg.ID, arg.TenantID)
	var i DigitalEmployeeExecutionInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DigitalEmployeeID,
		&i.RuntimeNodeID,
		&i.ProviderType,
		&i.AgentHomeDir,
		&i.WorkspacePolicy,
		&i.SessionPolicy,
		&i.RuntimeSelector,
		&i.CapacityRequirements,
		&i.FallbackPolicy,
		&i.Status,
		&i.ReadyAt,
		&i.DisabledAt,
		&i.ErrorAt,
		&i.ErrorMessage,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetDigitalEmployeeExecutionInstanceByEmployeeID = `-- name: GetDigitalEmployeeExecutionInstanceByEmployeeID :one
SELECT id, tenant_id, digital_employee_id, runtime_node_id, provider_type, agent_home_dir, workspace_policy, session_policy, runtime_selector, capacity_requirements, fallback_policy, status, ready_at, disabled_at, error_at, error_message, deleted_at, metadata, created_at, updated_at
FROM digital_employee_execution_instances
WHERE digital_employee_id = $1::uuid
  AND tenant_id = $2::uuid
  AND deleted_at IS NULL
`

type GetDigitalEmployeeExecutionInstanceByEmployeeIDParams struct {
	DigitalEmployeeID uuid.UUID `json:"digital_employee_id"`
	TenantID          uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetDigitalEmployeeExecutionInstanceByEmployeeID(ctx context.Context, arg GetDigitalEmployeeExecutionInstanceByEmployeeIDParams) (DigitalEmployeeExecutionInstance, error) {
	row := q.db.QueryRow(ctx, GetDigitalEmployeeExecutionInstanceByEmployeeID, arg.DigitalEmployeeID, arg.TenantID)
	var i DigitalEmployeeExecutionInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DigitalEmployeeID,
		&i.RuntimeNodeID,
		&i.ProviderType,
		&i.AgentHomeDir,
		&i.WorkspacePolicy,
		&i.SessionPolicy,
		&i.RuntimeSelector,
		&i.CapacityRequirements,
		&i.FallbackPolicy,
		&i.Status,
		&i.ReadyAt,
		&i.DisabledAt,
		&i.ErrorAt,
		&i.ErrorMessage,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListDigitalEmployeeExecutionInstances = `-- name: ListDigitalEmployeeExecutionInstances :many
SELECT id, tenant_id, digital_employee_id, runtime_node_id, provider_type, agent_home_dir, workspace_policy, session_policy, runtime_selector, capacity_requirements, fallback_policy, status, ready_at, disabled_at, error_at, error_message, deleted_at, metadata, created_at, updated_at
FROM digital_employee_execution_instances
WHERE tenant_id = $1::uuid
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR runtime_node_id = $2::uuid)
  AND ($3::varchar IS NULL OR provider_type = $3::varchar)
  AND ($4::varchar IS NULL OR status = $4::varchar)
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListDigitalEmployeeExecutionInstancesParams struct {
	TenantID      uuid.UUID     `json:"tenant_id"`
	RuntimeNodeID uuid.NullUUID `json:"runtime_node_id"`
	ProviderType  pgtype.Text   `json:"provider_type"`
	Status        pgtype.Text   `json:"status"`
	Offset        int32         `json:"offset"`
	Limit         int32         `json:"limit"`
}

func (q *Queries) ListDigitalEmployeeExecutionInstances(ctx context.Context, arg ListDigitalEmployeeExecutionInstancesParams) ([]DigitalEmployeeExecutionInstance, error) {
	rows, err := q.db.Query(ctx, ListDigitalEmployeeExecutionInstances,
		arg.TenantID,
		arg.RuntimeNodeID,
		arg.ProviderType,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DigitalEmployeeExecutionInstance{}
	for rows.Next() {
		var i DigitalEmployeeExecutionInstance
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DigitalEmployeeID,
			&i.RuntimeNodeID,
			&i.ProviderType,
			&i.AgentHomeDir,
			&i.WorkspacePolicy,
			&i.SessionPolicy,
			&i.RuntimeSelector,
			&i.CapacityRequirements,
			&i.FallbackPolicy,
			&i.Status,
			&i.ReadyAt,
			&i.DisabledAt,
			&i.ErrorAt,
			&i.ErrorMessage,
			&i.DeletedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDigitalEmployees = `-- name: ListDigitalEmployees :many
SELECT id, tenant_id, team_id, name, role, description, status, permission_policy, context_policy, approval_policy, risk_level, metadata, disabled_at, archived_at, deleted_at, created_at, updated_at
FROM digital_employees
WHERE tenant_id = $1::uuid
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR team_id = $2::uuid)
  AND ($3::varchar IS NULL OR status = $3::varchar)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListDigitalEmployeesParams struct {
	TenantID uuid.UUID     `json:"tenant_id"`
	TeamID   uuid.NullUUID `json:"team_id"`
	Status   pgtype.Text   `json:"status"`
	Offset   int32         `json:"offset"`
	Limit    int32         `json:"limit"`
}

func (q *Queries) ListDigitalEmployees(ctx context.Context, arg ListDigitalEmployeesParams) ([]DigitalEmployee, error) {
	rows, err := q.db.Query(ctx, ListDigitalEmployees,
		arg.TenantID,
		arg.TeamID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DigitalEmployee{}
	for rows.Next() {
		var i DigitalEmployee
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TeamID,
			&i.Name,
			&i.Role,
			&i.Description,
			&i.Status,
			&i.PermissionPolicy,
			&i.ContextPolicy,
			&i.ApprovalPolicy,
			&i.RiskLevel,
			&i.Metadata,
			&i.DisabledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateDigitalEmployeeExecutionInstanceStatus = `-- name: UpdateDigitalEmployeeExecutionInstanceStatus :one
UPDATE digital_employee_execution_instances
SET status = $1::varchar,
    ready_at = CASE
        WHEN $1::varchar = 'ready' THEN COALESCE(ready_at, NOW())
        ELSE ready_at
    END,
    disabled_at = CASE
        WHEN $1::varchar = 'disabled' THEN COALESCE(disabled_at, NOW())
        WHEN $1::varchar IN ('provisioning', 'ready', 'active') THEN NULL
        ELSE disabled_at
    END,
    error_at = CASE
        WHEN $1::varchar = 'error' THEN COALESCE(error_at, NOW())
        WHEN $1::varchar IN ('provisioning', 'ready', 'active') THEN NULL
        ELSE error_at
    END,
    error_message = CASE
        WHEN $1::varchar = 'error' THEN COALESCE($2::text, error_message)
        WHEN $1::varchar IN ('provisioning', 'ready', 'active') THEN NULL
        ELSE error_message
    END,
    updated_at = NOW()
WHERE id = $3::uuid
  AND tenant_id = $4::uuid
  AND deleted_at IS NULL
RETURNING id, tenant_id, digital_employee_id, runtime_node_id, provider_type, agent_home_dir, workspace_policy, session_policy, runtime_selector, capacity_requirements, fallback_policy, status, ready_at, disabled_at, error_at, error_message, deleted_at, metadata, created_at, updated_at
`

type UpdateDigitalEmployeeExecutionInstanceStatusParams struct {
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
}

func (q *Queries) UpdateDigitalEmployeeExecutionInstanceStatus(ctx context.Context, arg UpdateDigitalEmployeeExecutionInstanceStatusParams) (DigitalEmployeeExecutionInstance, error) {
	row := q.db.QueryRow(ctx, UpdateDigitalEmployeeExecutionInstanceStatus,
		arg.Status,
		arg.ErrorMessage,
		arg.ID,
		arg.TenantID,
	)
	var i DigitalEmployeeExecutionInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DigitalEmployeeID,
		&i.RuntimeNodeID,
		&i.ProviderType,
		&i.AgentHomeDir,
		&i.WorkspacePolicy,
		&i.SessionPolicy,
		&i.RuntimeSelector,
		&i.CapacityRequirements,
		&i.FallbackPolicy,
		&i.Status,
		&i.ReadyAt,
		&i.DisabledAt,
		&i.ErrorAt,
		&i.ErrorMessage,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateDigitalEmployeeStatus = `-- name: UpdateDigitalEmployeeStatus :one
UPDATE digital_employees
SET status = $1::varchar,
    disabled_at = CASE
        WHEN $1::varchar = 'disabled' THEN COALESCE(disabled_at, NOW())
        WHEN $1::varchar IN ('ready', 'active') THEN NULL
        ELSE disabled_at
    END,
    updated_at = NOW()
WHERE id = $2::uuid
  AND tenant_id = $3::uuid
  AND deleted_at IS NULL
RETURNING id, tenant_id, team_id, name, role, description, status, permission_policy, context_policy, approval_policy, risk_level, metadata, disabled_at, archived_at, deleted_at, created_at, updated_at
`

type UpdateDigitalEmployeeStatusParams struct {
	Status   string    `json:"status"`
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateDigitalEmployeeStatus(ctx context.Context, arg UpdateDigitalEmployeeStatusParams) (DigitalEmployee, error) {
	row := q.db.QueryRow(ctx, UpdateDigitalEmployeeStatus, arg.Status, arg.ID, arg.TenantID)
	var i DigitalEmployee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.Name,
		&i.Role,
		&i.Description,
		&i.Status,
		&i.PermissionPolicy,
		&i.ContextPolicy,
		&i.ApprovalPolicy,
		&i.RiskLevel,
		&i.Metadata,
		&i.DisabledAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpsertDigitalEmployeeExecutionInstance = `-- name: UpsertDigitalEmployeeExecutionInstance :one
INSERT INTO digital_employee_execution_instances (
    tenant_id,
    digital_employee_id,
    runtime_node_id,
    provider_type,
    agent_home_dir,
    workspace_policy,
    session_policy,
    runtime_selector,
    capacity_requirements,
    fallback_policy,
    status,
    metadata
) SELECT
    de.tenant_id,
    de.id,
    rn.id,
    $1::varchar,
    $2::text,
    COALESCE($3::jsonb, '{}'::jsonb),
    COALESCE($4::jsonb, '{}'::jsonb),
    COALESCE($5::jsonb, '{}'::jsonb),
    COALESCE($6::jsonb, '{}'::jsonb),
    COALESCE($7::jsonb, '{}'::jsonb),
    $8::varchar,
    COALESCE($9::jsonb, '{}'::jsonb)
FROM digital_employees de
JOIN runtime_nodes rn
  ON rn.id = $10::uuid
 AND rn.tenant_id = de.tenant_id
 AND rn.status = 'online'
 AND rn.disabled_at IS NULL
 AND rn.archived_at IS NULL
WHERE de.id = $11::uuid
  AND de.tenant_id = $12::uuid
  AND de.status NOT IN ('disabled', 'error')
  AND de.deleted_at IS NULL
  AND de.archived_at IS NULL
  AND EXISTS (
      SELECT 1
      FROM runtime_enrollments re
      WHERE re.tenant_id = de.tenant_id
        AND re.runtime_node_id = rn.id
        AND re.status = 'approved'
  )
  AND EXISTS (
      SELECT 1
      FROM runtime_capabilities rc
      WHERE rc.tenant_id = de.tenant_id
        AND rc.runtime_node_id = rn.id
        AND rc.capability_type = 'provider'
        AND rc.provider_type = $1::varchar
        AND rc.available = true
        AND rc.status = 'healthy'
        AND rc.health_status = 'healthy'
        AND rc.disabled_at IS NULL
        AND rc.archived_at IS NULL
  )
ON CONFLICT (tenant_id, digital_employee_id) WHERE deleted_at IS NULL DO UPDATE SET
    runtime_node_id = EXCLUDED.runtime_node_id,
    provider_type = EXCLUDED.provider_type,
    agent_home_dir = EXCLUDED.agent_home_dir,
    workspace_policy = EXCLUDED.workspace_policy,
    session_policy = EXCLUDED.session_policy,
    runtime_selector = EXCLUDED.runtime_selector,
    capacity_requirements = EXCLUDED.capacity_requirements,
    fallback_policy = EXCLUDED.fallback_policy,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    updated_at = NOW()
RETURNING id, tenant_id, digital_employee_id, runtime_node_id, provider_type, agent_home_dir, workspace_policy, session_policy, runtime_selector, capacity_requirements, fallback_policy, status, ready_at, disabled_at, error_at, error_message, deleted_at, metadata, created_at, updated_at
`

type UpsertDigitalEmployeeExecutionInstanceParams struct {
	ProviderType         string    `json:"provider_type"`
	AgentHomeDir         string    `json:"agent_home_dir"`
	WorkspacePolicy      []byte    `json:"workspace_policy"`
	SessionPolicy        []byte    `json:"session_policy"`
	RuntimeSelector      []byte    `json:"runtime_selector"`
	CapacityRequirements []byte    `json:"capacity_requirements"`
	FallbackPolicy       []byte    `json:"fallback_policy"`
	Status               string    `json:"status"`
	Metadata             []byte    `json:"metadata"`
	RuntimeNodeID        uuid.UUID `json:"runtime_node_id"`
	DigitalEmployeeID    uuid.UUID `json:"digital_employee_id"`
	TenantID             uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpsertDigitalEmployeeExecutionInstance(ctx context.Context, arg UpsertDigitalEmployeeExecutionInstanceParams) (DigitalEmployeeExecutionInstance, error) {
	row := q.db.QueryRow(ctx, UpsertDigitalEmployeeExecutionInstance,
		arg.ProviderType,
		arg.AgentHomeDir,
		arg.WorkspacePolicy,
		arg.SessionPolicy,
		arg.RuntimeSelector,
		arg.CapacityRequirements,
		arg.FallbackPolicy,
		arg.Status,
		arg.Metadata,
		arg.RuntimeNodeID,
		arg.DigitalEmployeeID,
		arg.TenantID,
	)
	var i DigitalEmployeeExecutionInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DigitalEmployeeID,
		&i.RuntimeNodeID,
		&i.ProviderType,
		&i.AgentHomeDir,
		&i.WorkspacePolicy,
		&i.SessionPolicy,
		&i.RuntimeSelector,
		&i.CapacityRequirements,
		&i.FallbackPolicy,
		&i.Status,
		&i.ReadyAt,
		&i.DisabledAt,
		&i.ErrorAt,
		&i.ErrorMessage,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
