// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employee_execution.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const AbortProvisionedDigitalEmployee = `-- name: AbortProvisionedDigitalEmployee :exec
WITH abort_args AS (
    SELECT
        $1::text AS reason,
        $2::uuid AS execution_instance_id,
        $3::uuid AS tenant_id,
        $4::uuid AS digital_employee_id,
        $2::uuid = '00000000-0000-0000-0000-000000000000'::uuid AS abort_by_employee
),
aborted_instance AS (
    UPDATE digital_employee_execution_instances dei
    SET status = 'error',
        error_at = COALESCE(dei.error_at, NOW()),
        error_message = abort_args.reason,
        deleted_at = COALESCE(dei.deleted_at, NOW()),
        updated_at = NOW()
    FROM abort_args
    WHERE dei.id = abort_args.execution_instance_id
      AND dei.tenant_id = abort_args.tenant_id
      AND dei.digital_employee_id = abort_args.digital_employee_id
      AND NOT abort_args.abort_by_employee
    RETURNING dei.id
),
abort_scope AS (
    SELECT abort_args.abort_by_employee OR EXISTS (SELECT 1 FROM aborted_instance) AS matched
    FROM abort_args
),
aborted_employee AS (
    UPDATE digital_employees de
    SET status = 'error',
        deleted_at = COALESCE(de.deleted_at, NOW()),
        updated_at = NOW()
    FROM abort_args
    WHERE de.id = abort_args.digital_employee_id
      AND de.tenant_id = abort_args.tenant_id
      AND EXISTS (SELECT 1 FROM abort_scope WHERE matched)
    RETURNING de.id
),
aborted_configs AS (
    UPDATE digital_employee_config_revisions decr
    SET archived_at = COALESCE(decr.archived_at, NOW()),
        updated_at = NOW()
    FROM abort_args
    WHERE decr.tenant_id = abort_args.tenant_id
      AND decr.digital_employee_id = abort_args.digital_employee_id
      AND decr.archived_at IS NULL
      AND EXISTS (SELECT 1 FROM aborted_employee)
      AND EXISTS (SELECT 1 FROM abort_scope WHERE matched)
    RETURNING decr.id
),
aborted_effective_configs AS (
    UPDATE digital_employee_effective_configs deec
    SET status = CASE
            WHEN deec.status = 'revoked' THEN deec.status
            ELSE 'revoked'
        END,
        revoked_at = COALESCE(deec.revoked_at, NOW()),
        updated_at = NOW()
    FROM abort_args
    WHERE deec.tenant_id = abort_args.tenant_id
      AND deec.digital_employee_id = abort_args.digital_employee_id
      AND deec.revoked_at IS NULL
      AND EXISTS (SELECT 1 FROM aborted_employee)
      AND EXISTS (SELECT 1 FROM abort_scope WHERE matched)
    RETURNING deec.id
),
aborted_workspace_files AS (
    UPDATE digital_employee_workspace_files dewf
    SET status = 'deleted',
        archived_at = COALESCE(dewf.archived_at, NOW()),
        deleted_at = COALESCE(dewf.deleted_at, NOW()),
        updated_at = NOW()
    FROM abort_args
    WHERE dewf.tenant_id = abort_args.tenant_id
      AND dewf.digital_employee_id = abort_args.digital_employee_id
      AND dewf.deleted_at IS NULL
      AND EXISTS (SELECT 1 FROM aborted_employee)
      AND EXISTS (SELECT 1 FROM abort_scope WHERE matched)
    RETURNING dewf.id
),
aborted_receipts AS (
    UPDATE runtime_command_receipts rcr
    SET status = CASE
            WHEN rcr.status IN ('completed', 'failed', 'cancelled', 'timed_out') THEN rcr.status
            ELSE 'failed'
        END,
        error_message = COALESCE(rcr.error_message, abort_args.reason),
        completed_at = CASE
            WHEN rcr.status IN ('completed', 'failed', 'cancelled', 'timed_out') THEN rcr.completed_at
            ELSE COALESCE(rcr.completed_at, NOW())
        END,
        updated_at = NOW()
    FROM abort_args
    JOIN aborted_instance ai ON TRUE
    JOIN aborted_employee ae ON TRUE
    WHERE rcr.tenant_id = abort_args.tenant_id
      AND rcr.resource_type = 'digital_employee_execution_instance'
      AND rcr.resource_id = ai.id
    RETURNING rcr.id
)
SELECT 1
`

type AbortProvisionedDigitalEmployeeParams struct {
	Reason              string    `json:"reason"`
	ExecutionInstanceID uuid.UUID `json:"execution_instance_id"`
	TenantID            uuid.UUID `json:"tenant_id"`
	DigitalEmployeeID   uuid.UUID `json:"digital_employee_id"`
}

func (q *Queries) AbortProvisionedDigitalEmployee(ctx context.Context, arg AbortProvisionedDigitalEmployeeParams) error {
	_, err := q.db.Exec(ctx, AbortProvisionedDigitalEmployee,
		arg.Reason,
		arg.ExecutionInstanceID,
		arg.TenantID,
		arg.DigitalEmployeeID,
	)
	return err
}

const CreateDigitalEmployee = `-- name: CreateDigitalEmployee :one
INSERT INTO digital_employees (
    tenant_id,
    team_id,
    owner_user_id,
    employee_type,
    name,
    role,
    description,
    status,
    permission_policy,
    context_policy,
    approval_policy,
    risk_level,
    metadata
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::varchar,
    $5::varchar,
    $6::varchar,
    $7::text,
    $8::varchar,
    COALESCE($9::jsonb, '{}'::jsonb),
    COALESCE($10::jsonb, '{}'::jsonb),
    COALESCE($11::jsonb, '{}'::jsonb),
    $12::varchar,
    COALESCE($13::jsonb, '{}'::jsonb)
) RETURNING id, tenant_id, team_id, name, role, description, status, permission_policy, context_policy, approval_policy, risk_level, metadata, disabled_at, archived_at, deleted_at, created_at, updated_at, owner_user_id, employee_type
`

type CreateDigitalEmployeeParams struct {
	TenantID         uuid.UUID     `json:"tenant_id"`
	TeamID           uuid.NullUUID `json:"team_id"`
	OwnerUserID      uuid.UUID     `json:"owner_user_id"`
	EmployeeType     string        `json:"employee_type"`
	Name             string        `json:"name"`
	Role             string        `json:"role"`
	Description      pgtype.Text   `json:"description"`
	Status           string        `json:"status"`
	PermissionPolicy []byte        `json:"permission_policy"`
	ContextPolicy    []byte        `json:"context_policy"`
	ApprovalPolicy   []byte        `json:"approval_policy"`
	RiskLevel        string        `json:"risk_level"`
	Metadata         []byte        `json:"metadata"`
}

func (q *Queries) CreateDigitalEmployee(ctx context.Context, arg CreateDigitalEmployeeParams) (DigitalEmployee, error) {
	row := q.db.QueryRow(ctx, CreateDigitalEmployee,
		arg.TenantID,
		arg.TeamID,
		arg.OwnerUserID,
		arg.EmployeeType,
		arg.Name,
		arg.Role,
		arg.Description,
		arg.Status,
		arg.PermissionPolicy,
		arg.ContextPolicy,
		arg.ApprovalPolicy,
		arg.RiskLevel,
		arg.Metadata,
	)
	var i DigitalEmployee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.Name,
		&i.Role,
		&i.Description,
		&i.Status,
		&i.PermissionPolicy,
		&i.ContextPolicy,
		&i.ApprovalPolicy,
		&i.RiskLevel,
		&i.Metadata,
		&i.DisabledAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
		&i.EmployeeType,
	)
	return i, err
}

const DeleteDigitalEmployee = `-- name: DeleteDigitalEmployee :exec
UPDATE digital_employees
SET deleted_at = COALESCE(deleted_at, NOW()),
    updated_at = NOW()
WHERE id = $1::uuid
  AND tenant_id = $2::uuid
`

type DeleteDigitalEmployeeParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteDigitalEmployee(ctx context.Context, arg DeleteDigitalEmployeeParams) error {
	_, err := q.db.Exec(ctx, DeleteDigitalEmployee, arg.ID, arg.TenantID)
	return err
}

const DeleteDigitalEmployeeExecutionInstance = `-- name: DeleteDigitalEmployeeExecutionInstance :exec
UPDATE digital_employee_execution_instances
SET deleted_at = COALESCE(deleted_at, NOW()),
    updated_at = NOW()
WHERE id = $1::uuid
  AND tenant_id = $2::uuid
`

type DeleteDigitalEmployeeExecutionInstanceParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteDigitalEmployeeExecutionInstance(ctx context.Context, arg DeleteDigitalEmployeeExecutionInstanceParams) error {
	_, err := q.db.Exec(ctx, DeleteDigitalEmployeeExecutionInstance, arg.ID, arg.TenantID)
	return err
}

const GetDigitalEmployee = `-- name: GetDigitalEmployee :one
SELECT id, tenant_id, team_id, name, role, description, status, permission_policy, context_policy, approval_policy, risk_level, metadata, disabled_at, archived_at, deleted_at, created_at, updated_at, owner_user_id, employee_type
FROM digital_employees
WHERE id = $1::uuid
  AND tenant_id = $2::uuid
  AND deleted_at IS NULL
`

type GetDigitalEmployeeParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetDigitalEmployee(ctx context.Context, arg GetDigitalEmployeeParams) (DigitalEmployee, error) {
	row := q.db.QueryRow(ctx, GetDigitalEmployee, arg.ID, arg.TenantID)
	var i DigitalEmployee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.Name,
		&i.Role,
		&i.Description,
		&i.Status,
		&i.PermissionPolicy,
		&i.ContextPolicy,
		&i.ApprovalPolicy,
		&i.RiskLevel,
		&i.Metadata,
		&i.DisabledAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
		&i.EmployeeType,
	)
	return i, err
}

const GetDigitalEmployeeExecutionInstance = `-- name: GetDigitalEmployeeExecutionInstance :one
SELECT id, tenant_id, digital_employee_id, runtime_node_id, provider_type, agent_home_dir, workspace_policy, session_policy, runtime_selector, capacity_requirements, fallback_policy, status, ready_at, disabled_at, error_at, error_message, deleted_at, metadata, created_at, updated_at
FROM digital_employee_execution_instances
WHERE id = $1::uuid
  AND tenant_id = $2::uuid
  AND deleted_at IS NULL
`

type GetDigitalEmployeeExecutionInstanceParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetDigitalEmployeeExecutionInstance(ctx context.Context, arg GetDigitalEmployeeExecutionInstanceParams) (DigitalEmployeeExecutionInstance, error) {
	row := q.db.QueryRow(ctx, GetDigitalEmployeeExecutionInstance, arg.ID, arg.TenantID)
	var i DigitalEmployeeExecutionInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DigitalEmployeeID,
		&i.RuntimeNodeID,
		&i.ProviderType,
		&i.AgentHomeDir,
		&i.WorkspacePolicy,
		&i.SessionPolicy,
		&i.RuntimeSelector,
		&i.CapacityRequirements,
		&i.FallbackPolicy,
		&i.Status,
		&i.ReadyAt,
		&i.DisabledAt,
		&i.ErrorAt,
		&i.ErrorMessage,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetDigitalEmployeeExecutionInstanceByEmployeeID = `-- name: GetDigitalEmployeeExecutionInstanceByEmployeeID :one
SELECT id, tenant_id, digital_employee_id, runtime_node_id, provider_type, agent_home_dir, workspace_policy, session_policy, runtime_selector, capacity_requirements, fallback_policy, status, ready_at, disabled_at, error_at, error_message, deleted_at, metadata, created_at, updated_at
FROM digital_employee_execution_instances
WHERE digital_employee_id = $1::uuid
  AND tenant_id = $2::uuid
  AND deleted_at IS NULL
`

type GetDigitalEmployeeExecutionInstanceByEmployeeIDParams struct {
	DigitalEmployeeID uuid.UUID `json:"digital_employee_id"`
	TenantID          uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetDigitalEmployeeExecutionInstanceByEmployeeID(ctx context.Context, arg GetDigitalEmployeeExecutionInstanceByEmployeeIDParams) (DigitalEmployeeExecutionInstance, error) {
	row := q.db.QueryRow(ctx, GetDigitalEmployeeExecutionInstanceByEmployeeID, arg.DigitalEmployeeID, arg.TenantID)
	var i DigitalEmployeeExecutionInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DigitalEmployeeID,
		&i.RuntimeNodeID,
		&i.ProviderType,
		&i.AgentHomeDir,
		&i.WorkspacePolicy,
		&i.SessionPolicy,
		&i.RuntimeSelector,
		&i.CapacityRequirements,
		&i.FallbackPolicy,
		&i.Status,
		&i.ReadyAt,
		&i.DisabledAt,
		&i.ErrorAt,
		&i.ErrorMessage,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetDigitalEmployeeOverviewSummary = `-- name: GetDigitalEmployeeOverviewSummary :one
WITH overview_args AS (
    SELECT
        $1::uuid AS tenant_id,
        NULLIF(BTRIM($2::text), '') AS q,
        $3::uuid AS team_id,
        NULLIF(BTRIM($4::text), '') AS status,
        NULLIF(BTRIM($5::text), '') AS employee_type,
        NULLIF(BTRIM($6::text), '') AS provider_type,
        $7::uuid AS runtime_node_id,
        NULLIF(BTRIM($8::text), '') AS risk_level,
        NULLIF(BTRIM($9::text), '') AS execution_status,
        NULLIF(BTRIM($10::text), '') AS run_status
),
provider_capabilities AS (
    SELECT DISTINCT ON (rc.tenant_id, rc.runtime_node_id, rc.provider_type)
        rc.tenant_id,
        rc.runtime_node_id,
        rc.provider_type,
        rc.status,
        rc.health_status,
        rc.available
    FROM runtime_capabilities rc
    JOIN overview_args args ON args.tenant_id = rc.tenant_id
    WHERE rc.capability_type = 'provider'
      AND rc.disabled_at IS NULL
      AND rc.archived_at IS NULL
    ORDER BY rc.tenant_id, rc.runtime_node_id, rc.provider_type, rc.last_seen_at DESC NULLS LAST, rc.updated_at DESC
),
latest_runs AS (
    SELECT DISTINCT ON (tr.tenant_id, tr.digital_employee_id)
        tr.tenant_id,
        tr.digital_employee_id,
        tr.status
    FROM task_runs tr
    JOIN overview_args args ON args.tenant_id = tr.tenant_id
    JOIN tasks t ON t.id = tr.task_id AND t.tenant_id = tr.tenant_id
    WHERE tr.digital_employee_id IS NOT NULL
      AND t.deleted_at IS NULL
    ORDER BY tr.tenant_id, tr.digital_employee_id, tr.updated_at DESC, tr.created_at DESC
),
effective_configs AS (
    SELECT DISTINCT ON (ec.tenant_id, ec.digital_employee_id)
        ec.tenant_id,
        ec.digital_employee_id,
        ec.id AS effective_config_id,
        ec.status
    FROM digital_employee_effective_configs ec
    JOIN overview_args args ON args.tenant_id = ec.tenant_id
    WHERE ec.status = 'approved'
      AND ec.revoked_at IS NULL
    ORDER BY ec.tenant_id, ec.digital_employee_id, ec.created_at DESC, ec.updated_at DESC
),
governance_configs AS (
    SELECT DISTINCT ON (ec.tenant_id, ec.digital_employee_id)
        ec.tenant_id,
        ec.digital_employee_id,
        ec.status
    FROM digital_employee_effective_configs ec
    JOIN overview_args args ON args.tenant_id = ec.tenant_id
    WHERE ec.revoked_at IS NULL
    ORDER BY ec.tenant_id, ec.digital_employee_id, ec.created_at DESC, ec.updated_at DESC
),
overview_rows AS (
    SELECT
        de.id,
        de.name,
        de.role,
        de.description,
        de.team_id,
        de.status AS employee_status,
        de.employee_type,
        de.risk_level,
        COALESCE(dei.status, 'missing')::text AS execution_status,
        dei.runtime_node_id,
        rn.status AS runtime_status,
        rn.disabled_at AS runtime_disabled_at,
        rn.archived_at AS runtime_archived_at,
        COALESCE(dei.provider_type, '')::text AS provider_type,
        (NULLIF(BTRIM(COALESCE(dei.agent_home_dir, '')), '') IS NOT NULL)::boolean AS agent_home_dir_available,
        COALESCE(pc.available, false)::boolean AS provider_available,
        COALESCE(pc.status, '')::text AS provider_status,
        COALESCE(pc.health_status, '')::text AS provider_health_status,
        COALESCE(lr.status, 'none')::text AS run_status,
        ec.effective_config_id,
        COALESCE(gc.status, 'missing')::text AS governance_status
    FROM digital_employees de
    CROSS JOIN overview_args args
    LEFT JOIN digital_employee_execution_instances dei
     ON dei.tenant_id = de.tenant_id
     AND dei.digital_employee_id = de.id
     AND dei.deleted_at IS NULL
    LEFT JOIN runtime_nodes rn
      ON rn.id = dei.runtime_node_id
     AND rn.tenant_id = dei.tenant_id
    LEFT JOIN provider_capabilities pc
      ON pc.tenant_id = dei.tenant_id
     AND pc.runtime_node_id = dei.runtime_node_id
     AND pc.provider_type = dei.provider_type
    LEFT JOIN latest_runs lr
      ON lr.tenant_id = de.tenant_id
     AND lr.digital_employee_id = de.id
    LEFT JOIN effective_configs ec
      ON ec.tenant_id = de.tenant_id
     AND ec.digital_employee_id = de.id
    LEFT JOIN governance_configs gc
      ON gc.tenant_id = de.tenant_id
     AND gc.digital_employee_id = de.id
    WHERE de.tenant_id = args.tenant_id
      AND de.deleted_at IS NULL
),
filtered_rows AS (
    SELECT overview_rows.id, overview_rows.name, overview_rows.role, overview_rows.description, overview_rows.team_id, overview_rows.employee_status, overview_rows.employee_type, overview_rows.risk_level, overview_rows.execution_status, overview_rows.runtime_node_id, overview_rows.runtime_status, overview_rows.runtime_disabled_at, overview_rows.runtime_archived_at, overview_rows.provider_type, overview_rows.agent_home_dir_available, overview_rows.provider_available, overview_rows.provider_status, overview_rows.provider_health_status, overview_rows.run_status, overview_rows.effective_config_id, overview_rows.governance_status
    FROM overview_rows
    CROSS JOIN overview_args args
    WHERE (
        args.q IS NULL
        OR overview_rows.name ILIKE '%' || args.q || '%'
        OR overview_rows.role ILIKE '%' || args.q || '%'
        OR overview_rows.description ILIKE '%' || args.q || '%'
    )
      AND (args.team_id IS NULL OR overview_rows.team_id = args.team_id)
      AND (args.status IS NULL OR overview_rows.employee_status = args.status)
      AND (args.employee_type IS NULL OR overview_rows.employee_type = args.employee_type)
      AND (args.provider_type IS NULL OR overview_rows.provider_type = args.provider_type)
      AND (args.runtime_node_id IS NULL OR overview_rows.runtime_node_id = args.runtime_node_id)
      AND (args.risk_level IS NULL OR overview_rows.risk_level = args.risk_level)
      AND (args.execution_status IS NULL OR overview_rows.execution_status = args.execution_status)
      AND (args.run_status IS NULL OR overview_rows.run_status = args.run_status)
)
SELECT
    COUNT(*)::integer AS total_count,
    (COUNT(*) FILTER (
        WHERE employee_status IN ('ready', 'active')
          AND execution_status IN ('ready', 'active')
          AND effective_config_id IS NOT NULL
          AND runtime_node_id IS NOT NULL
          AND runtime_status = 'online'
          AND runtime_disabled_at IS NULL
          AND runtime_archived_at IS NULL
          AND agent_home_dir_available = true
          AND governance_status = 'approved'
          AND provider_available = true
          AND provider_status = 'healthy'
          AND provider_health_status = 'healthy'
    ))::integer AS runnable_count,
    (COUNT(*) FILTER (
        WHERE run_status IN ('queued', 'dispatching', 'running', 'cancelling')
    ))::integer AS running_count,
    (COUNT(*) FILTER (
        WHERE execution_status IN ('missing', 'provisioning')
    ))::integer AS waiting_runtime_count,
    (COUNT(*) FILTER (
        WHERE employee_status IN ('disabled', 'error')
           OR execution_status IN ('disabled', 'error')
           OR run_status IN ('failed', 'timed_out')
           OR (
               runtime_node_id IS NOT NULL
               AND (
                   runtime_status <> 'online'
                   OR runtime_disabled_at IS NOT NULL
                   OR runtime_archived_at IS NOT NULL
               )
           )
           OR (
               provider_type <> ''
               AND (
                   provider_available = false
                   OR provider_status <> 'healthy'
                   OR provider_health_status <> 'healthy'
               )
           )
    ))::integer AS error_count,
    (COUNT(*) FILTER (
        WHERE risk_level IN ('high', 'critical')
    ))::integer AS high_risk_count,
    (COUNT(*) FILTER (
        WHERE employee_status IN ('ready', 'active')
          AND execution_status IN ('ready', 'active')
          AND effective_config_id IS NOT NULL
          AND runtime_node_id IS NOT NULL
          AND runtime_status = 'online'
          AND runtime_disabled_at IS NULL
          AND runtime_archived_at IS NULL
          AND agent_home_dir_available = true
          AND governance_status = 'approved'
          AND provider_available = true
          AND provider_status = 'healthy'
          AND provider_health_status = 'healthy'
          AND run_status NOT IN ('failed', 'timed_out')
    ))::integer AS ready_count,
    (COUNT(*) FILTER (
        WHERE execution_status IN ('missing', 'provisioning')
           OR runtime_node_id IS NULL
           OR provider_type = ''
           OR agent_home_dir_available = false
    ))::integer AS pending_runtime_binding_count,
    (COUNT(*) FILTER (
        WHERE governance_status IN ('missing', 'pending_approval', 'stale')
    ))::integer AS pending_config_approval_count,
    (COUNT(*) FILTER (
        WHERE run_status IN ('failed', 'timed_out')
    ))::integer AS failed_recent_run_count,
    (COUNT(*) FILTER (
        WHERE governance_status IN ('missing', 'pending_approval', 'stale')
    ))::integer AS stale_config_count
FROM filtered_rows
`

type GetDigitalEmployeeOverviewSummaryParams struct {
	TenantID        uuid.UUID     `json:"tenant_id"`
	Q               pgtype.Text   `json:"q"`
	TeamID          uuid.NullUUID `json:"team_id"`
	Status          pgtype.Text   `json:"status"`
	EmployeeType    pgtype.Text   `json:"employee_type"`
	ProviderType    pgtype.Text   `json:"provider_type"`
	RuntimeNodeID   uuid.NullUUID `json:"runtime_node_id"`
	RiskLevel       pgtype.Text   `json:"risk_level"`
	ExecutionStatus pgtype.Text   `json:"execution_status"`
	RunStatus       pgtype.Text   `json:"run_status"`
}

type GetDigitalEmployeeOverviewSummaryRow struct {
	TotalCount                 int32 `json:"total_count"`
	RunnableCount              int32 `json:"runnable_count"`
	RunningCount               int32 `json:"running_count"`
	WaitingRuntimeCount        int32 `json:"waiting_runtime_count"`
	ErrorCount                 int32 `json:"error_count"`
	HighRiskCount              int32 `json:"high_risk_count"`
	ReadyCount                 int32 `json:"ready_count"`
	PendingRuntimeBindingCount int32 `json:"pending_runtime_binding_count"`
	PendingConfigApprovalCount int32 `json:"pending_config_approval_count"`
	FailedRecentRunCount       int32 `json:"failed_recent_run_count"`
	StaleConfigCount           int32 `json:"stale_config_count"`
}

func (q *Queries) GetDigitalEmployeeOverviewSummary(ctx context.Context, arg GetDigitalEmployeeOverviewSummaryParams) (GetDigitalEmployeeOverviewSummaryRow, error) {
	row := q.db.QueryRow(ctx, GetDigitalEmployeeOverviewSummary,
		arg.TenantID,
		arg.Q,
		arg.TeamID,
		arg.Status,
		arg.EmployeeType,
		arg.ProviderType,
		arg.RuntimeNodeID,
		arg.RiskLevel,
		arg.ExecutionStatus,
		arg.RunStatus,
	)
	var i GetDigitalEmployeeOverviewSummaryRow
	err := row.Scan(
		&i.TotalCount,
		&i.RunnableCount,
		&i.RunningCount,
		&i.WaitingRuntimeCount,
		&i.ErrorCount,
		&i.HighRiskCount,
		&i.ReadyCount,
		&i.PendingRuntimeBindingCount,
		&i.PendingConfigApprovalCount,
		&i.FailedRecentRunCount,
		&i.StaleConfigCount,
	)
	return i, err
}

const GetDigitalEmployeeRunPreflight = `-- name: GetDigitalEmployeeRunPreflight :one
SELECT
    de.tenant_id,
    de.team_id,
    de.id AS digital_employee_id,
    de.status AS digital_employee_status,
    dei.id AS execution_instance_id,
    dei.status AS execution_status,
    dei.runtime_node_id,
    rn.node_id,
    dei.provider_type,
    dei.agent_home_dir,
    dei.runtime_selector,
    dei.session_policy,
    dei.workspace_policy,
    COALESCE(ec.effective_config_snapshot -> 'budget_policy', '{}'::jsonb)::jsonb AS budget_policy,
    COALESCE(today_usage.usage_tokens_today, 0)::integer AS today_token_usage,
    'Asia/Shanghai'::text AS business_timezone,
    (ec.effective_config_id IS NOT NULL)::boolean AS has_approved_effective_config,
    EXISTS (
        SELECT 1
        FROM runtime_capabilities rc
        WHERE rc.tenant_id = de.tenant_id
          AND rc.runtime_node_id = dei.runtime_node_id
          AND rc.capability_type = 'provider'
          AND rc.provider_type = dei.provider_type
          AND rc.available = true
          AND rc.status = 'healthy'
          AND rc.health_status = 'healthy'
          AND rc.disabled_at IS NULL
          AND rc.archived_at IS NULL
    ) AS provider_healthy
FROM digital_employees de
JOIN digital_employee_execution_instances dei
  ON dei.digital_employee_id = de.id
 AND dei.tenant_id = de.tenant_id
 AND dei.deleted_at IS NULL
JOIN runtime_nodes rn
  ON rn.id = dei.runtime_node_id
 AND rn.tenant_id = de.tenant_id
 AND rn.archived_at IS NULL
LEFT JOIN LATERAL (
    SELECT
        dec.id AS effective_config_id,
        dec.effective_config_snapshot
    FROM digital_employee_effective_configs dec
    WHERE dec.tenant_id = de.tenant_id
      AND dec.digital_employee_id = de.id
      AND dec.status = 'approved'
      AND dec.revoked_at IS NULL
    ORDER BY dec.created_at DESC, dec.updated_at DESC
    LIMIT 1
) ec ON true
LEFT JOIN LATERAL (
    SELECT
        LEAST(
            COALESCE(
                SUM(
                    CASE
                        WHEN COALESCE(tr.result #>> '{usage,total_tokens}', tr.result ->> 'total_tokens', '') ~ '^[0-9]+$'
                        THEN COALESCE(tr.result #>> '{usage,total_tokens}', tr.result ->> 'total_tokens', '')::bigint
                        ELSE 0
                    END
                ),
                0
            ),
            2147483647
        )::integer AS usage_tokens_today
    FROM task_runs tr
    WHERE tr.tenant_id = de.tenant_id
      AND tr.digital_employee_id = de.id
      AND COALESCE(tr.finished_at, tr.updated_at, tr.created_at) >= (date_trunc('day', timezone('Asia/Shanghai', now())) AT TIME ZONE 'Asia/Shanghai')
      AND COALESCE(tr.finished_at, tr.updated_at, tr.created_at) < ((date_trunc('day', timezone('Asia/Shanghai', now())) + INTERVAL '1 day') AT TIME ZONE 'Asia/Shanghai')
) today_usage ON true
WHERE de.id = $1::uuid
  AND de.tenant_id = $2::uuid
  AND de.deleted_at IS NULL
  AND de.archived_at IS NULL
`

type GetDigitalEmployeeRunPreflightParams struct {
	DigitalEmployeeID uuid.UUID `json:"digital_employee_id"`
	TenantID          uuid.UUID `json:"tenant_id"`
}

type GetDigitalEmployeeRunPreflightRow struct {
	TenantID                   uuid.UUID     `json:"tenant_id"`
	TeamID                     uuid.NullUUID `json:"team_id"`
	DigitalEmployeeID          uuid.UUID     `json:"digital_employee_id"`
	DigitalEmployeeStatus      string        `json:"digital_employee_status"`
	ExecutionInstanceID        uuid.UUID     `json:"execution_instance_id"`
	ExecutionStatus            string        `json:"execution_status"`
	RuntimeNodeID              uuid.UUID     `json:"runtime_node_id"`
	NodeID                     string        `json:"node_id"`
	ProviderType               string        `json:"provider_type"`
	AgentHomeDir               string        `json:"agent_home_dir"`
	RuntimeSelector            []byte        `json:"runtime_selector"`
	SessionPolicy              []byte        `json:"session_policy"`
	WorkspacePolicy            []byte        `json:"workspace_policy"`
	BudgetPolicy               []byte        `json:"budget_policy"`
	TodayTokenUsage            int32         `json:"today_token_usage"`
	BusinessTimezone           string        `json:"business_timezone"`
	HasApprovedEffectiveConfig bool          `json:"has_approved_effective_config"`
	ProviderHealthy            bool          `json:"provider_healthy"`
}

func (q *Queries) GetDigitalEmployeeRunPreflight(ctx context.Context, arg GetDigitalEmployeeRunPreflightParams) (GetDigitalEmployeeRunPreflightRow, error) {
	row := q.db.QueryRow(ctx, GetDigitalEmployeeRunPreflight, arg.DigitalEmployeeID, arg.TenantID)
	var i GetDigitalEmployeeRunPreflightRow
	err := row.Scan(
		&i.TenantID,
		&i.TeamID,
		&i.DigitalEmployeeID,
		&i.DigitalEmployeeStatus,
		&i.ExecutionInstanceID,
		&i.ExecutionStatus,
		&i.RuntimeNodeID,
		&i.NodeID,
		&i.ProviderType,
		&i.AgentHomeDir,
		&i.RuntimeSelector,
		&i.SessionPolicy,
		&i.WorkspacePolicy,
		&i.BudgetPolicy,
		&i.TodayTokenUsage,
		&i.BusinessTimezone,
		&i.HasApprovedEffectiveConfig,
		&i.ProviderHealthy,
	)
	return i, err
}

const GetRuntimeProvisioningPreflight = `-- name: GetRuntimeProvisioningPreflight :one
WITH active_team_config AS (
    SELECT id, tenant_id, team_id, revision_number, constitution, capability_policy, context_policy, approval_policy, artifact_contract, internal_collaboration_policy, runtime_scope_policy, status, approved_by, approved_at, archived_at, created_at, updated_at, human_owner_user_ids
    FROM tenant_team_config_revisions
    WHERE tenant_id = $3::uuid
      AND team_id = $4::uuid
      AND status = 'active'
      AND archived_at IS NULL
    ORDER BY revision_number DESC
    LIMIT 1
),
provider_capability AS (
    SELECT id, tenant_id, runtime_node_id, capability_type, capability_key, provider_type, provider_version, binary_path, available, workspace_base_dir, capacity, labels, status, details, health_status, metadata, last_seen_at, disabled_at, archived_at, created_at, updated_at
    FROM runtime_capabilities
    WHERE tenant_id = $3::uuid
      AND runtime_node_id = $2::uuid
      AND capability_type = 'provider'
      AND provider_type = $1::varchar
      AND available = true
      AND status = 'healthy'
      AND health_status = 'healthy'
      AND disabled_at IS NULL
      AND archived_at IS NULL
    ORDER BY last_seen_at DESC NULLS LAST, updated_at DESC
    LIMIT 1
),
workspace_capability AS (
    SELECT id, tenant_id, runtime_node_id, capability_type, capability_key, provider_type, provider_version, binary_path, available, workspace_base_dir, capacity, labels, status, details, health_status, metadata, last_seen_at, disabled_at, archived_at, created_at, updated_at
    FROM runtime_capabilities
    WHERE tenant_id = $3::uuid
      AND runtime_node_id = $2::uuid
      AND capability_type = 'workspace'
      AND capability_key = 'base-dir'
      AND available = true
      AND disabled_at IS NULL
      AND archived_at IS NULL
    ORDER BY last_seen_at DESC NULLS LAST, updated_at DESC
    LIMIT 1
)
SELECT
    tt.tenant_id,
    tt.id AS team_id,
    rn.id AS runtime_node_id,
    rn.node_id,
    COALESCE(
        provider_capability.details ->> 'agent_home_dir',
        provider_capability.metadata ->> 'agent_home_dir',
        provider_capability.workspace_base_dir,
        workspace_capability.details ->> 'agent_home_dir',
        workspace_capability.metadata ->> 'agent_home_dir',
        workspace_capability.workspace_base_dir,
        rn.metadata ->> 'agent_home_dir',
        ''
    )::text AS agent_home_dir,
    COALESCE(
        jsonb_build_object(
            'team_config_revision_id', active_team_config.id,
            'revision_number', active_team_config.revision_number,
            'constitution', active_team_config.constitution,
            'capability_policy', active_team_config.capability_policy,
            'context_policy', active_team_config.context_policy,
            'approval_policy', active_team_config.approval_policy,
            'artifact_contract', active_team_config.artifact_contract,
            'internal_collaboration_policy', active_team_config.internal_collaboration_policy,
            'runtime_scope_policy', active_team_config.runtime_scope_policy,
            'approved_by', active_team_config.approved_by,
            'approved_at', active_team_config.approved_at
        ),
        '{}'::jsonb
    ) AS governance_snapshot,
    (active_team_config.id IS NOT NULL)::boolean AS has_active_team_config,
    (
        rn.status = 'online'
        AND rn.disabled_at IS NULL
        AND rn.archived_at IS NULL
    )::boolean AS runtime_online,
    EXISTS (
        SELECT 1
        FROM runtime_enrollments re
        WHERE re.tenant_id = tt.tenant_id
          AND re.runtime_node_id = rn.id
          AND re.status = 'approved'
          AND re.rejected_at IS NULL
          AND re.revoked_at IS NULL
    )::boolean AS enrollment_approved,
    EXISTS (
        SELECT 1
        FROM runtime_sessions rs
        JOIN runtime_enrollments re
          ON re.id = rs.enrollment_id
         AND re.tenant_id = rs.tenant_id
         AND re.runtime_node_id = rs.runtime_node_id
         AND re.status = 'approved'
         AND re.rejected_at IS NULL
         AND re.revoked_at IS NULL
        WHERE rs.tenant_id = tt.tenant_id
          AND rs.runtime_node_id = rn.id
          AND rs.expires_at > NOW()
          AND rs.revoked_at IS NULL
    )::boolean AS runtime_session_active,
    (provider_capability.id IS NOT NULL)::boolean AS provider_available,
    COALESCE((
        active_team_config.id IS NOT NULL
        AND (
            (
                jsonb_typeof(active_team_config.capability_policy -> 'allowed_provider_types') = 'array'
                AND (active_team_config.capability_policy -> 'allowed_provider_types') ? $1::varchar
            )
            OR (
                jsonb_typeof(active_team_config.runtime_scope_policy -> 'allowed_provider_types') = 'array'
                AND (active_team_config.runtime_scope_policy -> 'allowed_provider_types') ? $1::varchar
            )
            OR (
                jsonb_typeof(active_team_config.runtime_scope_policy -> 'provider_types') = 'array'
                AND (active_team_config.runtime_scope_policy -> 'provider_types') ? $1::varchar
            )
        )
    ), false)::boolean AS provider_policy_allowed,
    COALESCE((
        active_team_config.id IS NOT NULL
        AND (
            (
                active_team_config.runtime_scope_policy ? 'allowed_runtime_node_ids'
                AND jsonb_typeof(active_team_config.runtime_scope_policy -> 'allowed_runtime_node_ids') = 'array'
                AND (active_team_config.runtime_scope_policy -> 'allowed_runtime_node_ids') ? rn.id::text
            )
            OR (
                active_team_config.runtime_scope_policy ? 'allowed_node_ids'
                AND jsonb_typeof(active_team_config.runtime_scope_policy -> 'allowed_node_ids') = 'array'
                AND (active_team_config.runtime_scope_policy -> 'allowed_node_ids') ? rn.node_id
            )
            OR (
                jsonb_typeof(active_team_config.runtime_scope_policy -> 'allowed_provider_types') = 'array'
                AND (active_team_config.runtime_scope_policy -> 'allowed_provider_types') ? $1::varchar
            )
            OR (
                jsonb_typeof(active_team_config.runtime_scope_policy -> 'provider_types') = 'array'
                AND (active_team_config.runtime_scope_policy -> 'provider_types') ? $1::varchar
            )
        )
        AND CASE
            WHEN NOT (active_team_config.runtime_scope_policy ? 'allowed_runtime_node_ids') THEN true
            WHEN jsonb_typeof(active_team_config.runtime_scope_policy -> 'allowed_runtime_node_ids') = 'array' THEN
                (active_team_config.runtime_scope_policy -> 'allowed_runtime_node_ids') ? rn.id::text
            ELSE false
        END
        AND CASE
            WHEN NOT (active_team_config.runtime_scope_policy ? 'allowed_node_ids') THEN true
            WHEN jsonb_typeof(active_team_config.runtime_scope_policy -> 'allowed_node_ids') = 'array' THEN
                (active_team_config.runtime_scope_policy -> 'allowed_node_ids') ? rn.node_id
            ELSE false
        END
    ), false)::boolean AS runtime_policy_allowed
FROM tenant_teams tt
JOIN runtime_nodes rn
  ON rn.id = $2::uuid
 AND rn.tenant_id = tt.tenant_id
LEFT JOIN active_team_config ON TRUE
LEFT JOIN provider_capability ON TRUE
LEFT JOIN workspace_capability ON TRUE
WHERE tt.tenant_id = $3::uuid
  AND tt.id = $4::uuid
  AND tt.status = 'active'
  AND tt.disabled_at IS NULL
  AND tt.archived_at IS NULL
  AND tt.deleted_at IS NULL
`

type GetRuntimeProvisioningPreflightParams struct {
	ProviderType  string    `json:"provider_type"`
	RuntimeNodeID uuid.UUID `json:"runtime_node_id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	TeamID        uuid.UUID `json:"team_id"`
}

type GetRuntimeProvisioningPreflightRow struct {
	TenantID              uuid.UUID   `json:"tenant_id"`
	TeamID                uuid.UUID   `json:"team_id"`
	RuntimeNodeID         uuid.UUID   `json:"runtime_node_id"`
	NodeID                string      `json:"node_id"`
	AgentHomeDir          string      `json:"agent_home_dir"`
	GovernanceSnapshot    interface{} `json:"governance_snapshot"`
	HasActiveTeamConfig   bool        `json:"has_active_team_config"`
	RuntimeOnline         bool        `json:"runtime_online"`
	EnrollmentApproved    bool        `json:"enrollment_approved"`
	RuntimeSessionActive  bool        `json:"runtime_session_active"`
	ProviderAvailable     bool        `json:"provider_available"`
	ProviderPolicyAllowed bool        `json:"provider_policy_allowed"`
	RuntimePolicyAllowed  bool        `json:"runtime_policy_allowed"`
}

func (q *Queries) GetRuntimeProvisioningPreflight(ctx context.Context, arg GetRuntimeProvisioningPreflightParams) (GetRuntimeProvisioningPreflightRow, error) {
	row := q.db.QueryRow(ctx, GetRuntimeProvisioningPreflight,
		arg.ProviderType,
		arg.RuntimeNodeID,
		arg.TenantID,
		arg.TeamID,
	)
	var i GetRuntimeProvisioningPreflightRow
	err := row.Scan(
		&i.TenantID,
		&i.TeamID,
		&i.RuntimeNodeID,
		&i.NodeID,
		&i.AgentHomeDir,
		&i.GovernanceSnapshot,
		&i.HasActiveTeamConfig,
		&i.RuntimeOnline,
		&i.EnrollmentApproved,
		&i.RuntimeSessionActive,
		&i.ProviderAvailable,
		&i.ProviderPolicyAllowed,
		&i.RuntimePolicyAllowed,
	)
	return i, err
}

const ListDigitalEmployeeExecutionInstances = `-- name: ListDigitalEmployeeExecutionInstances :many
SELECT id, tenant_id, digital_employee_id, runtime_node_id, provider_type, agent_home_dir, workspace_policy, session_policy, runtime_selector, capacity_requirements, fallback_policy, status, ready_at, disabled_at, error_at, error_message, deleted_at, metadata, created_at, updated_at
FROM digital_employee_execution_instances
WHERE tenant_id = $1::uuid
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR runtime_node_id = $2::uuid)
  AND ($3::varchar IS NULL OR provider_type = $3::varchar)
  AND ($4::varchar IS NULL OR status = $4::varchar)
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListDigitalEmployeeExecutionInstancesParams struct {
	TenantID      uuid.UUID     `json:"tenant_id"`
	RuntimeNodeID uuid.NullUUID `json:"runtime_node_id"`
	ProviderType  pgtype.Text   `json:"provider_type"`
	Status        pgtype.Text   `json:"status"`
	Offset        int32         `json:"offset"`
	Limit         int32         `json:"limit"`
}

func (q *Queries) ListDigitalEmployeeExecutionInstances(ctx context.Context, arg ListDigitalEmployeeExecutionInstancesParams) ([]DigitalEmployeeExecutionInstance, error) {
	rows, err := q.db.Query(ctx, ListDigitalEmployeeExecutionInstances,
		arg.TenantID,
		arg.RuntimeNodeID,
		arg.ProviderType,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DigitalEmployeeExecutionInstance{}
	for rows.Next() {
		var i DigitalEmployeeExecutionInstance
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DigitalEmployeeID,
			&i.RuntimeNodeID,
			&i.ProviderType,
			&i.AgentHomeDir,
			&i.WorkspacePolicy,
			&i.SessionPolicy,
			&i.RuntimeSelector,
			&i.CapacityRequirements,
			&i.FallbackPolicy,
			&i.Status,
			&i.ReadyAt,
			&i.DisabledAt,
			&i.ErrorAt,
			&i.ErrorMessage,
			&i.DeletedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDigitalEmployeeOverviewFilterOptions = `-- name: ListDigitalEmployeeOverviewFilterOptions :many
WITH overview_args AS (
    SELECT $1::uuid AS tenant_id
),
latest_runs AS (
    SELECT DISTINCT ON (tr.tenant_id, tr.digital_employee_id)
        tr.tenant_id,
        tr.digital_employee_id,
        tr.status
    FROM task_runs tr
    JOIN overview_args args ON args.tenant_id = tr.tenant_id
    JOIN tasks t ON t.id = tr.task_id AND t.tenant_id = tr.tenant_id
    WHERE tr.digital_employee_id IS NOT NULL
      AND t.deleted_at IS NULL
    ORDER BY tr.tenant_id, tr.digital_employee_id, tr.updated_at DESC, tr.created_at DESC
),
employee_rows AS (
    SELECT
        de.team_id,
        COALESCE(tt.name, '')::text AS team_name,
        de.employee_type,
        de.status,
        de.risk_level,
        COALESCE(dei.provider_type, '')::text AS provider_type,
        dei.runtime_node_id,
        COALESCE(rn.name, rn.node_id, '')::text AS runtime_name,
        COALESCE(dei.status, 'missing')::text AS execution_status,
        COALESCE(lr.status, 'none')::text AS run_status
    FROM digital_employees de
    CROSS JOIN overview_args args
    LEFT JOIN tenant_teams tt
      ON tt.id = de.team_id
     AND tt.tenant_id = de.tenant_id
     AND tt.deleted_at IS NULL
    LEFT JOIN digital_employee_execution_instances dei
      ON dei.tenant_id = de.tenant_id
     AND dei.digital_employee_id = de.id
     AND dei.deleted_at IS NULL
    LEFT JOIN runtime_nodes rn
      ON rn.id = dei.runtime_node_id
     AND rn.tenant_id = dei.tenant_id
    LEFT JOIN latest_runs lr
      ON lr.tenant_id = de.tenant_id
     AND lr.digital_employee_id = de.id
    WHERE de.tenant_id = args.tenant_id
      AND de.deleted_at IS NULL
)
SELECT filter_type, value, label
FROM (
    SELECT DISTINCT
        'team'::text AS filter_type,
        COALESCE(team_id::text, '')::text AS value,
        team_name AS label
    FROM employee_rows
    WHERE team_id IS NOT NULL

    UNION ALL

    SELECT DISTINCT
        'employee_type'::text AS filter_type,
        employee_type::text AS value,
        employee_type::text AS label
    FROM employee_rows
    WHERE NULLIF(employee_type, '') IS NOT NULL

    UNION ALL

    SELECT DISTINCT
        'status'::text AS filter_type,
        status::text AS value,
        status::text AS label
    FROM employee_rows
    WHERE NULLIF(status, '') IS NOT NULL

    UNION ALL

    SELECT DISTINCT
        'provider'::text AS filter_type,
        provider_type AS value,
        provider_type AS label
    FROM employee_rows
    WHERE NULLIF(provider_type, '') IS NOT NULL

    UNION ALL

    SELECT DISTINCT
        'runtime_node'::text AS filter_type,
        COALESCE(runtime_node_id::text, '')::text AS value,
        runtime_name AS label
    FROM employee_rows
    WHERE runtime_node_id IS NOT NULL

    UNION ALL

    SELECT DISTINCT
        'risk_level'::text AS filter_type,
        risk_level::text AS value,
        risk_level::text AS label
    FROM employee_rows
    WHERE NULLIF(risk_level, '') IS NOT NULL

    UNION ALL

    SELECT DISTINCT
        'execution_status'::text AS filter_type,
        execution_status AS value,
        execution_status AS label
    FROM employee_rows
    WHERE NULLIF(execution_status, '') IS NOT NULL

    UNION ALL

    SELECT DISTINCT
        'run_status'::text AS filter_type,
        run_status AS value,
        run_status AS label
    FROM employee_rows
    WHERE NULLIF(run_status, '') IS NOT NULL
) options
ORDER BY filter_type, label, value
`

type ListDigitalEmployeeOverviewFilterOptionsRow struct {
	FilterType string `json:"filter_type"`
	Value      string `json:"value"`
	Label      string `json:"label"`
}

func (q *Queries) ListDigitalEmployeeOverviewFilterOptions(ctx context.Context, tenantID uuid.UUID) ([]ListDigitalEmployeeOverviewFilterOptionsRow, error) {
	rows, err := q.db.Query(ctx, ListDigitalEmployeeOverviewFilterOptions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDigitalEmployeeOverviewFilterOptionsRow{}
	for rows.Next() {
		var i ListDigitalEmployeeOverviewFilterOptionsRow
		if err := rows.Scan(&i.FilterType, &i.Value, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDigitalEmployeeOverviewItems = `-- name: ListDigitalEmployeeOverviewItems :many
WITH overview_args AS (
    SELECT
        $1::uuid AS tenant_id,
        NULLIF(BTRIM($2::text), '') AS q,
        $3::uuid AS team_id,
        NULLIF(BTRIM($4::text), '') AS status,
        NULLIF(BTRIM($5::text), '') AS employee_type,
        NULLIF(BTRIM($6::text), '') AS provider_type,
        $7::uuid AS runtime_node_id,
        NULLIF(BTRIM($8::text), '') AS risk_level,
        NULLIF(BTRIM($9::text), '') AS execution_status,
        NULLIF(BTRIM($10::text), '') AS run_status,
        $11::integer AS limit_value,
        $12::integer AS offset_value
),
provider_capabilities AS (
    SELECT DISTINCT ON (rc.tenant_id, rc.runtime_node_id, rc.provider_type)
        rc.tenant_id,
        rc.runtime_node_id,
        rc.provider_type,
        rc.status,
        rc.health_status,
        rc.available
    FROM runtime_capabilities rc
    JOIN overview_args args ON args.tenant_id = rc.tenant_id
    WHERE rc.capability_type = 'provider'
      AND rc.disabled_at IS NULL
      AND rc.archived_at IS NULL
    ORDER BY rc.tenant_id, rc.runtime_node_id, rc.provider_type, rc.last_seen_at DESC NULLS LAST, rc.updated_at DESC
),
latest_runs AS (
    SELECT DISTINCT ON (tr.tenant_id, tr.digital_employee_id)
        tr.tenant_id,
        tr.digital_employee_id,
        tr.id,
        tr.task_id,
        t.title,
        tr.status,
        tr.started_at,
        tr.finished_at,
        tr.updated_at,
        tr.result,
        tr.error_message,
        tr.created_at
    FROM task_runs tr
    JOIN overview_args args ON args.tenant_id = tr.tenant_id
    JOIN tasks t ON t.id = tr.task_id AND t.tenant_id = tr.tenant_id
    WHERE tr.digital_employee_id IS NOT NULL
      AND t.deleted_at IS NULL
    ORDER BY tr.tenant_id, tr.digital_employee_id, tr.updated_at DESC, tr.created_at DESC
),
budget_run_tokens AS (
    SELECT
        tr.tenant_id,
        tr.digital_employee_id,
        COALESCE(tr.result #>> '{usage,total_tokens}', tr.result ->> 'total_tokens', '') AS token_text
    FROM task_runs tr
    JOIN overview_args args ON args.tenant_id = tr.tenant_id
    WHERE tr.digital_employee_id IS NOT NULL
      AND tr.created_at >= NOW() - INTERVAL '30 days'
),
budget_runs AS (
    SELECT
        tenant_id,
        digital_employee_id,
        CASE
            WHEN COUNT(*) FILTER (WHERE token_text ~ '^[0-9]+$') = 0 THEN NULL
            ELSE LEAST(
                SUM(CASE WHEN token_text ~ '^[0-9]+$' THEN token_text::bigint ELSE 0 END),
                2147483647
            )::integer
        END AS budget_usage_tokens_30d,
        COUNT(*)::integer AS budget_run_count_30d
    FROM budget_run_tokens
    GROUP BY tenant_id, digital_employee_id
),
today_budget_usage AS (
    SELECT
        tr.tenant_id,
        tr.digital_employee_id,
        LEAST(
            COALESCE(
                SUM(
                    CASE
                        WHEN COALESCE(tr.result #>> '{usage,total_tokens}', tr.result ->> 'total_tokens', '') ~ '^[0-9]+$'
                        THEN COALESCE(tr.result #>> '{usage,total_tokens}', tr.result ->> 'total_tokens', '')::bigint
                        ELSE 0
                    END
                ),
                0
            ),
            2147483647
        )::integer AS today_budget_usage_tokens
    FROM task_runs tr
    JOIN overview_args args ON args.tenant_id = tr.tenant_id
    WHERE tr.digital_employee_id IS NOT NULL
      AND COALESCE(tr.finished_at, tr.updated_at, tr.created_at) >= (date_trunc('day', timezone('Asia/Shanghai', now())) AT TIME ZONE 'Asia/Shanghai')
      AND COALESCE(tr.finished_at, tr.updated_at, tr.created_at) < ((date_trunc('day', timezone('Asia/Shanghai', now())) + INTERVAL '1 day') AT TIME ZONE 'Asia/Shanghai')
    GROUP BY tr.tenant_id, tr.digital_employee_id
),
effective_configs AS (
    SELECT DISTINCT ON (ec.tenant_id, ec.digital_employee_id)
        ec.tenant_id,
        ec.digital_employee_id,
        ec.id AS effective_config_id,
        ec.status,
        ec.effective_config_snapshot -> 'budget_policy' AS budget_policy,
        NULLIF(ec.effective_config_snapshot #>> '{budget_policy,daily_token_limit}', '') AS daily_token_limit_text,
        ttcr.revision_number AS team_revision_number,
        decr.revision_number AS employee_revision_number,
        CASE
            WHEN jsonb_typeof(ec.effective_config_snapshot #> '{capability_selection,enabled_mcp_servers}') = 'array'
            THEN jsonb_array_length(ec.effective_config_snapshot #> '{capability_selection,enabled_mcp_servers}')
            ELSE 0
        END::integer AS mcp_servers_count,
        COALESCE(
            ec.effective_config_snapshot #>> '{constitution,ref}',
            ec.effective_config_snapshot #>> '{constitution,team,ref}',
            ec.effective_config_snapshot #>> '{constitution,team,document_ref}',
            ''
        )::text AS constitution_ref
    FROM digital_employee_effective_configs ec
    JOIN overview_args args ON args.tenant_id = ec.tenant_id
    LEFT JOIN tenant_team_config_revisions ttcr
      ON ttcr.id = ec.tenant_team_config_revision_id
     AND ttcr.tenant_id = ec.tenant_id
    LEFT JOIN digital_employee_config_revisions decr
      ON decr.id = ec.employee_config_revision_id
     AND decr.tenant_id = ec.tenant_id
     AND decr.digital_employee_id = ec.digital_employee_id
    WHERE ec.status = 'approved'
      AND ec.revoked_at IS NULL
    ORDER BY ec.tenant_id, ec.digital_employee_id, ec.created_at DESC, ec.updated_at DESC
),
governance_configs AS (
    SELECT DISTINCT ON (ec.tenant_id, ec.digital_employee_id)
        ec.tenant_id,
        ec.digital_employee_id,
        ec.status
    FROM digital_employee_effective_configs ec
    JOIN overview_args args ON args.tenant_id = ec.tenant_id
    WHERE ec.revoked_at IS NULL
    ORDER BY ec.tenant_id, ec.digital_employee_id, ec.created_at DESC, ec.updated_at DESC
),
skill_counts AS (
    SELECT
        sab.tenant_id,
        sab.digital_employee_id,
        COUNT(*)::integer AS skills_count
    FROM skill_agent_bindings sab
    JOIN overview_args args ON args.tenant_id = sab.tenant_id
    JOIN skills s
      ON s.id = sab.skill_id
     AND s.tenant_id = sab.tenant_id
     AND s.deleted_at IS NULL
    WHERE sab.status = 'enabled'
    GROUP BY sab.tenant_id, sab.digital_employee_id
),
overview_rows AS (
    SELECT
        de.id,
        de.tenant_id,
        de.team_id,
        COALESCE(tt.name, '')::text AS team_name,
        de.owner_user_id,
        COALESCE(au.display_name, au.username, '')::text AS owner_display_name,
        de.employee_type,
        de.name,
        de.role,
        de.description,
        de.status,
        de.risk_level,
        de.metadata,
        dei.id AS execution_instance_id,
        COALESCE(dei.status, 'missing')::text AS execution_status,
        dei.runtime_node_id,
        COALESCE(rn.node_id, '')::text AS node_id,
        COALESCE(rn.name, '')::text AS runtime_name,
        COALESCE(rn.status, '')::text AS runtime_status,
        rn.disabled_at AS runtime_disabled_at,
        rn.archived_at AS runtime_archived_at,
        COALESCE(dei.provider_type, '')::text AS provider_type,
        COALESCE(pc.available, false)::boolean AS provider_available,
        COALESCE(pc.status, 'unknown')::text AS provider_status,
        COALESCE(pc.health_status, 'unknown')::text AS health_status,
        (NULLIF(BTRIM(COALESCE(dei.agent_home_dir, '')), '') IS NOT NULL)::boolean AS agent_home_dir_available,
        lr.id AS latest_run_id,
        lr.task_id AS latest_run_task_id,
        COALESCE(lr.status, 'none')::text AS latest_run_status,
        COALESCE(lr.title, '')::text AS latest_run_title,
        lr.started_at AS latest_run_started_at,
        lr.finished_at AS latest_run_finished_at,
        lr.updated_at AS latest_run_updated_at,
        COALESCE((CASE
            WHEN lr.id IS NOT NULL AND lr.finished_at IS NOT NULL THEN
                GREATEST(EXTRACT(EPOCH FROM (lr.finished_at - lr.started_at))::integer, 0)
            ELSE NULL
        END)::text, '')::text AS latest_run_duration_sec,
        COALESCE(lr.result #>> '{usage,total_tokens}', lr.result ->> 'total_tokens', '')::text AS latest_run_token_usage,
        lr.error_message AS latest_run_error_message,
        ec.effective_config_id,
        COALESCE(gc.status, 'missing')::text AS governance_status,
        COALESCE(ec.daily_token_limit_text, '')::text AS daily_token_limit_text,
        ec.team_revision_number,
        ec.employee_revision_number,
        COALESCE(sc.skills_count, 0)::integer AS skills_count,
        COALESCE(ec.mcp_servers_count, 0)::integer AS mcp_servers_count,
        COALESCE(ec.constitution_ref, '')::text AS constitution_ref,
        COALESCE(tbu.today_budget_usage_tokens, 0)::integer AS today_budget_usage_tokens,
        br.budget_usage_tokens_30d,
        COALESCE(br.budget_run_count_30d, 0)::integer AS budget_run_count_30d,
        de.created_at,
        de.updated_at
    FROM digital_employees de
    CROSS JOIN overview_args args
    LEFT JOIN tenant_teams tt
      ON tt.id = de.team_id
     AND tt.tenant_id = de.tenant_id
     AND tt.deleted_at IS NULL
    LEFT JOIN auth_users au
      ON au.id = de.owner_user_id
     AND au.deleted_at IS NULL
    LEFT JOIN digital_employee_execution_instances dei
      ON dei.tenant_id = de.tenant_id
     AND dei.digital_employee_id = de.id
     AND dei.deleted_at IS NULL
    LEFT JOIN runtime_nodes rn
      ON rn.id = dei.runtime_node_id
     AND rn.tenant_id = dei.tenant_id
    LEFT JOIN provider_capabilities pc
      ON pc.tenant_id = dei.tenant_id
     AND pc.runtime_node_id = dei.runtime_node_id
     AND pc.provider_type = dei.provider_type
    LEFT JOIN latest_runs lr
      ON lr.tenant_id = de.tenant_id
     AND lr.digital_employee_id = de.id
    LEFT JOIN budget_runs br
      ON br.tenant_id = de.tenant_id
     AND br.digital_employee_id = de.id
    LEFT JOIN today_budget_usage tbu
      ON tbu.tenant_id = de.tenant_id
     AND tbu.digital_employee_id = de.id
    LEFT JOIN effective_configs ec
      ON ec.tenant_id = de.tenant_id
     AND ec.digital_employee_id = de.id
    LEFT JOIN governance_configs gc
      ON gc.tenant_id = de.tenant_id
     AND gc.digital_employee_id = de.id
    LEFT JOIN skill_counts sc
      ON sc.tenant_id = de.tenant_id
     AND sc.digital_employee_id = de.id
    WHERE de.tenant_id = args.tenant_id
      AND de.deleted_at IS NULL
),
filtered_rows AS (
    SELECT overview_rows.id, overview_rows.tenant_id, overview_rows.team_id, overview_rows.team_name, overview_rows.owner_user_id, overview_rows.owner_display_name, overview_rows.employee_type, overview_rows.name, overview_rows.role, overview_rows.description, overview_rows.status, overview_rows.risk_level, overview_rows.metadata, overview_rows.execution_instance_id, overview_rows.execution_status, overview_rows.runtime_node_id, overview_rows.node_id, overview_rows.runtime_name, overview_rows.runtime_status, overview_rows.runtime_disabled_at, overview_rows.runtime_archived_at, overview_rows.provider_type, overview_rows.provider_available, overview_rows.provider_status, overview_rows.health_status, overview_rows.agent_home_dir_available, overview_rows.latest_run_id, overview_rows.latest_run_task_id, overview_rows.latest_run_status, overview_rows.latest_run_title, overview_rows.latest_run_started_at, overview_rows.latest_run_finished_at, overview_rows.latest_run_updated_at, overview_rows.latest_run_duration_sec, overview_rows.latest_run_token_usage, overview_rows.latest_run_error_message, overview_rows.effective_config_id, overview_rows.governance_status, overview_rows.daily_token_limit_text, overview_rows.team_revision_number, overview_rows.employee_revision_number, overview_rows.skills_count, overview_rows.mcp_servers_count, overview_rows.constitution_ref, overview_rows.today_budget_usage_tokens, overview_rows.budget_usage_tokens_30d, overview_rows.budget_run_count_30d, overview_rows.created_at, overview_rows.updated_at
    FROM overview_rows
    CROSS JOIN overview_args args
    WHERE (
        args.q IS NULL
        OR overview_rows.name ILIKE '%' || args.q || '%'
        OR overview_rows.role ILIKE '%' || args.q || '%'
        OR overview_rows.description ILIKE '%' || args.q || '%'
    )
      AND (args.team_id IS NULL OR overview_rows.team_id = args.team_id)
      AND (args.status IS NULL OR overview_rows.status = args.status)
      AND (args.employee_type IS NULL OR overview_rows.employee_type = args.employee_type)
      AND (args.provider_type IS NULL OR overview_rows.provider_type = args.provider_type)
      AND (args.runtime_node_id IS NULL OR overview_rows.runtime_node_id = args.runtime_node_id)
      AND (args.risk_level IS NULL OR overview_rows.risk_level = args.risk_level)
      AND (args.execution_status IS NULL OR overview_rows.execution_status = args.execution_status)
      AND (args.run_status IS NULL OR overview_rows.latest_run_status = args.run_status)
),
paged_rows AS (
    SELECT id, tenant_id, team_id, team_name, owner_user_id, owner_display_name, employee_type, name, role, description, status, risk_level, metadata, execution_instance_id, execution_status, runtime_node_id, node_id, runtime_name, runtime_status, runtime_disabled_at, runtime_archived_at, provider_type, provider_available, provider_status, health_status, agent_home_dir_available, latest_run_id, latest_run_task_id, latest_run_status, latest_run_title, latest_run_started_at, latest_run_finished_at, latest_run_updated_at, latest_run_duration_sec, latest_run_token_usage, latest_run_error_message, effective_config_id, governance_status, daily_token_limit_text, team_revision_number, employee_revision_number, skills_count, mcp_servers_count, constitution_ref, today_budget_usage_tokens, budget_usage_tokens_30d, budget_run_count_30d, created_at, updated_at
    FROM filtered_rows
    ORDER BY created_at DESC, id
    LIMIT (SELECT limit_value FROM overview_args)
    OFFSET (SELECT offset_value FROM overview_args)
),
recent_events AS (
    SELECT
        ranked.tenant_id,
        ranked.digital_employee_id,
        jsonb_agg(
            jsonb_build_object(
                'label', ranked.event_label,
                'status', ranked.event_status,
                'occurred_at', ranked.occurred_at
            )
            ORDER BY ranked.occurred_at DESC NULLS LAST, ranked.sequence_number DESC
        ) AS recent_events_json
    FROM (
        SELECT
            pr.tenant_id,
            pr.id AS digital_employee_id,
            te.sequence_number,
            CASE
                WHEN te.event_type = 'run_dispatched' THEN '命令已下发'
                WHEN te.event_type ILIKE '%provider%' THEN 'Provider 输出中'
                WHEN te.event_type ILIKE '%complete%' THEN '等待结果回写'
                ELSE te.event_type
            END AS event_label,
            CASE
                WHEN te.event_type ILIKE '%fail%' THEN 'failed'
                WHEN te.event_type ILIKE '%complete%' THEN 'completed'
                ELSE 'running'
            END AS event_status,
            COALESCE(te.created_at, tr.updated_at, tr.created_at) AS occurred_at,
            ROW_NUMBER() OVER (
                PARTITION BY pr.tenant_id, pr.id
                ORDER BY COALESCE(te.created_at, tr.updated_at, tr.created_at) DESC, te.sequence_number DESC
            ) AS row_number
        FROM paged_rows pr
        JOIN task_runs tr
          ON tr.tenant_id = pr.tenant_id
         AND tr.digital_employee_id = pr.id
        JOIN tasks t
          ON t.id = tr.task_id
         AND t.tenant_id = tr.tenant_id
         AND t.deleted_at IS NULL
        JOIN task_events te
          ON te.tenant_id = tr.tenant_id
         AND te.run_id = tr.id
    ) ranked
    WHERE ranked.row_number <= 3
    GROUP BY ranked.tenant_id, ranked.digital_employee_id
)
SELECT
    pr.id,
    pr.tenant_id,
    pr.team_id,
    pr.team_name,
    pr.owner_user_id,
    pr.owner_display_name,
    pr.employee_type,
    pr.name,
    pr.role,
    pr.description,
    pr.status,
    pr.risk_level,
    pr.metadata,
    pr.execution_instance_id,
    pr.execution_status,
    pr.runtime_node_id,
    pr.node_id,
    pr.runtime_name,
    pr.runtime_status,
    pr.runtime_disabled_at,
    pr.runtime_archived_at,
    pr.provider_type,
    pr.provider_available,
    pr.provider_status,
    pr.health_status,
    pr.agent_home_dir_available,
    pr.latest_run_id,
    pr.latest_run_task_id,
    pr.latest_run_status,
    pr.latest_run_title,
    pr.latest_run_started_at,
    pr.latest_run_finished_at,
    pr.latest_run_updated_at,
    pr.latest_run_duration_sec,
    pr.latest_run_token_usage,
    pr.latest_run_error_message,
    pr.effective_config_id,
    pr.governance_status,
    pr.daily_token_limit_text,
    pr.team_revision_number,
    pr.employee_revision_number,
    pr.skills_count,
    pr.mcp_servers_count,
    pr.constitution_ref,
    pr.today_budget_usage_tokens,
    pr.budget_usage_tokens_30d,
    pr.budget_run_count_30d,
    COALESCE(re.recent_events_json, '[]'::jsonb) AS recent_events_json
FROM paged_rows pr
LEFT JOIN recent_events re
  ON re.tenant_id = pr.tenant_id
 AND re.digital_employee_id = pr.id
ORDER BY pr.created_at DESC, pr.id
`

type ListDigitalEmployeeOverviewItemsParams struct {
	TenantID        uuid.UUID     `json:"tenant_id"`
	Q               pgtype.Text   `json:"q"`
	TeamID          uuid.NullUUID `json:"team_id"`
	Status          pgtype.Text   `json:"status"`
	EmployeeType    pgtype.Text   `json:"employee_type"`
	ProviderType    pgtype.Text   `json:"provider_type"`
	RuntimeNodeID   uuid.NullUUID `json:"runtime_node_id"`
	RiskLevel       pgtype.Text   `json:"risk_level"`
	ExecutionStatus pgtype.Text   `json:"execution_status"`
	RunStatus       pgtype.Text   `json:"run_status"`
	Limit           int32         `json:"limit"`
	Offset          int32         `json:"offset"`
}

type ListDigitalEmployeeOverviewItemsRow struct {
	ID                     uuid.UUID          `json:"id"`
	TenantID               uuid.UUID          `json:"tenant_id"`
	TeamID                 uuid.NullUUID      `json:"team_id"`
	TeamName               string             `json:"team_name"`
	OwnerUserID            uuid.UUID          `json:"owner_user_id"`
	OwnerDisplayName       string             `json:"owner_display_name"`
	EmployeeType           string             `json:"employee_type"`
	Name                   string             `json:"name"`
	Role                   string             `json:"role"`
	Description            pgtype.Text        `json:"description"`
	Status                 string             `json:"status"`
	RiskLevel              string             `json:"risk_level"`
	Metadata               []byte             `json:"metadata"`
	ExecutionInstanceID    uuid.NullUUID      `json:"execution_instance_id"`
	ExecutionStatus        string             `json:"execution_status"`
	RuntimeNodeID          uuid.NullUUID      `json:"runtime_node_id"`
	NodeID                 string             `json:"node_id"`
	RuntimeName            string             `json:"runtime_name"`
	RuntimeStatus          string             `json:"runtime_status"`
	RuntimeDisabledAt      pgtype.Timestamptz `json:"runtime_disabled_at"`
	RuntimeArchivedAt      pgtype.Timestamptz `json:"runtime_archived_at"`
	ProviderType           string             `json:"provider_type"`
	ProviderAvailable      bool               `json:"provider_available"`
	ProviderStatus         string             `json:"provider_status"`
	HealthStatus           string             `json:"health_status"`
	AgentHomeDirAvailable  bool               `json:"agent_home_dir_available"`
	LatestRunID            uuid.NullUUID      `json:"latest_run_id"`
	LatestRunTaskID        uuid.NullUUID      `json:"latest_run_task_id"`
	LatestRunStatus        string             `json:"latest_run_status"`
	LatestRunTitle         string             `json:"latest_run_title"`
	LatestRunStartedAt     pgtype.Timestamptz `json:"latest_run_started_at"`
	LatestRunFinishedAt    pgtype.Timestamptz `json:"latest_run_finished_at"`
	LatestRunUpdatedAt     pgtype.Timestamptz `json:"latest_run_updated_at"`
	LatestRunDurationSec   string             `json:"latest_run_duration_sec"`
	LatestRunTokenUsage    string             `json:"latest_run_token_usage"`
	LatestRunErrorMessage  pgtype.Text        `json:"latest_run_error_message"`
	EffectiveConfigID      uuid.NullUUID      `json:"effective_config_id"`
	GovernanceStatus       string             `json:"governance_status"`
	DailyTokenLimitText    string             `json:"daily_token_limit_text"`
	TeamRevisionNumber     pgtype.Int4        `json:"team_revision_number"`
	EmployeeRevisionNumber pgtype.Int4        `json:"employee_revision_number"`
	SkillsCount            int32              `json:"skills_count"`
	McpServersCount        int32              `json:"mcp_servers_count"`
	ConstitutionRef        string             `json:"constitution_ref"`
	TodayBudgetUsageTokens int32              `json:"today_budget_usage_tokens"`
	BudgetUsageTokens30d   pgtype.Int4        `json:"budget_usage_tokens_30d"`
	BudgetRunCount30d      int32              `json:"budget_run_count_30d"`
	RecentEventsJson       []byte             `json:"recent_events_json"`
}

func (q *Queries) ListDigitalEmployeeOverviewItems(ctx context.Context, arg ListDigitalEmployeeOverviewItemsParams) ([]ListDigitalEmployeeOverviewItemsRow, error) {
	rows, err := q.db.Query(ctx, ListDigitalEmployeeOverviewItems,
		arg.TenantID,
		arg.Q,
		arg.TeamID,
		arg.Status,
		arg.EmployeeType,
		arg.ProviderType,
		arg.RuntimeNodeID,
		arg.RiskLevel,
		arg.ExecutionStatus,
		arg.RunStatus,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDigitalEmployeeOverviewItemsRow{}
	for rows.Next() {
		var i ListDigitalEmployeeOverviewItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TeamID,
			&i.TeamName,
			&i.OwnerUserID,
			&i.OwnerDisplayName,
			&i.EmployeeType,
			&i.Name,
			&i.Role,
			&i.Description,
			&i.Status,
			&i.RiskLevel,
			&i.Metadata,
			&i.ExecutionInstanceID,
			&i.ExecutionStatus,
			&i.RuntimeNodeID,
			&i.NodeID,
			&i.RuntimeName,
			&i.RuntimeStatus,
			&i.RuntimeDisabledAt,
			&i.RuntimeArchivedAt,
			&i.ProviderType,
			&i.ProviderAvailable,
			&i.ProviderStatus,
			&i.HealthStatus,
			&i.AgentHomeDirAvailable,
			&i.LatestRunID,
			&i.LatestRunTaskID,
			&i.LatestRunStatus,
			&i.LatestRunTitle,
			&i.LatestRunStartedAt,
			&i.LatestRunFinishedAt,
			&i.LatestRunUpdatedAt,
			&i.LatestRunDurationSec,
			&i.LatestRunTokenUsage,
			&i.LatestRunErrorMessage,
			&i.EffectiveConfigID,
			&i.GovernanceStatus,
			&i.DailyTokenLimitText,
			&i.TeamRevisionNumber,
			&i.EmployeeRevisionNumber,
			&i.SkillsCount,
			&i.McpServersCount,
			&i.ConstitutionRef,
			&i.TodayBudgetUsageTokens,
			&i.BudgetUsageTokens30d,
			&i.BudgetRunCount30d,
			&i.RecentEventsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDigitalEmployees = `-- name: ListDigitalEmployees :many
SELECT id, tenant_id, team_id, name, role, description, status, permission_policy, context_policy, approval_policy, risk_level, metadata, disabled_at, archived_at, deleted_at, created_at, updated_at, owner_user_id, employee_type
FROM digital_employees
WHERE tenant_id = $1::uuid
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR team_id = $2::uuid)
  AND ($3::varchar IS NULL OR status = $3::varchar)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListDigitalEmployeesParams struct {
	TenantID uuid.UUID     `json:"tenant_id"`
	TeamID   uuid.NullUUID `json:"team_id"`
	Status   pgtype.Text   `json:"status"`
	Offset   int32         `json:"offset"`
	Limit    int32         `json:"limit"`
}

func (q *Queries) ListDigitalEmployees(ctx context.Context, arg ListDigitalEmployeesParams) ([]DigitalEmployee, error) {
	rows, err := q.db.Query(ctx, ListDigitalEmployees,
		arg.TenantID,
		arg.TeamID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DigitalEmployee{}
	for rows.Next() {
		var i DigitalEmployee
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TeamID,
			&i.Name,
			&i.Role,
			&i.Description,
			&i.Status,
			&i.PermissionPolicy,
			&i.ContextPolicy,
			&i.ApprovalPolicy,
			&i.RiskLevel,
			&i.Metadata,
			&i.DisabledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUserID,
			&i.EmployeeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRuntimeProviderOptionsForDigitalEmployeeCreate = `-- name: ListRuntimeProviderOptionsForDigitalEmployeeCreate :many
WITH active_team_config AS (
    SELECT id, tenant_id, team_id, revision_number, constitution, capability_policy, context_policy, approval_policy, artifact_contract, internal_collaboration_policy, runtime_scope_policy, status, approved_by, approved_at, archived_at, created_at, updated_at, human_owner_user_ids
    FROM tenant_team_config_revisions
    WHERE tenant_id = $1::uuid
      AND team_id = $2::uuid
      AND status = 'active'
      AND archived_at IS NULL
    ORDER BY revision_number DESC
    LIMIT 1
),
runtime_sessions_active AS (
    SELECT DISTINCT re.runtime_node_id
    FROM runtime_sessions rs
    JOIN runtime_enrollments re
      ON re.id = rs.enrollment_id
     AND re.tenant_id = rs.tenant_id
     AND re.runtime_node_id = rs.runtime_node_id
     AND re.status = 'approved'
     AND re.rejected_at IS NULL
     AND re.revoked_at IS NULL
    WHERE rs.tenant_id = $1::uuid
      AND rs.expires_at > NOW()
      AND rs.revoked_at IS NULL
),
provider_capabilities AS (
    SELECT DISTINCT ON (tenant_id, runtime_node_id, provider_type)
        id, tenant_id, runtime_node_id, capability_type, capability_key, provider_type, provider_version, binary_path, available, workspace_base_dir, capacity, labels, status, details, health_status, metadata, last_seen_at, disabled_at, archived_at, created_at, updated_at
    FROM runtime_capabilities
    WHERE tenant_id = $1::uuid
      AND capability_type = 'provider'
      AND disabled_at IS NULL
      AND archived_at IS NULL
    ORDER BY tenant_id, runtime_node_id, provider_type, last_seen_at DESC NULLS LAST, updated_at DESC
)
SELECT
    rn.id AS runtime_node_id,
    rn.node_id,
    rn.name AS runtime_name,
    pc.provider_type,
    rn.status AS runtime_status,
    pc.status AS provider_status,
    pc.health_status,
    rn.current_load,
    rn.max_slots,
    COALESCE(
        pc.details ->> 'agent_home_dir',
        pc.metadata ->> 'agent_home_dir',
        pc.workspace_base_dir,
        rn.metadata ->> 'agent_home_dir',
        ''
    )::text AS agent_home_dir,
    (
        active_team_config.id IS NOT NULL
        AND rn.status = 'online'
        AND rn.disabled_at IS NULL
        AND rn.archived_at IS NULL
        AND pc.available = true
        AND pc.status = 'healthy'
        AND pc.health_status = 'healthy'
        AND runtime_sessions_active.runtime_node_id IS NOT NULL
        AND COALESCE((
            (
                jsonb_typeof(active_team_config.capability_policy -> 'allowed_provider_types') = 'array'
                AND (active_team_config.capability_policy -> 'allowed_provider_types') ? pc.provider_type
            )
            OR (
                jsonb_typeof(active_team_config.runtime_scope_policy -> 'allowed_provider_types') = 'array'
                AND (active_team_config.runtime_scope_policy -> 'allowed_provider_types') ? pc.provider_type
            )
            OR (
                jsonb_typeof(active_team_config.runtime_scope_policy -> 'provider_types') = 'array'
                AND (active_team_config.runtime_scope_policy -> 'provider_types') ? pc.provider_type
            )
        ), false)
        AND CASE
            WHEN NOT (active_team_config.runtime_scope_policy ? 'allowed_runtime_node_ids') THEN true
            WHEN jsonb_typeof(active_team_config.runtime_scope_policy -> 'allowed_runtime_node_ids') = 'array' THEN
                (active_team_config.runtime_scope_policy -> 'allowed_runtime_node_ids') ? rn.id::text
            ELSE false
        END
        AND CASE
            WHEN NOT (active_team_config.runtime_scope_policy ? 'allowed_node_ids') THEN true
            WHEN jsonb_typeof(active_team_config.runtime_scope_policy -> 'allowed_node_ids') = 'array' THEN
                (active_team_config.runtime_scope_policy -> 'allowed_node_ids') ? rn.node_id
            ELSE false
        END
    )::boolean AS available,
    CASE
        WHEN active_team_config.id IS NULL THEN 'active_team_config_required'
        WHEN rn.status <> 'online' OR rn.disabled_at IS NOT NULL OR rn.archived_at IS NOT NULL THEN 'runtime_not_online'
        WHEN runtime_sessions_active.runtime_node_id IS NULL THEN 'runtime_session_inactive'
        WHEN pc.available = false OR pc.status <> 'healthy' OR pc.health_status <> 'healthy' THEN 'provider_unhealthy'
        WHEN COALESCE(pc.provider_type, '') = '' THEN 'provider_type_missing'
        WHEN NOT COALESCE((
            (
                jsonb_typeof(active_team_config.capability_policy -> 'allowed_provider_types') = 'array'
                AND (active_team_config.capability_policy -> 'allowed_provider_types') ? pc.provider_type
            )
            OR (
                jsonb_typeof(active_team_config.runtime_scope_policy -> 'allowed_provider_types') = 'array'
                AND (active_team_config.runtime_scope_policy -> 'allowed_provider_types') ? pc.provider_type
            )
            OR (
                jsonb_typeof(active_team_config.runtime_scope_policy -> 'provider_types') = 'array'
                AND (active_team_config.runtime_scope_policy -> 'provider_types') ? pc.provider_type
            )
        ), false) THEN 'provider_outside_team_policy'
        WHEN active_team_config.runtime_scope_policy ? 'allowed_runtime_node_ids'
            AND (
                jsonb_typeof(active_team_config.runtime_scope_policy -> 'allowed_runtime_node_ids') <> 'array'
                OR NOT ((active_team_config.runtime_scope_policy -> 'allowed_runtime_node_ids') ? rn.id::text)
            ) THEN 'runtime_node_outside_team_policy'
        WHEN active_team_config.runtime_scope_policy ? 'allowed_node_ids'
            AND (
                jsonb_typeof(active_team_config.runtime_scope_policy -> 'allowed_node_ids') <> 'array'
                OR NOT ((active_team_config.runtime_scope_policy -> 'allowed_node_ids') ? rn.node_id)
            ) THEN 'runtime_node_slug_outside_team_policy'
        ELSE ''
    END::varchar AS disabled_reason
FROM runtime_nodes rn
LEFT JOIN provider_capabilities pc
  ON pc.runtime_node_id = rn.id
 AND pc.tenant_id = rn.tenant_id
LEFT JOIN active_team_config ON TRUE
LEFT JOIN runtime_sessions_active ON runtime_sessions_active.runtime_node_id = rn.id
WHERE rn.tenant_id = $1::uuid
  AND pc.provider_type IS NOT NULL
ORDER BY available DESC, rn.name ASC, pc.provider_type ASC
`

type ListRuntimeProviderOptionsForDigitalEmployeeCreateParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	TeamID   uuid.UUID `json:"team_id"`
}

type ListRuntimeProviderOptionsForDigitalEmployeeCreateRow struct {
	RuntimeNodeID  uuid.UUID   `json:"runtime_node_id"`
	NodeID         string      `json:"node_id"`
	RuntimeName    string      `json:"runtime_name"`
	ProviderType   pgtype.Text `json:"provider_type"`
	RuntimeStatus  string      `json:"runtime_status"`
	ProviderStatus pgtype.Text `json:"provider_status"`
	HealthStatus   pgtype.Text `json:"health_status"`
	CurrentLoad    int32       `json:"current_load"`
	MaxSlots       int32       `json:"max_slots"`
	AgentHomeDir   string      `json:"agent_home_dir"`
	Available      bool        `json:"available"`
	DisabledReason string      `json:"disabled_reason"`
}

func (q *Queries) ListRuntimeProviderOptionsForDigitalEmployeeCreate(ctx context.Context, arg ListRuntimeProviderOptionsForDigitalEmployeeCreateParams) ([]ListRuntimeProviderOptionsForDigitalEmployeeCreateRow, error) {
	rows, err := q.db.Query(ctx, ListRuntimeProviderOptionsForDigitalEmployeeCreate, arg.TenantID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimeProviderOptionsForDigitalEmployeeCreateRow{}
	for rows.Next() {
		var i ListRuntimeProviderOptionsForDigitalEmployeeCreateRow
		if err := rows.Scan(
			&i.RuntimeNodeID,
			&i.NodeID,
			&i.RuntimeName,
			&i.ProviderType,
			&i.RuntimeStatus,
			&i.ProviderStatus,
			&i.HealthStatus,
			&i.CurrentLoad,
			&i.MaxSlots,
			&i.AgentHomeDir,
			&i.Available,
			&i.DisabledReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateDigitalEmployeeExecutionInstanceStatus = `-- name: UpdateDigitalEmployeeExecutionInstanceStatus :one
UPDATE digital_employee_execution_instances
SET status = $1::varchar,
    ready_at = CASE
        WHEN $1::varchar = 'ready' THEN COALESCE(ready_at, NOW())
        ELSE ready_at
    END,
    disabled_at = CASE
        WHEN $1::varchar = 'disabled' THEN COALESCE(disabled_at, NOW())
        WHEN $1::varchar IN ('provisioning', 'ready', 'active') THEN NULL
        ELSE disabled_at
    END,
    error_at = CASE
        WHEN $1::varchar = 'error' THEN COALESCE(error_at, NOW())
        WHEN $1::varchar IN ('provisioning', 'ready', 'active') THEN NULL
        ELSE error_at
    END,
    error_message = CASE
        WHEN $1::varchar = 'error' THEN COALESCE($2::text, error_message)
        WHEN $1::varchar IN ('provisioning', 'ready', 'active') THEN NULL
        ELSE error_message
    END,
    updated_at = NOW()
WHERE id = $3::uuid
  AND tenant_id = $4::uuid
  AND deleted_at IS NULL
RETURNING id, tenant_id, digital_employee_id, runtime_node_id, provider_type, agent_home_dir, workspace_policy, session_policy, runtime_selector, capacity_requirements, fallback_policy, status, ready_at, disabled_at, error_at, error_message, deleted_at, metadata, created_at, updated_at
`

type UpdateDigitalEmployeeExecutionInstanceStatusParams struct {
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
}

func (q *Queries) UpdateDigitalEmployeeExecutionInstanceStatus(ctx context.Context, arg UpdateDigitalEmployeeExecutionInstanceStatusParams) (DigitalEmployeeExecutionInstance, error) {
	row := q.db.QueryRow(ctx, UpdateDigitalEmployeeExecutionInstanceStatus,
		arg.Status,
		arg.ErrorMessage,
		arg.ID,
		arg.TenantID,
	)
	var i DigitalEmployeeExecutionInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DigitalEmployeeID,
		&i.RuntimeNodeID,
		&i.ProviderType,
		&i.AgentHomeDir,
		&i.WorkspacePolicy,
		&i.SessionPolicy,
		&i.RuntimeSelector,
		&i.CapacityRequirements,
		&i.FallbackPolicy,
		&i.Status,
		&i.ReadyAt,
		&i.DisabledAt,
		&i.ErrorAt,
		&i.ErrorMessage,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateDigitalEmployeeStatus = `-- name: UpdateDigitalEmployeeStatus :one
UPDATE digital_employees
SET status = $1::varchar,
    disabled_at = CASE
        WHEN $1::varchar = 'disabled' THEN COALESCE(disabled_at, NOW())
        WHEN $1::varchar IN ('ready', 'active') THEN NULL
        ELSE disabled_at
    END,
    updated_at = NOW()
WHERE id = $2::uuid
  AND tenant_id = $3::uuid
  AND deleted_at IS NULL
RETURNING id, tenant_id, team_id, name, role, description, status, permission_policy, context_policy, approval_policy, risk_level, metadata, disabled_at, archived_at, deleted_at, created_at, updated_at, owner_user_id, employee_type
`

type UpdateDigitalEmployeeStatusParams struct {
	Status   string    `json:"status"`
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateDigitalEmployeeStatus(ctx context.Context, arg UpdateDigitalEmployeeStatusParams) (DigitalEmployee, error) {
	row := q.db.QueryRow(ctx, UpdateDigitalEmployeeStatus, arg.Status, arg.ID, arg.TenantID)
	var i DigitalEmployee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.Name,
		&i.Role,
		&i.Description,
		&i.Status,
		&i.PermissionPolicy,
		&i.ContextPolicy,
		&i.ApprovalPolicy,
		&i.RiskLevel,
		&i.Metadata,
		&i.DisabledAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
		&i.EmployeeType,
	)
	return i, err
}

const UpsertDigitalEmployeeExecutionInstance = `-- name: UpsertDigitalEmployeeExecutionInstance :one
INSERT INTO digital_employee_execution_instances (
    tenant_id,
    digital_employee_id,
    runtime_node_id,
    provider_type,
    agent_home_dir,
    workspace_policy,
    session_policy,
    runtime_selector,
    capacity_requirements,
    fallback_policy,
    status,
    metadata
) SELECT
    de.tenant_id,
    de.id,
    rn.id,
    $1::varchar,
    $2::text,
    COALESCE($3::jsonb, '{}'::jsonb),
    COALESCE($4::jsonb, '{}'::jsonb),
    COALESCE($5::jsonb, '{}'::jsonb),
    COALESCE($6::jsonb, '{}'::jsonb),
    COALESCE($7::jsonb, '{}'::jsonb),
    $8::varchar,
    COALESCE($9::jsonb, '{}'::jsonb)
FROM digital_employees de
JOIN runtime_nodes rn
  ON rn.id = $10::uuid
 AND rn.tenant_id = de.tenant_id
 AND rn.status = 'online'
 AND rn.disabled_at IS NULL
 AND rn.archived_at IS NULL
WHERE de.id = $11::uuid
  AND de.tenant_id = $12::uuid
  AND de.status NOT IN ('disabled', 'error')
  AND de.deleted_at IS NULL
  AND de.archived_at IS NULL
  AND EXISTS (
      SELECT 1
      FROM runtime_enrollments re
      WHERE re.tenant_id = de.tenant_id
        AND re.runtime_node_id = rn.id
        AND re.status = 'approved'
  )
  AND EXISTS (
      SELECT 1
      FROM runtime_capabilities rc
      WHERE rc.tenant_id = de.tenant_id
        AND rc.runtime_node_id = rn.id
        AND rc.capability_type = 'provider'
        AND rc.provider_type = $1::varchar
        AND rc.available = true
        AND rc.status = 'healthy'
        AND rc.health_status = 'healthy'
        AND rc.disabled_at IS NULL
        AND rc.archived_at IS NULL
  )
ON CONFLICT (tenant_id, digital_employee_id) WHERE deleted_at IS NULL DO UPDATE SET
    runtime_node_id = EXCLUDED.runtime_node_id,
    provider_type = EXCLUDED.provider_type,
    agent_home_dir = EXCLUDED.agent_home_dir,
    workspace_policy = EXCLUDED.workspace_policy,
    session_policy = EXCLUDED.session_policy,
    runtime_selector = EXCLUDED.runtime_selector,
    capacity_requirements = EXCLUDED.capacity_requirements,
    fallback_policy = EXCLUDED.fallback_policy,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    updated_at = NOW()
RETURNING id, tenant_id, digital_employee_id, runtime_node_id, provider_type, agent_home_dir, workspace_policy, session_policy, runtime_selector, capacity_requirements, fallback_policy, status, ready_at, disabled_at, error_at, error_message, deleted_at, metadata, created_at, updated_at
`

type UpsertDigitalEmployeeExecutionInstanceParams struct {
	ProviderType         string    `json:"provider_type"`
	AgentHomeDir         string    `json:"agent_home_dir"`
	WorkspacePolicy      []byte    `json:"workspace_policy"`
	SessionPolicy        []byte    `json:"session_policy"`
	RuntimeSelector      []byte    `json:"runtime_selector"`
	CapacityRequirements []byte    `json:"capacity_requirements"`
	FallbackPolicy       []byte    `json:"fallback_policy"`
	Status               string    `json:"status"`
	Metadata             []byte    `json:"metadata"`
	RuntimeNodeID        uuid.UUID `json:"runtime_node_id"`
	DigitalEmployeeID    uuid.UUID `json:"digital_employee_id"`
	TenantID             uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpsertDigitalEmployeeExecutionInstance(ctx context.Context, arg UpsertDigitalEmployeeExecutionInstanceParams) (DigitalEmployeeExecutionInstance, error) {
	row := q.db.QueryRow(ctx, UpsertDigitalEmployeeExecutionInstance,
		arg.ProviderType,
		arg.AgentHomeDir,
		arg.WorkspacePolicy,
		arg.SessionPolicy,
		arg.RuntimeSelector,
		arg.CapacityRequirements,
		arg.FallbackPolicy,
		arg.Status,
		arg.Metadata,
		arg.RuntimeNodeID,
		arg.DigitalEmployeeID,
		arg.TenantID,
	)
	var i DigitalEmployeeExecutionInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DigitalEmployeeID,
		&i.RuntimeNodeID,
		&i.ProviderType,
		&i.AgentHomeDir,
		&i.WorkspacePolicy,
		&i.SessionPolicy,
		&i.RuntimeSelector,
		&i.CapacityRequirements,
		&i.FallbackPolicy,
		&i.Status,
		&i.ReadyAt,
		&i.DisabledAt,
		&i.ErrorAt,
		&i.ErrorMessage,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
