// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// 全局审批处理记录表，保存人类处理动作和意见
type ApprovalDecision struct {
	// 审批处理记录ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 关联审批请求ID，由应用层校验租户和状态
	ApprovalRequestID uuid.UUID `json:"approval_request_id"`
	// 处理审批的人类用户ID
	DecidedByUserID uuid.UUID `json:"decided_by_user_id"`
	// 处理结论：approved、rejected、needs_more_evidence
	Decision string `json:"decision"`
	// 处理意见
	Comment pgtype.Text `json:"comment"`
	// 处理时提交的结构化补充信息
	Payload []byte `json:"payload"`
	// 处理记录创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 全局审批请求事实表，保存人类决策请求的事实源
type ApprovalRequest struct {
	// 审批请求ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 审批关联资源类型，由应用层校验
	ResourceType string `json:"resource_type"`
	// 审批关联资源ID
	ResourceID uuid.UUID `json:"resource_id"`
	// 发起者类型，例如 project_coordinator、human_user 或 system
	RequesterType string `json:"requester_type"`
	// 发起者ID，可为空表示系统发起
	RequesterID uuid.NullUUID `json:"requester_id"`
	// 目标处理人用户ID
	TargetUserID uuid.UUID `json:"target_user_id"`
	// 决策类型，由应用层注册和校验
	DecisionType string `json:"decision_type"`
	// 审批标题快照
	Title string `json:"title"`
	// 审批摘要快照
	Summary pgtype.Text `json:"summary"`
	// 风险等级快照
	RiskLevel pgtype.Text `json:"risk_level"`
	// 审批状态：pending、approved、rejected、needs_more_evidence、cancelled
	Status string `json:"status"`
	// 可选决策项 JSON 数组
	Options []byte `json:"options"`
	// 审批上下文快照
	ContextPayload []byte `json:"context_payload"`
	// 审批创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 审批更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 审批处理完成时间
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

// 工件保留锁表，记录归档、审计和人工决策产生的工件保留要求
type ArtifactRetentionHold struct {
	// 工件保留锁ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 被保留的工件ID
	ArtifactID uuid.UUID `json:"artifact_id"`
	// 保留锁类型，由应用层注册和校验
	HoldType string `json:"hold_type"`
	// 触发保留锁的资源类型
	ResourceType string `json:"resource_type"`
	// 触发保留锁的资源ID
	ResourceID uuid.UUID `json:"resource_id"`
	// 保留原因
	Reason pgtype.Text `json:"reason"`
	// 保留锁状态，例如 active、released
	Status string `json:"status"`
	// 创建该保留锁时产生的项目事件ID
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
	// 保留锁创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 保留锁更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 保留锁释放时间
	ReleasedAt pgtype.Timestamptz `json:"released_at"`
}

// 审计事件表
type AuditEvent struct {
	// 审计事件主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 审计事件类型
	EventType string `json:"event_type"`
	// 操作者类型
	ActorType string `json:"actor_type"`
	// 操作者 ID
	ActorID string `json:"actor_id"`
	// 资源类型
	ResourceType pgtype.Text `json:"resource_type"`
	// 资源 ID
	ResourceID pgtype.Text `json:"resource_id"`
	// 审计动作
	Action string `json:"action"`
	// 审计扩展信息
	Details []byte `json:"details"`
	// 操作者 IP 地址
	IpAddress *netip.Addr `json:"ip_address"`
	// 审计事件创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Web 登录图形验证码挑战表
type AuthCaptchaChallenge struct {
	// 验证码挑战主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 验证码答案哈希，不保存明文
	AnswerHash string `json:"answer_hash"`
	// 验证码过期时间
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// 验证码消费时间；非空表示已使用
	UsedAt pgtype.Timestamptz `json:"used_at"`
	// 创建验证码的客户端 IP
	ClientIp pgtype.Text `json:"client_ip"`
	// 创建验证码的 User-Agent
	UserAgent pgtype.Text `json:"user_agent"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Runtime Agent 认证令牌表
type AuthRuntimeToken struct {
	// Runtime 令牌主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// Runtime 外部业务节点 ID
	NodeID string `json:"node_id"`
	// Runtime 令牌哈希
	TokenHash string `json:"token_hash"`
	// Runtime 令牌过期时间
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// Runtime 令牌撤销时间
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	// Runtime 令牌创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Web 控制台用户会话表
type AuthSession struct {
	// 会话主键 UUID
	ID uuid.UUID `json:"id"`
	// 会话所属用户 ID
	UserID uuid.UUID `json:"user_id"`
	// 会话令牌哈希
	TokenHash string `json:"token_hash"`
	// 会话过期时间
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// 会话最后访问时间
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	// 客户端 IP
	ClientIp pgtype.Text `json:"client_ip"`
	// 客户端 User-Agent
	UserAgent pgtype.Text `json:"user_agent"`
	// 会话撤销时间
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	// 会话创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 会话最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Web 控制台平台用户表
type AuthUser struct {
	// 用户主键 UUID
	ID uuid.UUID `json:"id"`
	// 登录账号，平台内唯一
	Username string `json:"username"`
	// 用户展示名称，当前 MVP 可为空
	DisplayName pgtype.Text `json:"display_name"`
	// 用户邮箱，当前 MVP 可为空
	Email pgtype.Text `json:"email"`
	// 用户密码哈希，禁止存储明文密码
	PasswordHash string `json:"password_hash"`
	// 用户状态：active 表示启用，disabled 表示禁用
	Status string `json:"status"`
	// 用户最后登录时间
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	// 用户禁用时间
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	// 用户软删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// 用户创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 用户最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 用户头像来源，MVP 使用 DiceBear 生成稳定卡通头像
	AvatarProvider string `json:"avatar_provider"`
	// 用户头像样式标识，MVP 默认为 DiceBear adventurer
	AvatarStyle string `json:"avatar_style"`
	// 用户头像生成种子；为空时由服务端使用 username 生成稳定种子
	AvatarSeed pgtype.Text `json:"avatar_seed"`
	// 用户头像生成选项 JSON，保留颜色、配件等后续扩展配置
	AvatarOptions []byte `json:"avatar_options"`
	// 人类用户选择的内置头像资产 ID；创建用户流程以该字段作为头像事实来源
	AvatarAssetID pgtype.Text `json:"avatar_asset_id"`
}

// 数字员工业务身份表
type DigitalEmployee struct {
	// 数字员工主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属团队 ID，可为空表示租户级数字员工
	TeamID uuid.NullUUID `json:"team_id"`
	// 数字员工名称
	Name string `json:"name"`
	// 数字员工职责或角色标识
	Role string `json:"role"`
	// 数字员工职责描述
	Description pgtype.Text `json:"description"`
	// 数字员工状态：draft、ready、active、disabled 或 error
	Status string `json:"status"`
	// 数字员工权限策略快照
	PermissionPolicy []byte `json:"permission_policy"`
	// 数字员工上下文注入策略快照
	ContextPolicy []byte `json:"context_policy"`
	// 数字员工人类审批策略快照
	ApprovalPolicy []byte `json:"approval_policy"`
	// 数字员工默认风险等级
	RiskLevel string `json:"risk_level"`
	// 数字员工扩展元数据
	Metadata []byte `json:"metadata"`
	// 数字员工禁用时间
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	// 数字员工归档时间
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	// 数字员工软删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// 数字员工创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 数字员工最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 数字员工归属人类用户ID，由控制平面从登录上下文写入
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	// 数字员工专业类型，由服务端注册表校验，不使用数据库枚举
	EmployeeType string `json:"employee_type"`
	// 数字员工主 Provider 类型，由服务端 Provider 注册表校验，不使用数据库枚举。
	ProviderType string `json:"provider_type"`
}

// 数字员工个人配置版本表，保存人格记忆、能力绑定和预算策略
type DigitalEmployeeConfigRevision struct {
	// 数字员工个人配置版本ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 数字员工ID
	DigitalEmployeeID uuid.UUID `json:"digital_employee_id"`
	// 个人配置版本号，同一数字员工内递增
	RevisionNumber int32 `json:"revision_number"`
	// 配置状态：draft、pending_approval、active、archived
	Status string `json:"status"`
	// 批准该个人配置版本的用户ID
	ApprovedBy uuid.NullUUID `json:"approved_by"`
	// 个人配置版本批准时间
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
	// 个人配置版本归档时间
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 数字员工预算策略，包含每日 token 上限；空对象表示无预算上限
	BudgetPolicy []byte `json:"budget_policy"`
	// 数字员工人格记忆 Markdown，描述人格画像、专业边界、工作方式和表达偏好
	PersonaMemoryMarkdown string `json:"persona_memory_markdown"`
	// 数字员工能力绑定，保存 Skill、MCP、外部能力和环境变量引用
	CapabilityBindings []byte `json:"capability_bindings"`
}

type DigitalEmployeeEnvironmentVariable struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	// 环境变量所属数字员工团队 ID；无团队数字员工为空
	TeamID            uuid.NullUUID      `json:"team_id"`
	DigitalEmployeeID uuid.UUID          `json:"digital_employee_id"`
	Name              string             `json:"name"`
	EncryptedValue    string             `json:"encrypted_value"`
	EncryptionKeyID   string             `json:"encryption_key_id"`
	ValueFingerprint  string             `json:"value_fingerprint"`
	Sensitive         bool               `json:"sensitive"`
	Status            string             `json:"status"`
	CreatedBy         uuid.NullUUID      `json:"created_by"`
	UpdatedBy         uuid.NullUUID      `json:"updated_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	Metadata          []byte             `json:"metadata"`
}

// 数字员工唯一执行实例表
type DigitalEmployeeExecutionInstance struct {
	// 数字员工执行实例主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 绑定的数字员工 ID
	DigitalEmployeeID uuid.UUID `json:"digital_employee_id"`
	// 承载执行实例的 Runtime 节点 UUID
	RuntimeNodeID uuid.UUID `json:"runtime_node_id"`
	// 执行实例使用的 Provider 类型
	ProviderType string `json:"provider_type"`
	// 数字员工在 Runtime 工作区中的长期目录
	AgentHomeDir string `json:"agent_home_dir"`
	// 工作区策略快照
	WorkspacePolicy []byte `json:"workspace_policy"`
	// Provider 会话策略快照
	SessionPolicy []byte `json:"session_policy"`
	// 预留的 Runtime 自动选择器
	RuntimeSelector []byte `json:"runtime_selector"`
	// 预留的容量需求
	CapacityRequirements []byte `json:"capacity_requirements"`
	// 预留的降级或 fallback 策略
	FallbackPolicy []byte `json:"fallback_policy"`
	// 执行实例状态
	Status string `json:"status"`
	// 执行实例就绪时间
	ReadyAt pgtype.Timestamptz `json:"ready_at"`
	// 执行实例禁用时间
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	// 执行实例进入错误状态时间
	ErrorAt pgtype.Timestamptz `json:"error_at"`
	// 执行实例错误说明
	ErrorMessage pgtype.Text `json:"error_message"`
	// 执行实例软删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// 执行实例扩展元数据
	Metadata []byte `json:"metadata"`
	// 执行实例创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 执行实例最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 数字员工个人 MCP 服务器配置
type DigitalEmployeeMcpBinding struct {
	// 数字员工 MCP 配置主键 UUID
	ID uuid.UUID `json:"id"`
	// 数字员工 MCP 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 数字员工 ID
	DigitalEmployeeID uuid.UUID `json:"digital_employee_id"`
	// 个人 MCP 显示名称，同一数字员工下未删除时唯一
	Name string `json:"name"`
	// 个人 MCP 远程 HTTP 地址
	Url string `json:"url"`
	// 引用的个人凭据 ID，由应用层校验归属和类型
	CredentialID uuid.NullUUID `json:"credential_id"`
	// 个人 MCP 状态，例如 active 或 disabled
	Status string `json:"status"`
	// 个人 MCP 扩展元数据 JSON
	Metadata []byte `json:"metadata"`
	// 个人 MCP 禁用时间
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	// 个人 MCP 软删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// 创建个人 MCP 的用户 ID
	CreatedBy uuid.NullUUID `json:"created_by"`
	// 个人 MCP 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 个人 MCP 更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 数字员工对注册表 MCP 的个人绑定
type DigitalEmployeeMcpBindingsV2 struct {
	// 员工 MCP 绑定主键 UUID
	ID uuid.UUID `json:"id"`
	// 绑定所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 数字员工 ID
	DigitalEmployeeID uuid.UUID `json:"digital_employee_id"`
	// 引用的注册表 MCP 定义 ID
	McpServerID uuid.UUID `json:"mcp_server_id"`
	// 该绑定使用的凭据环境变量名，值由数字员工环境变量提供
	CredentialEnvVar pgtype.Text `json:"credential_env_var"`
	// 绑定状态，例如 active 或 disabled
	Status string `json:"status"`
	// 绑定扩展元数据 JSON
	Metadata []byte `json:"metadata"`
	// 绑定禁用时间
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	// 绑定软删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// 创建绑定的用户 ID
	CreatedBy uuid.NullUUID `json:"created_by"`
	// 绑定创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 绑定更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 数字员工 runtime 就绪读视图,is_runtime_ready 与 overview runnable 判定一致,供协调器执行人选择过滤
type DigitalEmployeeRuntimeReadiness struct {
	TenantID          uuid.UUID `json:"tenant_id"`
	DigitalEmployeeID uuid.UUID `json:"digital_employee_id"`
	IsRuntimeReady    bool      `json:"is_runtime_ready"`
}

type DigitalEmployeeTemplate struct {
	ID                       uuid.UUID          `json:"id"`
	TenantID                 uuid.UUID          `json:"tenant_id"`
	Type                     string             `json:"type"`
	Label                    string             `json:"label"`
	Description              string             `json:"description"`
	DefaultRole              string             `json:"default_role"`
	RecommendedSkills        []byte             `json:"recommended_skills"`
	RecommendedMcpServers    []byte             `json:"recommended_mcp_servers"`
	RecommendedProviderTypes []byte             `json:"recommended_provider_types"`
	Metadata                 []byte             `json:"metadata"`
	Status                   string             `json:"status"`
	IsSystem                 bool               `json:"is_system"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	// 模板预填的人格记忆 Markdown
	PersonaMemoryMarkdown string `json:"persona_memory_markdown"`
	// 模板预填的数字员工能力绑定
	CapabilityBindings []byte `json:"capability_bindings"`
	// 模板预填的预算策略
	BudgetPolicy []byte `json:"budget_policy"`
}

// 数字员工工作目录受控文件身份表
type DigitalEmployeeWorkspaceFile struct {
	// 受控文件主键 UUID
	ID uuid.UUID `json:"id"`
	// 文件所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 文件所属数字员工团队 ID；无团队数字员工为空
	TeamID uuid.NullUUID `json:"team_id"`
	// 文件所属数字员工 ID
	DigitalEmployeeID uuid.UUID `json:"digital_employee_id"`
	// 数字员工根目录下的安全相对路径
	Path string `json:"path"`
	// 文件角色，例如 entrypoint、supporting_doc、provider_config 或 generated，由应用层注册表校验
	FileRole string `json:"file_role"`
	// 文件 MIME 类型
	MimeType string `json:"mime_type"`
	// 同步策略，例如 auto、manual 或 disabled，由应用层注册表校验
	SyncPolicy string `json:"sync_policy"`
	// 当前激活的文件版本 ID
	CurrentRevisionID uuid.NullUUID `json:"current_revision_id"`
	// 文件状态，例如 active、archived 或 deleted
	Status string `json:"status"`
	// 文件扩展元数据 JSON
	Metadata []byte `json:"metadata"`
	// 创建文件的用户 ID，系统创建时可为空
	CreatedBy uuid.NullUUID `json:"created_by"`
	// 文件创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 文件更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 文件归档时间
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	// 文件软删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// 数字员工工作目录受控文件内容版本表
type DigitalEmployeeWorkspaceFileRevision struct {
	// 文件版本主键 UUID
	ID uuid.UUID `json:"id"`
	// 文件版本所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属受控文件 ID
	FileID uuid.UUID `json:"file_id"`
	// 文件内递增版本号
	RevisionNumber int32 `json:"revision_number"`
	// DB 存储模式下的文本正文
	ContentText pgtype.Text `json:"content_text"`
	// 文件正文 SHA-256 十六进制校验值
	ContentHash string `json:"content_hash"`
	// 文件正文 UTF-8 字节数
	SizeBytes int32 `json:"size_bytes"`
	// 正文存储后端，首版使用 db，预留 object_store
	StorageBackend string `json:"storage_backend"`
	// 对象存储模式下的对象键
	ObjectKey pgtype.Text `json:"object_key"`
	// 创建版本的用户 ID，系统创建时可为空
	CreatedBy uuid.NullUUID `json:"created_by"`
	// 文件版本创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 版本变更说明
	ChangeNote pgtype.Text `json:"change_note"`
	// 文件版本扩展元数据 JSON
	Metadata []byte `json:"metadata"`
}

// 数字员工工作目录文件同步状态投影表
type DigitalEmployeeWorkspaceFileSync struct {
	// 同步状态主键 UUID
	ID uuid.UUID `json:"id"`
	// 同步状态所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 同步状态所属数字员工 ID
	DigitalEmployeeID uuid.UUID `json:"digital_employee_id"`
	// 同步目标执行实例 ID
	ExecutionInstanceID uuid.UUID `json:"execution_instance_id"`
	// 同步的受控文件 ID
	FileID uuid.UUID `json:"file_id"`
	// 同步目标文件版本 ID
	RevisionID uuid.UUID `json:"revision_id"`
	// 同步目标 Runtime 节点 ID
	RuntimeNodeID uuid.UUID `json:"runtime_node_id"`
	// 同步状态，例如 pending、synced 或 failed
	Status string `json:"status"`
	// Runtime 回写的已同步文件校验值
	SyncedHash pgtype.Text `json:"synced_hash"`
	// 同步失败时的错误摘要
	ErrorMessage pgtype.Text `json:"error_message"`
	// 最后一次同步命令 ID
	LastCommandID pgtype.Text `json:"last_command_id"`
	// 最后同步成功时间
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	// 同步状态创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 同步状态更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 执行账本事件表，记录项目任务执行、Provider、工具、MCP、外部能力和证据链的统一审计索引。
type ExecutionLedgerEvent struct {
	// 执行账本事件主键 UUID。
	ID uuid.UUID `json:"id"`
	// 执行账本事件所属租户 ID。
	TenantID uuid.UUID `json:"tenant_id"`
	// 执行账本事件所属团队 ID，可为空以兼容项目未绑定团队的历史数据。
	TeamID uuid.NullUUID `json:"team_id"`
	// 执行账本事件所属项目 ID。
	ProjectID uuid.UUID `json:"project_id"`
	// 执行账本事件关联项目任务 ID，可为空表示项目级执行事件。
	ProjectTaskID uuid.NullUUID `json:"project_task_id"`
	// 执行账本事件关联项目任务执行尝试 ID。
	ProjectTaskAttemptID uuid.NullUUID `json:"project_task_attempt_id"`
	// 执行事件类型，例如 attempt.started、provider.event、mcp.tool_call、summary.created。
	EventType string `json:"event_type"`
	// 来源事实类型，例如 project_task_attempt、provider_session_event、runtime_command_receipt。
	SourceType string `json:"source_type"`
	// 来源事实 ID 或稳定外部 ID。
	SourceID string `json:"source_id"`
	// 执行事件主体类型，例如 digital_employee、runtime_node、provider、system。
	ActorType string `json:"actor_type"`
	// 执行事件主体 ID 或外部标识。
	ActorID pgtype.Text `json:"actor_id"`
	// 关联 Runtime 节点 ID。
	RuntimeNodeID uuid.NullUUID `json:"runtime_node_id"`
	// 关联 Provider 类型，由服务端注册表校验。
	ProviderType pgtype.Text `json:"provider_type"`
	// Provider 外部会话 ID。
	ProviderSessionID pgtype.Text `json:"provider_session_id"`
	// 输入摘要，不保存完整 prompt、secret 或大 payload。
	InputSummary pgtype.Text `json:"input_summary"`
	// 输出摘要，不保存完整 raw payload。
	OutputSummary pgtype.Text `json:"output_summary"`
	// 错误分类，例如 provider_error、runtime_error、missing_context、capability_denied。
	ErrorFamily pgtype.Text `json:"error_family"`
	// 细分错误码。
	ErrorCode pgtype.Text `json:"error_code"`
	// 短错误说明，禁止写入 secret。
	ErrorMessage pgtype.Text `json:"error_message"`
	// 该事件对应失败是否可重试。
	Retryable pgtype.Bool `json:"retryable"`
	// 工件引用数组。
	ArtifactRefs []byte `json:"artifact_refs"`
	// 证据引用数组。
	EvidenceRefs []byte `json:"evidence_refs"`
	// 结构化扩展数据，禁止写入 secret 和完整 raw payload。
	Metadata []byte `json:"metadata"`
	// 事件发生时间。
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	// 执行账本事件幂等键。
	IdempotencyKey string `json:"idempotency_key"`
	// 执行账本事件创建时间。
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 执行账本事件更新时间。
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 收件箱可操作事项 read model，聚合需要人类用户处理的审批和项目决策待办
type InboxItem struct {
	// 收件箱事项ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 团队ID，可为空；第一版主要用于后续团队范围过滤
	TeamID uuid.NullUUID `json:"team_id"`
	// 目标处理人用户ID；第一版只有目标处理人可以执行动作
	TargetUserID uuid.UUID `json:"target_user_id"`
	// 事项范围：personal 或 team，由应用层校验
	Scope string `json:"scope"`
	// 收件箱事项类型，例如 approval 或 project_decision，由应用层注册校验
	ItemType string `json:"item_type"`
	// 来源对象类型，例如 approval_request 或 project_decision_request
	SourceType string `json:"source_type"`
	// 来源对象ID，与 source_type 共同定位事实源
	SourceID uuid.UUID `json:"source_id"`
	// 来源项目ID，用于项目筛选和上下文跳转
	SourceProjectID uuid.NullUUID `json:"source_project_id"`
	// 来源项目任务ID，用于后续任务上下文筛选
	SourceTaskID uuid.NullUUID `json:"source_task_id"`
	// 关联全局审批请求ID，用于防止审批和项目决策重复投影
	SourceApprovalRequestID uuid.NullUUID `json:"source_approval_request_id"`
	// 事项标题快照
	Title string `json:"title"`
	// 事项摘要快照
	Summary pgtype.Text `json:"summary"`
	// 风险等级快照，例如 low、medium、high
	RiskLevel pgtype.Text `json:"risk_level"`
	// 队列优先级快照，由应用层校验
	Priority pgtype.Text `json:"priority"`
	// 收件箱状态：open、resolved、cancelled，由来源状态驱动
	Status string `json:"status"`
	// 前端可展示动作 schema，最终合法性仍由来源服务校验
	ActionSchema []byte `json:"action_schema"`
	// 展示上下文快照，不作为业务事实源
	ContextPayload []byte `json:"context_payload"`
	// 前端上下文跳转信息
	DeepLink []byte `json:"deep_link"`
	// 事项关闭时间
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	// 最后活动时间，用于收件箱排序
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
	// 事项创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 事项更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 租户级 MCP HTTP 能力注册表，定义一次、被团队与数字员工绑定复用
type McpServer struct {
	// MCP 定义主键 UUID
	ID uuid.UUID `json:"id"`
	// MCP 定义所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// MCP 显示名称
	Name string `json:"name"`
	// MCP 稳定标识，渲染到 provider 配置的 server 键，租户内未删除时唯一
	ServerKey string `json:"server_key"`
	// MCP 描述
	Description string `json:"description"`
	// MCP 传输方式，仅支持 streamable_http 或 http
	Transport string `json:"transport"`
	// MCP 远程 HTTP 地址
	Url string `json:"url"`
	// MCP 鉴权方式：none、bearer_env 或 headers_env
	AuthStrategy string `json:"auth_strategy"`
	// MCP 必需环境变量名列表，数字员工缺失则绑定被阻断
	RequiredEnvVars []string `json:"required_env_vars"`
	// MCP 可选环境变量名列表
	OptionalEnvVars []string `json:"optional_env_vars"`
	// 各 provider 是否投射此 MCP 的可见性开关 JSON
	ProviderVisibility []byte `json:"provider_visibility"`
	// MCP 工具白名单
	ToolAllowlist []string `json:"tool_allowlist"`
	// MCP 风险等级
	RiskLevel string `json:"risk_level"`
	// MCP 状态，例如 active 或 disabled
	Status string `json:"status"`
	// MCP 扩展元数据 JSON
	Metadata []byte `json:"metadata"`
	// MCP 禁用时间
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	// MCP 软删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// 创建 MCP 定义的用户 ID
	CreatedBy uuid.NullUUID `json:"created_by"`
	// MCP 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// MCP 更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 项目核心事实容器
type Project struct {
	// 项目ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 团队ID（可选）
	TeamID uuid.NullUUID `json:"team_id"`
	// 项目名称
	Name string `json:"name"`
	// 项目说明
	Description pgtype.Text `json:"description"`
	// 项目目标或问题场景闭环目标
	Goal pgtype.Text `json:"goal"`
	// 项目状态，由应用层校验
	Status string `json:"status"`
	// 人类负责人ID
	HumanOwnerUserID uuid.UUID `json:"human_owner_user_id"`
	// 项目负责人或推进人用户ID
	LeaderUserID uuid.NullUUID `json:"leader_user_id"`
	// 项目验收人用户ID
	AcceptanceUserID uuid.NullUUID `json:"acceptance_user_id"`
	// 绑定的 Temporal 工作流ID
	CoordinationWorkflowID pgtype.Text `json:"coordination_workflow_id"`
	// 虚拟协调线程状态
	CoordinationStatus pgtype.Text `json:"coordination_status"`
	// 项目协调策略配置
	CoordinationPolicy []byte `json:"coordination_policy"`
	// 项目审批策略配置
	ApprovalPolicy []byte `json:"approval_policy"`
	// 项目证据与工件策略配置
	EvidencePolicy []byte `json:"evidence_policy"`
	// 项目归档时间
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	// 项目创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 项目更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 项目 Phase 1 源码仓库 URL；为空表示项目不绑定源码。
	RepoUrl pgtype.Text `json:"repo_url"`
	// 项目源码默认 base ref，不保存本地绝对路径。
	RepoDefaultBranch pgtype.Text `json:"repo_default_branch"`
	// 项目级 git 凭据引用，与员工 MCP 凭据分离。
	RepoGitCredentialRef pgtype.Text `json:"repo_git_credential_ref"`
	// 仓库 sparse checkout scope，必须由业务侧保证包含传递依赖闭包。
	RepoScope         []byte `json:"repo_scope"`
	RepoBindingStatus string `json:"repo_binding_status"`
	// 软删除时间；非空表示项目已从当前管理面移除
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// 项目绑定的场景模板 key，可空 = generic 兜底（行为同无模板）
	ScenarioTemplateKey pgtype.Text `json:"scenario_template_key"`
}

// 项目验收记录表，保存人类验收结论、证据引用和未解决风险
type ProjectAcceptanceRecord struct {
	// 项目验收记录ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// 做出验收结论的人类用户ID
	AcceptedByUserID uuid.UUID `json:"accepted_by_user_id"`
	// 验收状态，由应用层注册和校验
	Status string `json:"status"`
	// 验收结论
	Conclusion string `json:"conclusion"`
	// 验收摘要
	Summary pgtype.Text `json:"summary"`
	// 验收使用的证据引用ID数组
	EvidenceRefIds []byte `json:"evidence_ref_ids"`
	// 验收使用的报告引用ID数组
	ReportRefIds []byte `json:"report_ref_ids"`
	// 验收时仍未解决的风险数组
	UnresolvedRisks []byte `json:"unresolved_risks"`
	// 创建该验收记录时产生的项目事件ID
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
	// 验收记录创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 项目归档快照表，保存项目证据、报告和工件归档结果
type ProjectArchiveSnapshot struct {
	// 项目归档快照ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// 归档快照类型，由应用层注册和校验
	SnapshotType string `json:"snapshot_type"`
	// 归档快照状态，由应用层注册和校验
	Status string `json:"status"`
	// 归档快照对象存储引用或外部对象引用
	ObjectRef pgtype.Text `json:"object_ref"`
	// 归档摘要
	Summary pgtype.Text `json:"summary"`
	// 归档包含对象数量统计
	IncludedCounts []byte `json:"included_counts"`
	// 归档时被保留锁覆盖的工件ID数组
	RetainedArtifactIds []byte `json:"retained_artifact_ids"`
	// 创建归档保留锁时产生的项目事件ID
	RetentionLockEventID uuid.NullUUID `json:"retention_lock_event_id"`
	// 创建归档快照的人类用户ID
	CreatedByUserID uuid.UUID `json:"created_by_user_id"`
	// 创建该归档快照时产生的项目事件ID
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
	// 归档快照创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 项目工件引用表，保存项目内报告、附件、日志和执行产物的对象引用
type ProjectArtifactRef struct {
	// 项目工件引用ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// 关联项目任务ID，可为空表示项目级工件
	ProjectTaskID uuid.NullUUID `json:"project_task_id"`
	// 平台工件ID，可为空表示外部对象或尚未入库的对象
	ArtifactID uuid.NullUUID `json:"artifact_id"`
	// 工件类型，由应用层注册和校验
	ArtifactType string `json:"artifact_type"`
	// 工件标题快照
	Title string `json:"title"`
	// 对象存储引用或外部对象引用
	ObjectRef string `json:"object_ref"`
	// 工件内容类型
	ContentType pgtype.Text `json:"content_type"`
	// 工件大小字节数
	SizeBytes pgtype.Int8 `json:"size_bytes"`
	// 工件校验和
	Checksum pgtype.Text `json:"checksum"`
	// 保留状态，例如 unheld、held、released
	RetentionStatus string `json:"retention_status"`
	// 当前关联的保留锁ID
	RetentionHoldID uuid.NullUUID `json:"retention_hold_id"`
	// 工件扩展元数据
	Metadata []byte `json:"metadata"`
	// 创建该工件引用时产生的项目事件ID
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
	// 工件引用创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 工件引用更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 项目预算流水表，记录协调、执行和外部能力调用的预算估算与实际消耗
type ProjectBudgetLedger struct {
	// 项目预算流水ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// 关联协调作业ID
	CoordinationJobID uuid.NullUUID `json:"coordination_job_id"`
	// 关联项目任务ID
	ProjectTaskID uuid.NullUUID `json:"project_task_id"`
	// 关联数字员工ID
	DigitalEmployeeID uuid.NullUUID `json:"digital_employee_id"`
	// 成本类型，由应用层注册和校验
	CostType string `json:"cost_type"`
	// 预估 Token 数
	EstimatedTokens pgtype.Int8 `json:"estimated_tokens"`
	// 实际 Token 数
	ActualTokens pgtype.Int8 `json:"actual_tokens"`
	// 预估费用
	EstimatedCost pgtype.Numeric `json:"estimated_cost"`
	// 实际费用
	ActualCost pgtype.Numeric `json:"actual_cost"`
	// 预算流水来源，例如 coordinator、runtime、provider、capability
	Source string `json:"source"`
	// 记录该预算流水的原因
	Reason pgtype.Text `json:"reason"`
	// 创建该预算流水时产生的项目事件ID
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
	// 预算流水创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 项目配置与策略变更历史
type ProjectConfigRevision struct {
	// 项目配置修订ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// 项目内的递增版本号
	RevisionNumber int32 `json:"revision_number"`
	// 项目配置与策略快照
	ConfigSnapshot []byte `json:"config_snapshot"`
	// 配置变更摘要
	ChangeSummary pgtype.Text `json:"change_summary"`
	// 创建该配置修订的人类用户ID
	CreatedByUserID uuid.UUID `json:"created_by_user_id"`
	// 创建该修订时产生的项目事件ID
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
	// 配置修订创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 配置修订涉及的配置分区数组
	ChangedSections []byte `json:"changed_sections"`
	// 上一版项目配置修订ID
	PreviousRevisionID uuid.NullUUID `json:"previous_revision_id"`
	// 配置策略指纹，用于识别策略内容是否变化
	PolicyFingerprint pgtype.Text `json:"policy_fingerprint"`
	// 配置变更差异摘要
	DiffSummary []byte `json:"diff_summary"`
}

// 项目协调作业记录，追踪一次 Workflow 协调决策的输入、状态和输出事件
type ProjectCoordinationJob struct {
	// 协调作业ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// Temporal Workflow ID
	WorkflowID string `json:"workflow_id"`
	// 触发该作业的项目事件ID
	TriggerEventID uuid.NullUUID `json:"trigger_event_id"`
	// 协调作业类型，例如 demand_route、transfer_review、human_decision
	JobType string `json:"job_type"`
	// 协调作业状态：running、completed、failed、noop
	Status string `json:"status"`
	// 输入快照引用或小型快照 JSON
	InputSnapshotRef []byte `json:"input_snapshot_ref"`
	// 该作业产生的项目事件ID列表
	OutputEventIds []byte `json:"output_event_ids"`
	// 协调作业开始时间
	StartedAt pgtype.Timestamptz `json:"started_at"`
	// 协调作业结束时间
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	// 协调作业创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 项目侧人类决策查询投影，审批事实源归 approval_requests 与 approval_decisions
type ProjectDecisionRequest struct {
	// 项目决策请求投影ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// 全局审批请求ID，审批事实源引用
	ApprovalRequestID uuid.UUID `json:"approval_request_id"`
	// 关联协调作业ID
	CoordinationJobID uuid.NullUUID `json:"coordination_job_id"`
	// 关联项目任务ID
	ProjectTaskID uuid.NullUUID `json:"project_task_id"`
	// 目标处理人用户ID
	TargetUserID uuid.UUID `json:"target_user_id"`
	// 决策类型
	DecisionType string `json:"decision_type"`
	// 决策标题快照
	TitleSnapshot string `json:"title_snapshot"`
	// 决策摘要快照
	SummarySnapshot pgtype.Text `json:"summary_snapshot"`
	// 风险等级快照
	RiskLevelSnapshot pgtype.Text `json:"risk_level_snapshot"`
	// 审批状态快照
	StatusSnapshot string `json:"status_snapshot"`
	// 创建该投影时产生的项目事件ID
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
	// 处理该投影时产生的项目事件ID
	ResolvedEventID uuid.NullUUID `json:"resolved_event_id"`
	// 投影创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 投影更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 投影处理完成时间
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	// 该人类决策由哪个 dispatch gate 结果创建。
	DispatchGateResultID uuid.NullUUID `json:"dispatch_gate_result_id"`
	// 该人类决策由哪个结构化任务结果触发。
	ProjectTaskResultID uuid.NullUUID `json:"project_task_result_id"`
	// 该人类决策关联的计划版本ID，用于 ProjectCoordinator Continue-As-New 后恢复 plan_review 路由。
	PlanRevisionID uuid.NullUUID `json:"plan_revision_id"`
}

// 用户或外部系统提交到项目的需求
type ProjectDemand struct {
	// 项目需求ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// 提交需求的人类用户ID
	SubmittedByUserID uuid.UUID `json:"submitted_by_user_id"`
	// 需求标题
	Title string `json:"title"`
	// 需求正文
	Content pgtype.Text `json:"content"`
	// 来源类型：manual / github / ticket / document / log
	SourceType string `json:"source_type"`
	// 需求来源引用信息
	SourceRefs []byte `json:"source_refs"`
	// 需求附件引用列表
	Attachments []byte `json:"attachments"`
	// 需求优先级，由应用层校验
	Priority pgtype.Text `json:"priority"`
	// 需求风险等级，由应用层和策略校验
	RiskLevel pgtype.Text `json:"risk_level"`
	// 需求状态：submitted, recorded, planning_pending, planned, executing, completed, failed, cancelled
	Status string `json:"status"`
	// 创建该需求时产生的项目事件ID
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
	// 需求创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 需求更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 协调模式:plan=上游阻塞时报人类决策;loop=自动补链。随需求提交,冻结进 plan revision。
	CoordinationMode string `json:"coordination_mode"`
	// 需求级场景模板 key；解析顺序：需求显式 > 项目默认 > generic 兜底
	ScenarioTemplateKey pgtype.Text `json:"scenario_template_key"`
}

// 项目需求最终总结记录，按 demand 生成 append-only 总结和报告引用。
type ProjectDemandSummary struct {
	ID         uuid.UUID `json:"id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	ProjectID  uuid.UUID `json:"project_id"`
	DemandID   uuid.UUID `json:"demand_id"`
	Status     string    `json:"status"`
	Conclusion string    `json:"conclusion"`
	// 最终需求总结 JSON，包含目标、结论、任务状态、证据、人工决策、验证、风险和下一步建议。
	SummaryPayload     []byte             `json:"summary_payload"`
	ReportRefID        uuid.NullUUID      `json:"report_ref_id"`
	AcceptanceRequired bool               `json:"acceptance_required"`
	IdempotencyKey     string             `json:"idempotency_key"`
	CreatedEventID     uuid.NullUUID      `json:"created_event_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ProjectEmployeeNodeAffinity struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	ProjectID         uuid.UUID          `json:"project_id"`
	DigitalEmployeeID uuid.UUID          `json:"digital_employee_id"`
	RuntimeNodeID     uuid.UUID          `json:"runtime_node_id"`
	LastRunAt         pgtype.Timestamptz `json:"last_run_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// 项目生命周期内的关键事件流
type ProjectEvent struct {
	// 项目事件ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// 项目内的局部递增序号
	SequenceNumber int64 `json:"sequence_number"`
	// 项目事件类型，由应用层注册和校验
	EventType string `json:"event_type"`
	// 事件发起者类型：human_user / digital_employee / project_coordinator / system
	ActorType string `json:"actor_type"`
	// 事件发起者ID或系统标识
	ActorID string `json:"actor_id"`
	// 事件关联资源类型
	ResourceType pgtype.Text `json:"resource_type"`
	// 事件关联资源ID
	ResourceID pgtype.Text `json:"resource_id"`
	// 事件摘要
	Summary pgtype.Text `json:"summary"`
	// 事件结构化载荷
	Payload []byte `json:"payload"`
	// 事件创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 项目证据引用表，保存任务、路由和执行摘要产出的可审计证据
type ProjectEvidenceRef struct {
	// 项目证据引用ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// 关联项目任务ID，可为空表示项目级证据
	ProjectTaskID uuid.NullUUID `json:"project_task_id"`
	// 关联路由决策ID
	RouteDecisionID uuid.NullUUID `json:"route_decision_id"`
	// 关联执行摘要ID
	ExecutionSummaryID uuid.NullUUID `json:"execution_summary_id"`
	// 证据类型，由应用层注册和校验
	EvidenceType string `json:"evidence_type"`
	// 证据标题快照
	Title string `json:"title"`
	// 证据摘要
	Summary pgtype.Text `json:"summary"`
	// 证据来源类型，例如 artifact、report、manual、external
	SourceType string `json:"source_type"`
	// 证据来源引用，保存外部ID、对象地址或结构化引用摘要
	SourceRef string `json:"source_ref"`
	// 关联项目工件引用ID
	ArtifactRefID uuid.NullUUID `json:"artifact_ref_id"`
	// 提交者类型，例如 human_user、digital_employee、system
	SubmittedByType string `json:"submitted_by_type"`
	// 提交者ID，可为空表示系统提交
	SubmittedByID uuid.NullUUID `json:"submitted_by_id"`
	// 证据核验状态，由应用层注册和校验
	VerificationStatus string `json:"verification_status"`
	// 证据扩展元数据
	Metadata []byte `json:"metadata"`
	// 创建该证据引用时产生的项目事件ID
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
	// 证据引用创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 证据引用更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 项目任务执行摘要表，保存数字员工回写的结论、证据、工件和不确定性
type ProjectExecutionSummary struct {
	// 执行摘要ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// 关联项目任务ID
	ProjectTaskID uuid.UUID `json:"project_task_id"`
	// 回写摘要的数字员工ID
	DigitalEmployeeID uuid.UUID `json:"digital_employee_id"`
	// 执行结论
	Conclusion string `json:"conclusion"`
	// 证据引用数组
	EvidenceRefs []byte `json:"evidence_refs"`
	// 工件引用数组
	ArtifactRefs []byte `json:"artifact_refs"`
	// 置信度因素快照
	ConfidenceFactors []byte `json:"confidence_factors"`
	// 不确定性说明
	Uncertainty pgtype.Text `json:"uncertainty"`
	// 缺失信息数组
	MissingInformation []byte `json:"missing_information"`
	// 建议下一步动作
	RecommendedNextAction pgtype.Text `json:"recommended_next_action"`
	// 是否需要人类复核
	RequiresHumanReview bool `json:"requires_human_review"`
	// 关联转派请求ID
	TransferRequestID uuid.NullUUID `json:"transfer_request_id"`
	// 创建该摘要时产生的项目事件ID
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
	// 执行摘要创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 项目成员与数字员工池
type ProjectMember struct {
	// 项目成员记录ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// 成员类型：human_user / digital_employee / team
	PrincipalType string `json:"principal_type"`
	// 成员主体ID
	PrincipalID uuid.UUID `json:"principal_id"`
	// 项目内角色：owner / leader / acceptance / executor / reviewer / observer
	ProjectRole string `json:"project_role"`
	// 成员展示名称快照
	DisplayNameSnapshot pgtype.Text `json:"display_name_snapshot"`
	// 成员状态，由应用层校验
	Status string `json:"status"`
	// 项目成员级配置
	Settings []byte `json:"settings"`
	// 项目成员创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 项目成员更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 项目到 Runtime 节点的动态亲和放置状态，不保存本地绝对路径。
type ProjectPlacement struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	RuntimeNodeID   uuid.UUID          `json:"runtime_node_id"`
	PlacementStatus string             `json:"placement_status"`
	PlacementReason pgtype.Text        `json:"placement_reason"`
	AssignedAt      pgtype.Timestamptz `json:"assigned_at"`
	ReleasedAt      pgtype.Timestamptz `json:"released_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// 计划版本分解幂等声明表，保证 accepted PlanRevision 精确一次转换为 ProjectTask DAG。
type ProjectPlanDecompositionClaim struct {
	// 分解声明ID。
	ID uuid.UUID `json:"id"`
	// 租户ID。
	TenantID uuid.UUID `json:"tenant_id"`
	// 项目ID。
	ProjectID uuid.UUID `json:"project_id"`
	// 需求ID。
	DemandID uuid.UUID `json:"demand_id"`
	// 被分解的 accepted PlanRevision ID。
	AcceptedPlanRevisionID uuid.UUID `json:"accepted_plan_revision_id"`
	// 被分解计划的 canonical hash。
	PlanFingerprint string `json:"plan_fingerprint"`
	// 分解状态：in_flight, completed, failed。
	Status string `json:"status"`
	// 分解成功或恢复后对应的 ProjectTask ID。
	CreatedTaskIds []uuid.UUID `json:"created_task_ids"`
	// 分解失败时记录的结构化错误。
	Error []byte `json:"error"`
	// 分解声明创建时间。
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 分解声明最近更新时间。
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 项目计划版本表，保存 planner 生成并经服务端校验的人类可审核计划版本。
type ProjectPlanRevision struct {
	// 计划版本ID。
	ID uuid.UUID `json:"id"`
	// 租户ID，所有查询必须以租户隔离。
	TenantID uuid.UUID `json:"tenant_id"`
	// 项目所属团队ID；历史项目可为空，由应用层从项目校验。
	TeamID uuid.NullUUID `json:"team_id"`
	// 计划版本所属项目ID。
	ProjectID uuid.UUID `json:"project_id"`
	// 计划版本关联的用户需求或触发事件ID。
	DemandID uuid.UUID `json:"demand_id"`
	// 生成该计划版本的项目协调作业ID。
	CoordinationJobID uuid.NullUUID `json:"coordination_job_id"`
	// 兼容现有路由决策读模型的关联决策ID。
	RouteDecisionID uuid.NullUUID `json:"route_decision_id"`
	// 同一项目需求下从 1 开始递增的计划版本号。
	RevisionNumber int32 `json:"revision_number"`
	// 计划版本状态：draft, validation_failed, pending_review, accepted, rejected, superseded, decomposing, decomposed。
	Status string `json:"status"`
	// 结构化 PlanRevisionPayload，不保存长 prompt 或原始模型全文。
	Payload []byte `json:"payload"`
	// 生成计划的 planner provider。
	PlannerProvider pgtype.Text `json:"planner_provider"`
	// 生成计划的 planner model。
	PlannerModel pgtype.Text `json:"planner_model"`
	// PlanningSnapshot 输入摘要 hash。
	PlannerInputHash pgtype.Text `json:"planner_input_hash"`
	// canonical payload hash，用于幂等与审计。
	PlanFingerprint string `json:"plan_fingerprint"`
	// 服务端校验 hard error 列表。
	ValidationErrors []byte `json:"validation_errors"`
	// 服务端校验 warning 列表。
	ValidationWarnings []byte `json:"validation_warnings"`
	// 该版本是否需要人类 review。
	ReviewRequired bool `json:"review_required"`
	// 需要人类 review 的摘要原因。
	ReviewReason pgtype.Text `json:"review_reason"`
	// 接受该计划版本的人类用户ID；策略自动接受时为空。
	AcceptedBy uuid.NullUUID `json:"accepted_by"`
	// 计划版本被接受时间。
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	// 驳回该计划版本的人类用户ID。
	RejectedBy uuid.NullUUID `json:"rejected_by"`
	// 计划版本被驳回时间。
	RejectedAt pgtype.Timestamptz `json:"rejected_at"`
	// 驳回或要求修改的原因。
	RejectionReason pgtype.Text `json:"rejection_reason"`
	// 替代该版本的新计划版本ID。
	SupersededByRevisionID uuid.NullUUID `json:"superseded_by_revision_id"`
	// 分解该版本的幂等 claim ID。
	DecompositionClaimID uuid.NullUUID `json:"decomposition_claim_id"`
	// 该计划版本分解后创建或重放的 ProjectTask ID。
	CreatedTaskIds []uuid.UUID `json:"created_task_ids"`
	// 计划版本创建时间。
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 计划版本最近更新时间。
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 创建该计划版本时产生的项目事件ID，用于 ProjectCoordinator Continue-As-New 后恢复协调作业输出事件链。
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
	// 从 demand 冻结的协调模式;NULL(存量)按 loop 解释。
	CoordinationMode pgtype.Text `json:"coordination_mode"`
}

// 项目报告引用表，保存阶段汇报、验收报告和归档报告的对象引用
type ProjectReportRef struct {
	// 项目报告引用ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// 报告类型，由应用层注册和校验
	ReportType string `json:"report_type"`
	// 报告标题快照
	Title string `json:"title"`
	// 报告摘要
	Summary pgtype.Text `json:"summary"`
	// 报告对象存储引用或外部对象引用
	ObjectRef string `json:"object_ref"`
	// 报告格式，例如 markdown、pdf、html、json
	Format string `json:"format"`
	// 生成者类型，例如 human_user、digital_employee、system
	GeneratedByType string `json:"generated_by_type"`
	// 生成者ID，可为空表示系统生成
	GeneratedByID uuid.NullUUID `json:"generated_by_id"`
	// 创建该报告引用时产生的项目事件ID
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
	// 报告引用创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 项目需求路由决策表，保存虚拟协调线程选择执行员工和输出契约的结构化结论
type ProjectRouteDecision struct {
	// 路由决策ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// 产生该决策的协调作业ID
	CoordinationJobID uuid.UUID `json:"coordination_job_id"`
	// 关联需求ID
	DemandID uuid.NullUUID `json:"demand_id"`
	// 候选数字员工ID数组
	CandidateDigitalEmployeeIds []byte `json:"candidate_digital_employee_ids"`
	// 选中的数字员工ID数组
	SelectedDigitalEmployeeIds []byte `json:"selected_digital_employee_ids"`
	// 路由理由
	Reason string `json:"reason"`
	// 任务输入要求
	InputRequirements []byte `json:"input_requirements"`
	// 期望输出契约数组
	ExpectedOutputs []byte `json:"expected_outputs"`
	// 预算估算快照
	BudgetEstimate []byte `json:"budget_estimate"`
	// 是否需要人类先审核该决策
	RequiresHumanReview bool `json:"requires_human_review"`
	// 创建该决策时产生的项目事件ID
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
	// 路由决策创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProjectRuntimeNode struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	RuntimeNodeID uuid.UUID          `json:"runtime_node_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// 项目内可分派、可执行的工作项
type ProjectTask struct {
	// 项目任务ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// 关联项目需求ID
	DemandID uuid.NullUUID `json:"demand_id"`
	// 项目任务标题
	Title string `json:"title"`
	// 项目任务摘要
	Summary pgtype.Text `json:"summary"`
	// 任务状态：pending, planned, queued, assigned, blocked, running, waiting_human, completed, failed, cancelled；queued 表示已分派并等待 Runtime 真正启动。
	Status string `json:"status"`
	// 当前分派的数字员工ID
	AssignedDigitalEmployeeID uuid.NullUUID `json:"assigned_digital_employee_id"`
	// 关联的底层 Runtime 任务ID（若有）
	RuntimeTaskID uuid.NullUUID `json:"runtime_task_id"`
	// 关联的数字员工执行记录ID（若有）
	DigitalEmployeeRunID uuid.NullUUID `json:"digital_employee_run_id"`
	// 任务风险等级，由应用层和策略校验
	RiskLevel pgtype.Text `json:"risk_level"`
	// 是否需要人类审批后继续
	RequiresHumanApproval bool `json:"requires_human_approval"`
	// 最新关联项目事件ID
	LatestEventID uuid.NullUUID `json:"latest_event_id"`
	// 项目任务创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 项目任务更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 创建该任务的项目协调作业ID，由应用层校验租户和项目范围
	CoordinationJobID uuid.NullUUID `json:"coordination_job_id"`
	// 创建该任务的路由决策ID，由应用层校验租户和项目范围
	RouteDecisionID uuid.NullUUID `json:"route_decision_id"`
	// Planner在同一协调图内生成的稳定任务键，用于幂等重放和图展示
	PlannedTaskKey pgtype.Text `json:"planned_task_key"`
	// 任务类型开放字符串，例如 analysis、implementation、review、test 或 summary，由应用层注册校验
	TaskKind pgtype.Text `json:"task_kind"`
	// 任务在规划图中的展示阶段序号，执行事实仍以依赖边为准
	StageIndex pgtype.Int4 `json:"stage_index"`
	// 任务级输出契约数组，用于完成前校验和下游交接
	ExpectedOutputs []byte `json:"expected_outputs"`
	// 任务输入要求JSON，描述执行该任务需要的上下文切片
	InputRequirements []byte `json:"input_requirements"`
	// 任务交接契约JSON，描述下游可消费的证据、工件、结论和引用要求
	HandoffContract []byte `json:"handoff_contract"`
	// Planner审计摘要JSON，不保存长prompt或模型原文
	PlannerMetadata []byte `json:"planner_metadata"`
	// 当前项目任务执行尝试ID，指向当前 queued、running 或 waiting_human 尝试。
	CurrentAttemptID uuid.NullUUID `json:"current_attempt_id"`
	// 生成该任务的已接受计划版本ID。
	AcceptedPlanRevisionID uuid.NullUUID `json:"accepted_plan_revision_id"`
	// 计划分解幂等声明键，用于同一计划分解重复写入去重。
	DecompositionClaimKey pgtype.Text `json:"decomposition_claim_key"`
	// 任务执行尝试次数。
	AttemptCount int32 `json:"attempt_count"`
	// 任务允许的最大执行尝试次数。
	MaxAttempts pgtype.Int4 `json:"max_attempts"`
	// 任务下次可重试时间。
	RetryNotBefore pgtype.Timestamptz `json:"retry_not_before"`
	// 任务等待人类或外部条件的原因。
	WaitingReason pgtype.Text `json:"waiting_reason"`
	// 任务等待的人类决策或请求ID。
	WaitingRequestID uuid.NullUUID `json:"waiting_request_id"`
	// 任务进入终态的原因。
	TerminalReason pgtype.Text `json:"terminal_reason"`
	// 任务进入终态时写入的项目事件ID。
	TerminalEventID uuid.NullUUID `json:"terminal_event_id"`
	// 取消任务的主体类型或来源。
	CancelledBy pgtype.Text `json:"cancelled_by"`
	// 标记任务失败的主体类型或来源。
	FailedBy pgtype.Text `json:"failed_by"`
	// 任务状态最近一次变化时间。
	StatusChangedAt pgtype.Timestamptz `json:"status_changed_at"`
	// 该任务最近一次 gate 结果ID。
	LatestDispatchGateResultID uuid.NullUUID `json:"latest_dispatch_gate_result_id"`
	// 该任务是否为另一个 ProjectTask 的 append-only 修订任务。
	RevisionOfTaskID uuid.NullUUID `json:"revision_of_task_id"`
	// 该任务最新结构化结果记录ID。
	LatestTaskResultID uuid.NullUUID `json:"latest_task_result_id"`
	// Graph extension round: 0 for the original plan, N for tasks appended in the Nth round.
	PlanIteration int32 `json:"plan_iteration"`
}

// 项目任务执行尝试表，记录项目任务调度、租约、重试和终态回写。
type ProjectTaskAttempt struct {
	// 执行尝试主键ID。
	ID uuid.UUID `json:"id"`
	// 执行尝试所属租户ID。
	TenantID uuid.UUID `json:"tenant_id"`
	// 执行尝试所属项目任务ID。
	ProjectTaskID uuid.UUID `json:"project_task_id"`
	// 尝试序号，从 1 开始递增。
	AttemptNo int32 `json:"attempt_no"`
	// 尝试状态：queued, running, succeeded, failed, cancelled, lost, timed_out, waiting_human。
	Status string `json:"status"`
	// 执行尝试关联的数字员工运行ID。
	DigitalEmployeeRunID uuid.NullUUID `json:"digital_employee_run_id"`
	// 执行尝试关联的 Runtime 任务ID。
	RuntimeTaskID uuid.NullUUID `json:"runtime_task_id"`
	// 执行尝试所在 Runtime 节点ID。
	RuntimeNodeID uuid.NullUUID `json:"runtime_node_id"`
	// 执行尝试关联的 Provider 会话ID。
	ProviderSessionID pgtype.Text `json:"provider_session_id"`
	// 执行上下文包 JSON，保存下发给 Runtime 的任务上下文切片。
	ExecutionContextPacket []byte `json:"execution_context_packet"`
	// 执行上下文包版本。
	ExecutionContextPacketVersion string `json:"execution_context_packet_version"`
	// Runtime 租约令牌。
	LeaseToken string `json:"lease_token"`
	// Runtime 租约过期时间。
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	// Runtime 租约最近续约时间。
	RenewedAt pgtype.Timestamptz `json:"renewed_at"`
	// 执行尝试被判定丢失的时间。
	LostAt pgtype.Timestamptz `json:"lost_at"`
	// 执行尝试开始时间。
	StartedAt pgtype.Timestamptz `json:"started_at"`
	// 执行尝试结束时间。
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	// 执行尝试超时时间。
	TimeoutAt pgtype.Timestamptz `json:"timeout_at"`
	// 执行失败后是否允许重试。
	Retryable pgtype.Bool `json:"retryable"`
	// 执行失败分类。
	FailureFamily pgtype.Text `json:"failure_family"`
	// 执行失败说明。
	FailureMessage pgtype.Text `json:"failure_message"`
	// 执行尝试创建幂等键。
	IdempotencyKey string `json:"idempotency_key"`
	// 执行尝试创建时写入的项目事件ID。
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
	// 执行尝试进入终态时写入的项目事件ID。
	TerminalEventID uuid.NullUUID `json:"terminal_event_id"`
	// 执行尝试创建时间。
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 执行尝试最近更新时间。
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 创建该尝试前通过的 gate 结果ID。
	DispatchGateResultID uuid.NullUUID `json:"dispatch_gate_result_id"`
	// 该尝试的墙钟预算上限，空表示未设置。
	BudgetWallClockLimitSec    pgtype.Int4        `json:"budget_wall_clock_limit_sec"`
	BudgetLastHeartbeatAt      pgtype.Timestamptz `json:"budget_last_heartbeat_at"`
	BudgetConsumedWallClockSec int32              `json:"budget_consumed_wall_clock_sec"`
	BudgetConsumedTokens       int32              `json:"budget_consumed_tokens"`
	BudgetTrippedAt            pgtype.Timestamptz `json:"budget_tripped_at"`
	// 预算熔断原因，例如 wall_clock_exceeded、token_limit_exceeded。
	BudgetTripReason pgtype.Text `json:"budget_trip_reason"`
	// 执行尝试实际分派的数字员工 ID，历史记录可为空。
	DigitalEmployeeID uuid.NullUUID `json:"digital_employee_id"`
	// 执行尝试使用的 Provider 类型，优先来自上下文包或数字员工主 Provider。
	ProviderType pgtype.Text `json:"provider_type"`
	// Raw transcript backend: object_store | local_file
	LogStore pgtype.Text `json:"log_store"`
	// Opaque reference to the raw transcript manifest
	LogRef pgtype.Text `json:"log_ref"`
	// Total raw transcript bytes across all segments
	LogBytes pgtype.Int8 `json:"log_bytes"`
	// Runtime-reported sha256 of the concatenated raw transcript; must be recomputed before being trusted
	LogSha256 pgtype.Text `json:"log_sha256"`
	// Whether raw transcript segments are stored compressed
	LogCompressed bool `json:"log_compressed"`
}

type ProjectTaskAttemptContextUpdate struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	ProjectTaskID  uuid.UUID          `json:"project_task_id"`
	AttemptID      uuid.NullUUID      `json:"attempt_id"`
	UpdateKind     string             `json:"update_kind"`
	Payload        []byte             `json:"payload"`
	DeliveryMode   string             `json:"delivery_mode"`
	CreatedEventID uuid.NullUUID      `json:"created_event_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Runtime 对项目任务执行的结构化证明，保存命令、退出码、日志哈希、产物哈希和 git 证据引用。
type ProjectTaskAttestation struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	ProjectID         uuid.UUID          `json:"project_id"`
	ProjectTaskID     uuid.UUID          `json:"project_task_id"`
	AttemptID         uuid.UUID          `json:"attempt_id"`
	RuntimeNodeID     uuid.UUID          `json:"runtime_node_id"`
	ProviderSessionID pgtype.Text        `json:"provider_session_id"`
	AttestationType   string             `json:"attestation_type"`
	Status            string             `json:"status"`
	CommandArgv       []byte             `json:"command_argv"`
	ExitCode          pgtype.Int4        `json:"exit_code"`
	DurationMs        pgtype.Int8        `json:"duration_ms"`
	LogRef            pgtype.Text        `json:"log_ref"`
	StdoutSha256      pgtype.Text        `json:"stdout_sha256"`
	StderrSha256      pgtype.Text        `json:"stderr_sha256"`
	ArtifactRefs      []byte             `json:"artifact_refs"`
	ArtifactHashes    []byte             `json:"artifact_hashes"`
	GitBranch         pgtype.Text        `json:"git_branch"`
	GitBaseRef        pgtype.Text        `json:"git_base_ref"`
	GitHeadSha        pgtype.Text        `json:"git_head_sha"`
	GitDiffSha256     pgtype.Text        `json:"git_diff_sha256"`
	Metadata          []byte             `json:"metadata"`
	IdempotencyKey    string             `json:"idempotency_key"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	// 生成该执行证明的数字员工 ID；历史缺失记录使用全零 UUID 占位。
	DigitalEmployeeID uuid.UUID `json:"digital_employee_id"`
	// 执行时使用的员工能力 manifest 版本。
	CapabilityManifestVersion pgtype.Text `json:"capability_manifest_version"`
	// 执行时 Provider 认证模式：host、employee 或 explicit_credential。
	ProviderAuthMode string `json:"provider_auth_mode"`
}

// 项目任务依赖边，记录一个任务被另一个任务完成结果阻塞的DAG关系
type ProjectTaskDependency struct {
	// 任务依赖边ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// 生成该依赖边的协调作业ID
	CoordinationJobID uuid.NullUUID `json:"coordination_job_id"`
	// 被阻塞的项目任务ID
	DependentTaskID uuid.UUID `json:"dependent_task_id"`
	// 必须先完成的前置项目任务ID
	BlockerTaskID uuid.UUID `json:"blocker_task_id"`
	// 依赖边创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ProjectTask 分派 Runtime 前的 Control Plane gate 结果，保存可审计的检查摘要、阻塞原因和后续 attempt 或人类请求引用。
type ProjectTaskDispatchGateResult struct {
	// Gate 结果ID。
	ID uuid.UUID `json:"id"`
	// 租户ID。
	TenantID uuid.UUID `json:"tenant_id"`
	// 项目ID。
	ProjectID uuid.UUID `json:"project_id"`
	// 被检查的 ProjectTask ID。
	ProjectTaskID uuid.UUID `json:"project_task_id"`
	// 生成任务的 accepted PlanRevision ID。
	AcceptedPlanRevisionID uuid.NullUUID `json:"accepted_plan_revision_id"`
	// PlanRevision payload 内稳定任务键。
	PlannedTaskKey pgtype.Text `json:"planned_task_key"`
	// Gate 检查时的被选数字员工ID。
	SelectedEmployeeID uuid.UUID `json:"selected_employee_id"`
	// 本次 gate 预期创建的执行尝试序号。
	AttemptNo int32 `json:"attempt_no"`
	// 触发 gate 的原因，例如 root_ready、dependency_unlocked、human_resolved、retry。
	DispatchReason string `json:"dispatch_reason"`
	// Gate 幂等键，同一任务同一分派原因和尝试序号只保留一个结果。
	IdempotencyKey string `json:"idempotency_key"`
	// 通过 gate 后交给 dispatch 的稳定 token，不包含密钥。
	DispatchToken string `json:"dispatch_token"`
	// Gate 状态：passed, waiting_human, blocked, retry_later, replan_required。
	Status string `json:"status"`
	// Gate 检查时间。
	CheckedAt pgtype.Timestamptz `json:"checked_at"`
	// 检查项摘要 JSON 数组，禁止保存密钥、完整连接串、敏感 SQL 或完整日志。
	Checks []byte `json:"checks"`
	// 阻塞原因 JSON 数组，禁止保存密钥、完整连接串、敏感 SQL 或完整日志。
	Blockers []byte `json:"blockers"`
	// 需要人类动作时的请求摘要，不作为审批事实源。
	HumanActionRequest []byte `json:"human_action_request"`
	// 暂态不满足时建议下次 gate 时间。
	RetryAfter pgtype.Timestamptz `json:"retry_after"`
	// Gate 通过后创建的 ProjectTaskAttempt ID。
	AttemptID uuid.NullUUID `json:"attempt_id"`
	// Gate 创建的人类决策请求投影ID。
	DecisionRequestID uuid.NullUUID `json:"decision_request_id"`
	// 记录该 gate 结果时产生的项目事件ID。
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
	// Gate 结果创建时间。
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Gate 结果最近更新时间。
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// ProjectTask 结构化结果契约记录，保存 Runtime/Provider 写回后的可审计结果、校验状态和调度决策。
type ProjectTaskResult struct {
	ID                 uuid.UUID     `json:"id"`
	TenantID           uuid.UUID     `json:"tenant_id"`
	ProjectID          uuid.UUID     `json:"project_id"`
	ProjectTaskID      uuid.UUID     `json:"project_task_id"`
	AttemptID          uuid.NullUUID `json:"attempt_id"`
	ExecutionSummaryID uuid.NullUUID `json:"execution_summary_id"`
	ResultStatus       string        `json:"result_status"`
	ValidationStatus   string        `json:"validation_status"`
	Decision           string        `json:"decision"`
	// TaskResultContract JSON，不保存完整日志、密钥、连接串或大段 prompt。
	ContractPayload []byte `json:"contract_payload"`
	// 结果契约校验错误数组。
	ValidationErrors   []byte `json:"validation_errors"`
	ValidationWarnings []byte `json:"validation_warnings"`
	IdempotencyKey     string `json:"idempotency_key"`
	// 结果需要人类判断时的请求摘要，不作为审批事实源。
	HumanReviewRequest []byte `json:"human_review_request"`
	// 任务结果触发重规划时的结构化原因和约束。
	ReplanRequest []byte `json:"replan_request"`
	// 任务结果触发修订时的结构化原因和建议。
	RevisionRequest   []byte             `json:"revision_request"`
	CreatedEventID    uuid.NullUUID      `json:"created_event_id"`
	DecisionRequestID uuid.NullUUID      `json:"decision_request_id"`
	RevisionTaskID    uuid.NullUUID      `json:"revision_task_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// 项目任务转派请求表，保存数字员工发起的结构化转派事实
type ProjectTransferRequest struct {
	// 转派请求ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属项目ID
	ProjectID uuid.UUID `json:"project_id"`
	// 关联项目任务ID
	ProjectTaskID uuid.UUID `json:"project_task_id"`
	// 发起转派请求的数字员工ID
	RequestedByDigitalEmployeeID uuid.UUID `json:"requested_by_digital_employee_id"`
	// 转派理由
	Reason string `json:"reason"`
	// 建议员工类型
	SuggestedEmployeeType pgtype.Text `json:"suggested_employee_type"`
	// 建议数字员工ID数组
	SuggestedDigitalEmployeeIds []byte `json:"suggested_digital_employee_ids"`
	// 缺失上下文引用数组
	MissingContextRefs []byte `json:"missing_context_refs"`
	// 转派请求状态：requested、accepted、rejected、cancelled
	Status string `json:"status"`
	// 创建该请求时产生的项目事件ID
	CreatedEventID uuid.NullUUID `json:"created_event_id"`
	// 转派请求创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 转派请求更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Provider 会话映射表
type ProviderSession struct {
	// Provider 会话主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// Provider 自身返回的会话 ID
	ProviderSessionID string `json:"provider_session_id"`
	// 关联的数字员工 ID
	DigitalEmployeeID uuid.UUID `json:"digital_employee_id"`
	// 关联的数字员工执行实例 ID
	ExecutionInstanceID uuid.UUID `json:"execution_instance_id"`
	// 承载会话的 Runtime 节点 UUID
	RuntimeNodeID uuid.UUID `json:"runtime_node_id"`
	// Provider 类型
	ProviderType string `json:"provider_type"`
	// Provider 会话状态
	Status string `json:"status"`
	// Provider 会话是否可恢复
	Recoverable bool `json:"recoverable"`
	// Provider 会话最后活跃时间
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	// Provider 会话关闭时间
	ClosedAt pgtype.Timestamptz `json:"closed_at"`
	// Provider 会话错误说明
	ErrorMessage pgtype.Text `json:"error_message"`
	// Provider 会话扩展元数据
	Metadata []byte `json:"metadata"`
	// Provider 会话创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Provider 会话最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Provider会话展示ID
	SessionDisplayID pgtype.Text `json:"session_display_id"`
	// Provider会话启动参数
	SessionParams []byte `json:"session_params"`
	// Provider适配器可恢复的会话状态
	SessionState []byte `json:"session_state"`
	// 最后处理的Provider事件序号
	LastSequenceNumber int32 `json:"last_sequence_number"`
	// 最后关联的Runtime命令ID
	LastCommandID pgtype.Text `json:"last_command_id"`
	// 最后关联的任务运行ID
	LastRunID uuid.NullUUID `json:"last_run_id"`
	// 最后一次错误分类
	LastErrorFamily pgtype.Text `json:"last_error_family"`
	// Runtime最后回写会话时间
	LastRuntimeSeenAt pgtype.Timestamptz `json:"last_runtime_seen_at"`
	// Task lineage root this session is scoped to; null for pre-refactor employee-level sessions.
	ProjectTaskRootID uuid.NullUUID `json:"project_task_root_id"`
}

// Provider 会话事件流表
type ProviderSessionEvent struct {
	// Provider 会话事件主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// Provider 会话表内部 UUID
	ProviderSessionID uuid.UUID `json:"provider_session_id"`
	// 关联的数字员工 ID
	DigitalEmployeeID uuid.UUID `json:"digital_employee_id"`
	// 关联的数字员工执行实例 ID
	ExecutionInstanceID uuid.UUID `json:"execution_instance_id"`
	// 事件来源 Runtime 节点 UUID
	RuntimeNodeID uuid.UUID `json:"runtime_node_id"`
	// Provider 类型
	ProviderType string `json:"provider_type"`
	// Provider 事件类型
	EventType string `json:"event_type"`
	// Provider 会话内事件序号
	SequenceNumber int32 `json:"sequence_number"`
	// 归一化后的 Provider 事件负载
	Payload []byte `json:"payload"`
	// 触发该事件的平台请求 ID，request_id 或 command_id 至少填写一个
	RequestID pgtype.Text `json:"request_id"`
	// 触发该事件的平台命令 ID，request_id 或 command_id 至少填写一个
	CommandID pgtype.Text `json:"command_id"`
	// 原始输出对象存储引用或摘要引用
	RawEventRef pgtype.Text `json:"raw_event_ref"`
	// Provider 会话事件扩展元数据
	Metadata []byte `json:"metadata"`
	// Provider 会话事件创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Provider事件日志对象引用
	LogRef pgtype.Text `json:"log_ref"`
	// 事件携带的会话状态增量
	SessionStatePatch []byte `json:"session_state_patch"`
}

// Runtime Agent 环境级接入引导密钥表
type RuntimeBootstrapKey struct {
	// 接入引导密钥主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID，默认使用开发租户
	TenantID uuid.UUID `json:"tenant_id"`
	// 接入引导密钥展示名称
	Name string `json:"name"`
	// 接入引导密钥哈希，禁止保存明文
	KeyHash string `json:"key_hash"`
	// 接入引导密钥状态
	Status string `json:"status"`
	// 接入引导密钥用途说明
	Description pgtype.Text `json:"description"`
	// 接入引导密钥过期时间
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// 创建该密钥的用户 ID
	CreatedBy uuid.NullUUID `json:"created_by"`
	// 接入引导密钥撤销时间
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	// 撤销该密钥的用户 ID
	RevokedBy uuid.NullUUID `json:"revoked_by"`
	// 接入引导密钥撤销原因
	RevokedReason pgtype.Text `json:"revoked_reason"`
	// 接入引导密钥扩展元数据
	Metadata []byte `json:"metadata"`
	// 接入引导密钥创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 接入引导密钥最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Runtime Agent 上报的 Provider 与工作区能力表
type RuntimeCapability struct {
	// Runtime 能力主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// Runtime 节点 UUID
	RuntimeNodeID uuid.UUID `json:"runtime_node_id"`
	// Runtime 能力类型，例如 provider 或 workspace
	CapabilityType string `json:"capability_type"`
	// Runtime 能力在节点内的稳定键
	CapabilityKey string `json:"capability_key"`
	// Provider 类型，例如 claude-code、opencode、codex
	ProviderType string `json:"provider_type"`
	// Provider 版本
	ProviderVersion pgtype.Text `json:"provider_version"`
	// Provider 可执行文件路径
	BinaryPath pgtype.Text `json:"binary_path"`
	// Provider 当前是否可用；执行实例绑定前必须为可用
	Available bool `json:"available"`
	// Runtime 工作区根目录
	WorkspaceBaseDir pgtype.Text `json:"workspace_base_dir"`
	// Runtime 上报的容量信息
	Capacity []byte `json:"capacity"`
	// Runtime 能力标签，用于后续选择器匹配
	Labels []byte `json:"labels"`
	// Runtime 能力当前状态
	Status string `json:"status"`
	// Runtime 能力状态详情
	Details []byte `json:"details"`
	// Provider 能力健康状态
	HealthStatus string `json:"health_status"`
	// Runtime 能力扩展元数据
	Metadata []byte `json:"metadata"`
	// Runtime 能力最近上报时间
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	// Runtime 能力禁用时间
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	// Runtime 能力归档时间
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	// Runtime 能力首次上报时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Runtime 能力最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Runtime 命令回执表，记录下发、回写和终态结果
type RuntimeCommandReceipt struct {
	// 命令回执ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 控制平面生成的命令ID
	CommandID string `json:"command_id"`
	// 命令类型
	CommandType string `json:"command_type"`
	// 目标Runtime节点UUID
	RuntimeNodeID uuid.UUID `json:"runtime_node_id"`
	// 目标Runtime业务节点ID
	NodeID string `json:"node_id"`
	// 命令关联资源类型
	ResourceType string `json:"resource_type"`
	// 命令关联资源ID
	ResourceID uuid.UUID `json:"resource_id"`
	// 命令状态
	Status string `json:"status"`
	// 命令下发负载
	Payload []byte `json:"payload"`
	// 命令回写结果
	Result []byte `json:"result"`
	// 命令错误信息
	ErrorMessage pgtype.Text `json:"error_message"`
	// 命令下发时间
	DispatchedAt pgtype.Timestamptz `json:"dispatched_at"`
	// 命令完成时间
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Runtime Agent 接入审批状态表
type RuntimeEnrollment struct {
	// Runtime 接入记录主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// Runtime 节点 UUID
	RuntimeNodeID uuid.NullUUID `json:"runtime_node_id"`
	// Runtime 外部业务节点 ID
	NodeID string `json:"node_id"`
	// 用于发起接入的有效引导密钥 ID，不能为空
	BootstrapKeyID uuid.UUID `json:"bootstrap_key_id"`
	// 接入审批状态：pending、approved、rejected 或 revoked
	Status string `json:"status"`
	// Runtime hello 上报的接入请求快照
	RequestPayload []byte `json:"request_payload"`
	// 批准接入的用户 ID
	ApprovedBy uuid.NullUUID `json:"approved_by"`
	// 批准接入时间
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
	// 拒绝接入的用户 ID
	RejectedBy uuid.NullUUID `json:"rejected_by"`
	// 拒绝接入时间
	RejectedAt pgtype.Timestamptz `json:"rejected_at"`
	// 拒绝接入原因
	RejectReason pgtype.Text `json:"reject_reason"`
	// 撤销接入的用户 ID
	RevokedBy uuid.NullUUID `json:"revoked_by"`
	// 撤销接入时间
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	// 撤销接入原因
	RevokeReason pgtype.Text `json:"revoke_reason"`
	// Runtime 最近一次 hello 时间
	LastHelloAt pgtype.Timestamptz `json:"last_hello_at"`
	// 接入记录创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 接入记录最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Runtime 管理面统一事件流，用于 Runtime 总览和事件审计
type RuntimeEvent struct {
	// Runtime 管理面事件主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID，用于 Runtime 事件租户隔离
	TenantID uuid.UUID `json:"tenant_id"`
	// 关联 Runtime 节点 UUID，可为空以支持仅有 node_id 的接入请求
	RuntimeNodeID uuid.NullUUID `json:"runtime_node_id"`
	// Runtime 外部业务节点 ID
	NodeID pgtype.Text `json:"node_id"`
	// Runtime 管理面事件类型
	EventType string `json:"event_type"`
	// 事件严重级别：info、success、warning 或 error
	Severity string `json:"severity"`
	// 事件来源模块
	Source string `json:"source"`
	// 事件列表展示标题
	Title string `json:"title"`
	// 事件摘要描述
	Description pgtype.Text `json:"description"`
	// 关联 Provider 类型
	ProviderType pgtype.Text `json:"provider_type"`
	// 原始事实类型
	CorrelationType pgtype.Text `json:"correlation_type"`
	// 原始事实 ID 或命令 ID
	CorrelationID pgtype.Text `json:"correlation_id"`
	// 脱敏后的事件扩展数据
	Payload []byte `json:"payload"`
	// Runtime 管理面事件创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Runtime 管理面事件最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Runtime Agent 节点注册表
type RuntimeNode struct {
	// Runtime 节点主键 UUID
	ID uuid.UUID `json:"id"`
	// 默认所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// Runtime 外部业务节点 ID
	NodeID string `json:"node_id"`
	// Runtime 节点名称
	Name string `json:"name"`
	// Runtime 支持的 Provider 列表
	SupportedProviders []byte `json:"supported_providers"`
	// Runtime 最大并发槽位数
	MaxSlots int32 `json:"max_slots"`
	// Runtime 当前负载
	CurrentLoad int32 `json:"current_load"`
	// Runtime 节点状态
	Status string `json:"status"`
	// Runtime 节点扩展元数据
	Metadata []byte `json:"metadata"`
	// Runtime 最后心跳时间
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	// Runtime 节点禁用时间
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	// Runtime 节点归档时间
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	// Runtime 节点注册时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Runtime 节点最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Runtime 节点可执行范围表
type RuntimeNodeScope struct {
	// 节点范围主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// Runtime 节点 ID
	RuntimeNodeID uuid.UUID `json:"runtime_node_id"`
	// 授权团队 ID
	TeamID uuid.NullUUID `json:"team_id"`
	// 范围类型
	ScopeType string `json:"scope_type"`
	// 范围值
	ScopeValue string `json:"scope_value"`
	// 范围状态
	Status string `json:"status"`
	// 范围禁用时间
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	// 范围创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 范围最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Runtime Agent 短期会话表
type RuntimeSession struct {
	// Runtime 会话主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// Runtime 节点 UUID
	RuntimeNodeID uuid.UUID `json:"runtime_node_id"`
	// 关联的 Runtime 接入记录 ID
	EnrollmentID uuid.NullUUID `json:"enrollment_id"`
	// 短期 Runtime 会话 token 的确定性查找哈希
	TokenLookupHash string `json:"token_lookup_hash"`
	// 短期 Runtime 会话 token 的安全校验哈希
	TokenSecretHash string `json:"token_secret_hash"`
	// 短期 Runtime 会话过期时间
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// Runtime 会话最近访问时间
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	// Runtime 会话撤销时间
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	// Runtime 会话撤销原因
	RevokedReason pgtype.Text `json:"revoked_reason"`
	// Runtime 会话创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Runtime 会话最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 租户级场景模板注册表，驱动规划分解与交接契约实例化
type ScenarioTemplate struct {
	// 场景模板主键 UUID
	ID uuid.UUID `json:"id"`
	// 场景模板所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 模板稳定标识（如 software_delivery），租户内未删除时唯一
	TemplateKey string `json:"template_key"`
	// 模板显示名
	Name string `json:"name"`
	// 模板适用场景说明
	Description string `json:"description"`
	// 模板内容：roles/skeleton/default_acceptance_criteria/risk_policy/feasibility_thresholds
	Spec []byte `json:"spec"`
	// 模板状态：active/disabled
	Status string `json:"status"`
	// 模板软删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// 创建模板的用户 ID
	CreatedBy uuid.NullUUID `json:"created_by"`
	// 模板创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 模板更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 当前生效版本号，主表 spec 始终镜像该版本内容
	ActiveVersion int32 `json:"active_version"`
}

// 场景模板 spec 的不可变版本历史，供审计血缘与计划钉住
type ScenarioTemplateVersion struct {
	// 版本记录主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属场景模板 ID
	TemplateID uuid.UUID `json:"template_id"`
	// 版本号，从 1 单调递增
	Version int32 `json:"version"`
	// 该版本的完整模板 spec JSONB
	Spec []byte `json:"spec"`
	// 创建该版本的用户 ID，迁移生成为 NULL
	CreatedBy uuid.NullUUID `json:"created_by"`
	// 版本创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 技能包主表，记录可上传、安装和绑定到数字员工的技能定义
type Skill struct {
	// 技能主键 UUID
	ID uuid.UUID `json:"id"`
	// 技能所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 租户内技能稳定标识，由上传名称规范化生成
	Slug string `json:"slug"`
	// 技能显示名称
	Name string `json:"name"`
	// 技能描述，由上传表单或 SKILL.md 摘要提供
	Description string `json:"description"`
	// 技能版本，来自上传包元数据或默认版本
	Version string `json:"version"`
	// 技能来源，例如 upload、internal_market 或 marketplace
	Source string `json:"source"`
	// 技能风险等级，由服务端和上传表单校验
	RiskLevel string `json:"risk_level"`
	// 技能市场彩色图标键，前端映射到图标库
	IconKey string `json:"icon_key"`
	// 技能图标语义色标识
	ColorToken string `json:"color_token"`
	// 上传定义的技能标签数组，技能市场展示只使用此字段
	Tags []string `json:"tags"`
	// 技能扩展元数据 JSON
	Metadata []byte `json:"metadata"`
	// 上传或创建技能的用户 ID
	CreatedBy uuid.NullUUID `json:"created_by"`
	// 技能软删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// 技能创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 技能更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 技能 zip 包在对象存储的 URI，例如 s3://bucket/skills/.../xxx.zip
	ArchiveObjectRef pgtype.Text `json:"archive_object_ref"`
	// 上传时原始 zip 文件名
	ArchiveFilename pgtype.Text `json:"archive_filename"`
	// zip 包字节数
	ArchiveSizeBytes int64 `json:"archive_size_bytes"`
	// zip 包 SHA256 校验值，用于 Runtime 下发完整性校验
	ArchiveChecksumSha256 string `json:"archive_checksum_sha256"`
	// zip 包内文件总数
	ArchiveFileCount int32 `json:"archive_file_count"`
}

// 技能安装到数字员工的绑定表
type SkillAgentBinding struct {
	// 技能数字员工绑定主键 UUID
	ID uuid.UUID `json:"id"`
	// 绑定所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 绑定的技能 ID
	SkillID uuid.UUID `json:"skill_id"`
	// 安装该技能的数字员工 ID
	DigitalEmployeeID uuid.UUID `json:"digital_employee_id"`
	// 安装状态，例如 enabled 或 disabled
	Status string `json:"status"`
	// 安装关系扩展元数据 JSON
	Metadata []byte `json:"metadata"`
	// 安装关系创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 安装关系更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 技能物理安装记录，只保存已成功写入数字员工 workspace 的安装事实
type SkillInstallation struct {
	// 技能物理安装记录 ID
	ID uuid.UUID `json:"id"`
	// 安装记录所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 被安装的技能包 ID
	SkillID uuid.UUID `json:"skill_id"`
	// 安装请求目标范围，team 表示团队批量安装，employee 表示单个数字员工安装
	TargetScope string `json:"target_scope"`
	// 团队批量安装来源团队 ID，单员工安装时可为空
	TeamID uuid.NullUUID `json:"team_id"`
	// 实际写入技能目录的数字员工 ID
	DigitalEmployeeID uuid.UUID `json:"digital_employee_id"`
	// 执行本次物理安装的 Runtime 节点 ID
	RuntimeNodeID uuid.UUID `json:"runtime_node_id"`
	// Provider 类型，由服务端注册表和安装前置校验控制
	ProviderType string `json:"provider_type"`
	// Runtime Agent 实际写入的 provider 官方技能目录
	InstalledPath string `json:"installed_path"`
	// 安装时使用的技能 zip 包 SHA256 校验值
	ArchiveChecksumSha256 string `json:"archive_checksum_sha256"`
	// 安装事实状态；此表只保存 installed 成功记录
	Status string `json:"status"`
	// 触发安装的人类用户 ID 或系统操作者 ID
	InstalledBy uuid.NullUUID `json:"installed_by"`
	// Runtime 确认物理安装成功的时间
	InstalledAt pgtype.Timestamptz `json:"installed_at"`
	// 安装命令、Runtime 回执和排障扩展信息
	Metadata []byte `json:"metadata"`
	// 安装记录创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 安装记录最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 安装记录软删除时间；为空表示当前有效
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// 任务主表
type Task struct {
	// 任务主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属团队 ID
	TeamID uuid.NullUUID `json:"team_id"`
	// 任务标题
	Title string `json:"title"`
	// 任务描述
	Description pgtype.Text `json:"description"`
	// 任务创建用户 ID
	CreatorID uuid.NullUUID `json:"creator_id"`
	// 任务目标 Provider 类型
	ProviderType string `json:"provider_type"`
	// 指定 Runtime 外部业务节点 ID
	TargetNodeID pgtype.Text `json:"target_node_id"`
	// 已分配 Runtime 外部业务节点 ID
	AssignedNodeID pgtype.Text `json:"assigned_node_id"`
	// 任务状态
	Status string `json:"status"`
	// 任务工作目录路径
	WorkspacePath pgtype.Text `json:"workspace_path"`
	// 任务参数
	Params []byte `json:"params"`
	// 任务优先级
	Priority int32 `json:"priority"`
	// 任务幂等键
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	// 任务风险级别
	RiskLevel string `json:"risk_level"`
	// 任务取消时间
	CancelledAt pgtype.Timestamptz `json:"cancelled_at"`
	// 任务软删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// 任务创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 任务最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// run 归类:task=任务执行,chat=数字员工单次对话。纯分类标签,不改变执行语义。
	RunKind string `json:"run_kind"`
	// chat 追问血缘:指向上一个 chat run(task_runs.id),仅审计用,无 FK。
	ResumeOfRunID uuid.NullUUID `json:"resume_of_run_id"`
}

// 任务工件表
type TaskArtifact struct {
	// 任务工件主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属任务 ID
	TaskID uuid.UUID `json:"task_id"`
	// 所属任务运行 ID
	RunID uuid.NullUUID `json:"run_id"`
	// 工件类型
	ArtifactType string `json:"artifact_type"`
	// 工件名称
	Name string `json:"name"`
	// 工件存储地址
	StorageUrl string `json:"storage_url"`
	// 工件大小字节数
	SizeBytes pgtype.Int8 `json:"size_bytes"`
	// 工件扩展元数据
	Metadata []byte `json:"metadata"`
	// 工件归档时间
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	// 工件软删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// 工件创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 任务事件流表
type TaskEvent struct {
	// 任务事件主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属任务 ID
	TaskID uuid.UUID `json:"task_id"`
	// 所属任务运行 ID
	RunID uuid.NullUUID `json:"run_id"`
	// 任务事件类型
	EventType string `json:"event_type"`
	// 任务内事件序号
	SequenceNumber int32 `json:"sequence_number"`
	// 任务事件负载
	Payload []byte `json:"payload"`
	// 任务事件创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 事件关联的Runtime命令ID
	CommandID pgtype.Text `json:"command_id"`
	// 原始事件对象引用
	RawEventRef pgtype.Text `json:"raw_event_ref"`
	// 事件日志对象引用
	LogRef pgtype.Text `json:"log_ref"`
	// 任务事件扩展元数据
	Metadata []byte `json:"metadata"`
}

type TaskPromptTemplate struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	Title        string             `json:"title"`
	Content      string             `json:"content"`
	CategoryCode string             `json:"category_code"`
	Scope        string             `json:"scope"`
	TeamID       uuid.NullUUID      `json:"team_id"`
	CreatorID    uuid.UUID          `json:"creator_id"`
	Variables    []byte             `json:"variables"`
	UseCount     int32              `json:"use_count"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// 任务运行记录表
type TaskRun struct {
	// 任务运行主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属任务 ID
	TaskID uuid.UUID `json:"task_id"`
	// 执行 Runtime 外部业务节点 ID
	NodeID string `json:"node_id"`
	// 执行 Runtime 节点 UUID
	RuntimeNodeID uuid.NullUUID `json:"runtime_node_id"`
	// Provider 会话 ID
	ProviderSessionID pgtype.Text `json:"provider_session_id"`
	// 任务运行状态
	Status string `json:"status"`
	// 任务运行租约过期时间
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	// 任务运行开始时间
	StartedAt pgtype.Timestamptz `json:"started_at"`
	// 任务运行完成时间
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	// 任务运行终止时间，包含完成、失败或取消
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	// 任务运行结果
	Result []byte `json:"result"`
	// 任务运行错误信息
	ErrorMessage pgtype.Text `json:"error_message"`
	// 任务运行创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 任务运行最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 运行关联的Runtime命令ID
	CommandID pgtype.Text `json:"command_id"`
	// 运行所属数字员工ID
	DigitalEmployeeID uuid.NullUUID `json:"digital_employee_id"`
	// 运行使用的执行实例ID
	ExecutionInstanceID uuid.NullUUID `json:"execution_instance_id"`
	// 运行创建幂等键
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	// 运行创建幂等指纹
	IdempotencyFingerprint pgtype.Text `json:"idempotency_fingerprint"`
	// 运行超时时间秒数
	TimeoutSec pgtype.Int4 `json:"timeout_sec"`
	// 停止宽限时间秒数
	GraceSec pgtype.Int4 `json:"grace_sec"`
	// 运行诊断信息
	Diagnostic []byte `json:"diagnostic"`
	// 运行日志对象引用
	LogRef pgtype.Text `json:"log_ref"`
	// 原始结果对象引用
	RawResultRef pgtype.Text `json:"raw_result_ref"`
	// 结构化工作产物列表
	WorkProducts []byte `json:"work_products"`
	// Provider会话状态快照
	SessionState []byte `json:"session_state"`
	// 运行错误码
	ErrorCode pgtype.Text `json:"error_code"`
	// 运行错误分类
	ErrorFamily pgtype.Text `json:"error_family"`
	// Provider进程退出码
	ExitCode pgtype.Int4 `json:"exit_code"`
	// Provider进程退出信号
	Signal pgtype.Text `json:"signal"`
	// 运行是否因超时终止
	TimedOut bool `json:"timed_out"`
	// 运行使用的Provider类型
	ProviderType pgtype.Text `json:"provider_type"`
	// Provider外部会话ID
	ProviderSessionExternalID pgtype.Text `json:"provider_session_external_id"`
}

// 任务状态变更历史表
type TaskStateHistory struct {
	// 状态历史主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属任务 ID
	TaskID uuid.UUID `json:"task_id"`
	// 变更前任务状态
	FromStatus pgtype.Text `json:"from_status"`
	// 变更后任务状态
	ToStatus string `json:"to_status"`
	// 状态变更触发者
	ChangedBy pgtype.Text `json:"changed_by"`
	// 状态变更原因
	Reason pgtype.Text `json:"reason"`
	// 状态变更记录时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 团队借调策略：团队负责人设置本团队员工是否/在什么条件下可被项目借调（每团队一条 active）
type TeamLendingPolicy struct {
	// 借调策略 UUID
	ID uuid.UUID `json:"id"`
	// 租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属团队 ID（供给侧）
	TeamID uuid.UUID `json:"team_id"`
	// 是否允许本团队员工被项目借调
	AllowLending bool `json:"allow_lending"`
	// 审批模式：auto 符合策略自动放行；manual 每次借调需团队负责人审批
	ApprovalMode string `json:"approval_mode"`
	// 单次借调预算上限；请求超过则强制转人工审批
	BudgetCeiling pgtype.Numeric `json:"budget_ceiling"`
	// 可被借调时允许的能力/runtime scope 天花板，不可超出团队治理外壳
	CapabilityCeiling []byte `json:"capability_ceiling"`
	// 可被哪些项目调用的匹配条件（标签 / owner 范围等，registry-first）
	ProjectMatch []byte `json:"project_match"`
	// 策略状态：active 生效，archived 历史版本
	Status string `json:"status"`
	// 创建该策略的用户 ID
	CreatedByUserID uuid.NullUUID `json:"created_by_user_id"`
	// 最后更新该策略的用户 ID
	UpdatedByUserID uuid.NullUUID `json:"updated_by_user_id"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 团队借调请求：项目向团队申请借调数字员工，团队负责人裁决（D1 团队级 (project, team) 授权）
type TeamLendingRequest struct {
	// 借调请求 UUID
	ID uuid.UUID `json:"id"`
	// 租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 被借调的团队 ID（供给侧）
	TeamID uuid.UUID `json:"team_id"`
	// 发起借调的项目 ID（需求侧）
	ProjectID uuid.UUID `json:"project_id"`
	// 请求状态：pending 待审批，auto_approved 策略自动放行，approved 人工通过，rejected 驳回，revoked 撤销
	Status string `json:"status"`
	// 发起借调的用户 ID（项目负责人）
	RequestedByUserID uuid.UUID `json:"requested_by_user_id"`
	// 借调事由
	RequestReason string `json:"request_reason"`
	// 申请的借调预算
	RequestedBudget pgtype.Numeric `json:"requested_budget"`
	// 申请使用的能力范围
	RequestedCapability []byte `json:"requested_capability"`
	// 实际授予的借调预算（≤ 策略天花板）
	GrantedBudget pgtype.Numeric `json:"granted_budget"`
	// 实际授予的能力范围（≤ 策略天花板）
	GrantedCapability []byte `json:"granted_capability"`
	// 是否因超出策略预算/能力天花板而强制转人工审批
	IsException bool `json:"is_exception"`
	// 裁决该请求的团队负责人用户 ID
	DecidedByUserID uuid.NullUUID `json:"decided_by_user_id"`
	// 裁决时间
	DecidedAt pgtype.Timestamptz `json:"decided_at"`
	// 裁决说明
	DecisionReason string `json:"decision_reason"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 团队对注册表 MCP 的绑定，团队下数字员工继承
type TeamMcpBinding struct {
	// 团队 MCP 绑定主键 UUID
	ID uuid.UUID `json:"id"`
	// 绑定所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 绑定所属团队 ID
	TeamID uuid.UUID `json:"team_id"`
	// 引用的注册表 MCP 定义 ID
	McpServerID uuid.UUID `json:"mcp_server_id"`
	// 该绑定使用的凭据环境变量名，值由数字员工环境变量提供
	CredentialEnvVar pgtype.Text `json:"credential_env_var"`
	// 绑定状态，例如 active 或 disabled
	Status string `json:"status"`
	// 绑定扩展元数据 JSON
	Metadata []byte `json:"metadata"`
	// 绑定禁用时间
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	// 绑定软删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// 创建绑定的用户 ID
	CreatedBy uuid.NullUUID `json:"created_by"`
	// 绑定创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 绑定更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 团队公共 MCP 服务器配置，团队下数字员工强制继承
type TeamMcpServer struct {
	// 团队 MCP 配置主键 UUID
	ID uuid.UUID `json:"id"`
	// 团队 MCP 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 团队 MCP 所属团队 ID
	TeamID uuid.UUID `json:"team_id"`
	// 团队 MCP 显示名称，同一团队下未删除时唯一
	Name string `json:"name"`
	// 团队 MCP 远程 HTTP 地址
	Url string `json:"url"`
	// 引用的个人凭据 ID，由应用层校验归属和类型
	CredentialID uuid.NullUUID `json:"credential_id"`
	// 团队 MCP 状态，例如 active 或 disabled
	Status string `json:"status"`
	// 团队 MCP 扩展元数据 JSON
	Metadata []byte `json:"metadata"`
	// 团队 MCP 禁用时间
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	// 团队 MCP 软删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// 创建团队 MCP 的用户 ID
	CreatedBy uuid.NullUUID `json:"created_by"`
	// 团队 MCP 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 团队 MCP 更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 技能与团队归属绑定表
type TeamSkillBinding struct {
	// 技能团队绑定主键 UUID
	ID uuid.UUID `json:"id"`
	// 绑定所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 绑定的技能 ID
	SkillID uuid.UUID `json:"skill_id"`
	// 归属团队 ID
	TeamID uuid.UUID `json:"team_id"`
	// 绑定创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 租户表
type Tenant struct {
	// 租户主键 UUID
	ID uuid.UUID `json:"id"`
	// 租户唯一标识
	Slug string `json:"slug"`
	// 租户名称
	Name string `json:"name"`
	// 租户状态
	Status string `json:"status"`
	// 租户扩展元数据
	Metadata []byte `json:"metadata"`
	// 租户归档时间
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	// 租户禁用时间
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	// 租户软删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// 租户创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 租户最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 租户成员关系表
type TenantMember struct {
	// 成员关系主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 所属团队 ID，可为空表示租户级成员
	TeamID uuid.NullUUID `json:"team_id"`
	// 成员主体类型
	PrincipalType string `json:"principal_type"`
	// 成员主体 ID
	PrincipalID uuid.UUID `json:"principal_id"`
	// 成员角色
	Role string `json:"role"`
	// 成员关系状态
	Status string `json:"status"`
	// 成员关系禁用时间
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	// 成员关系创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 成员关系最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 租户配置画像表
type TenantProfile struct {
	// 租户配置主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 配置键
	ProfileKey string `json:"profile_key"`
	// 配置值
	ProfileValue []byte `json:"profile_value"`
	// 配置创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 配置最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 租户团队表
type TenantTeam struct {
	// 团队主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 团队唯一标识
	Slug string `json:"slug"`
	// 团队名称
	Name string `json:"name"`
	// 团队状态
	Status string `json:"status"`
	// 团队扩展元数据
	Metadata []byte `json:"metadata"`
	// 团队归档时间
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	// 团队禁用时间
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	// 团队软删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// 团队创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 团队最后更新时间
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	HumanOwnerUserIds []uuid.UUID        `json:"human_owner_user_ids"`
	Constitution      []byte             `json:"constitution"`
}

// 团队高权限角色变更申请表
type TenantTeamMemberRoleRequest struct {
	// 角色变更申请ID
	ID uuid.UUID `json:"id"`
	// 租户ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 团队ID
	TeamID uuid.UUID `json:"team_id"`
	// 目标用户ID
	TargetUserID uuid.UUID `json:"target_user_id"`
	// 申请授予的团队角色
	RequestedRole string `json:"requested_role"`
	// 申请人用户ID
	RequestedBy uuid.UUID `json:"requested_by"`
	// 申请状态：pending、approved、rejected
	Status string `json:"status"`
	// 申请原因
	Reason string `json:"reason"`
	// 审批人用户ID
	DecidedBy uuid.NullUUID `json:"decided_by"`
	// 审批时间
	DecidedAt pgtype.Timestamptz `json:"decided_at"`
	// 审批说明
	DecisionReason string `json:"decision_reason"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 个人凭据池，保存用户可复用的外部能力授权令牌密文
type UserCredential struct {
	// 个人凭据主键 UUID
	ID uuid.UUID `json:"id"`
	// 凭据所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 凭据所属用户 ID
	UserID uuid.UUID `json:"user_id"`
	// 凭据显示名称，同一用户下未删除时唯一
	Name string `json:"name"`
	// 凭据类型，例如 mcp_token，由服务端注册表校验
	CredentialType string `json:"credential_type"`
	// 服务端封存后的凭据密文，API 永不返回明文
	EncryptedValue string `json:"encrypted_value"`
	// 凭据明文末尾四位或更短尾标，用于用户识别
	LastFour string `json:"last_four"`
	// 凭据状态，例如 active 或 disabled
	Status string `json:"status"`
	// 凭据扩展元数据 JSON
	Metadata []byte `json:"metadata"`
	// 凭据禁用时间
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	// 凭据软删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// 凭据创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 凭据更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 人类用户创建项目时可选择的团队授权范围
type UserProjectTeamScope struct {
	// 授权记录 UUID
	ID uuid.UUID `json:"id"`
	// 租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 被授权的人类用户 ID
	UserID uuid.UUID `json:"user_id"`
	// 用户创建项目时可选择的团队 ID
	TeamID uuid.UUID `json:"team_id"`
	// 授权状态：active 表示可用，revoked 表示已撤销
	Status string `json:"status"`
	// 授予或最后替换该授权范围的管理员用户 ID
	GrantedByUserID uuid.NullUUID `json:"granted_by_user_id"`
	// 授权撤销时间
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	// 授权创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 授权最后更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Web 控制台登录日志表
type WebLoginLog struct {
	// 登录日志主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 登录事件类型
	EventType string `json:"event_type"`
	// 登录用户 ID，失败登录可为空
	UserID uuid.NullUUID `json:"user_id"`
	// 登录账号快照
	Username string `json:"username"`
	// 登录会话 ID
	SessionID uuid.NullUUID `json:"session_id"`
	// 客户端 IP
	ClientIp pgtype.Text `json:"client_ip"`
	// 客户端 User-Agent
	UserAgent pgtype.Text `json:"user_agent"`
	// 登录结果：succeeded 或 failed
	Result string `json:"result"`
	// 登录失败原因
	FailureReason pgtype.Text `json:"failure_reason"`
	// 登录上下文扩展信息
	Details []byte `json:"details"`
	// 登录事件发生时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Web 控制台操作日志表
type WebOperationLog struct {
	// 操作日志主键 UUID
	ID uuid.UUID `json:"id"`
	// 所属租户 ID
	TenantID uuid.UUID `json:"tenant_id"`
	// 执行操作的用户 ID，用户删除后保留日志
	UserID uuid.NullUUID `json:"user_id"`
	// 执行操作的用户账号快照
	Username pgtype.Text `json:"username"`
	// 操作所属模块
	Module string `json:"module"`
	// 被操作资源类型
	ResourceType pgtype.Text `json:"resource_type"`
	// 被操作资源 ID
	ResourceID pgtype.Text `json:"resource_id"`
	// 操作动作
	Action string `json:"action"`
	// 操作结果：succeeded 或 failed
	Result string `json:"result"`
	// 请求 ID，便于链路追踪
	RequestID pgtype.Text `json:"request_id"`
	// 客户端 IP
	ClientIp pgtype.Text `json:"client_ip"`
	// 客户端 User-Agent
	UserAgent pgtype.Text `json:"user_agent"`
	// 操作上下文扩展信息
	Details []byte `json:"details"`
	// 操作发生时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
