// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_runtime_affinity.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateProjectTaskAttestation = `-- name: CreateProjectTaskAttestation :one
INSERT INTO project_task_attestations (
    tenant_id,
    project_id,
    project_task_id,
    attempt_id,
    runtime_node_id,
    provider_session_id,
    attestation_type,
    status,
    command_argv,
    exit_code,
    duration_ms,
    log_ref,
    stdout_sha256,
    stderr_sha256,
    artifact_refs,
    artifact_hashes,
    git_branch,
    git_base_ref,
    git_head_sha,
    git_diff_sha256,
    metadata,
    idempotency_key
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::uuid,
    $5::uuid,
    $6::varchar,
    $7::varchar,
    $8::varchar,
    COALESCE($9::jsonb, '[]'::jsonb),
    $10::integer,
    $11::bigint,
    $12::text,
    $13::varchar,
    $14::varchar,
    COALESCE($15::jsonb, '[]'::jsonb),
    COALESCE($16::jsonb, '{}'::jsonb),
    $17::varchar,
    $18::varchar,
    $19::varchar,
    $20::varchar,
    COALESCE($21::jsonb, '{}'::jsonb),
    $22::varchar
)
ON CONFLICT (tenant_id, attempt_id, idempotency_key) DO UPDATE SET
    idempotency_key = EXCLUDED.idempotency_key
RETURNING id, tenant_id, project_id, project_task_id, attempt_id, runtime_node_id, provider_session_id, attestation_type, status, command_argv, exit_code, duration_ms, log_ref, stdout_sha256, stderr_sha256, artifact_refs, artifact_hashes, git_branch, git_base_ref, git_head_sha, git_diff_sha256, metadata, idempotency_key, created_at, updated_at
`

type CreateProjectTaskAttestationParams struct {
	TenantID          uuid.UUID   `json:"tenant_id"`
	ProjectID         uuid.UUID   `json:"project_id"`
	ProjectTaskID     uuid.UUID   `json:"project_task_id"`
	AttemptID         uuid.UUID   `json:"attempt_id"`
	RuntimeNodeID     uuid.UUID   `json:"runtime_node_id"`
	ProviderSessionID pgtype.Text `json:"provider_session_id"`
	AttestationType   string      `json:"attestation_type"`
	Status            string      `json:"status"`
	CommandArgv       []byte      `json:"command_argv"`
	ExitCode          pgtype.Int4 `json:"exit_code"`
	DurationMs        pgtype.Int8 `json:"duration_ms"`
	LogRef            pgtype.Text `json:"log_ref"`
	StdoutSha256      pgtype.Text `json:"stdout_sha256"`
	StderrSha256      pgtype.Text `json:"stderr_sha256"`
	ArtifactRefs      []byte      `json:"artifact_refs"`
	ArtifactHashes    []byte      `json:"artifact_hashes"`
	GitBranch         pgtype.Text `json:"git_branch"`
	GitBaseRef        pgtype.Text `json:"git_base_ref"`
	GitHeadSha        pgtype.Text `json:"git_head_sha"`
	GitDiffSha256     pgtype.Text `json:"git_diff_sha256"`
	Metadata          []byte      `json:"metadata"`
	IdempotencyKey    string      `json:"idempotency_key"`
}

func (q *Queries) CreateProjectTaskAttestation(ctx context.Context, arg CreateProjectTaskAttestationParams) (ProjectTaskAttestation, error) {
	row := q.db.QueryRow(ctx, CreateProjectTaskAttestation,
		arg.TenantID,
		arg.ProjectID,
		arg.ProjectTaskID,
		arg.AttemptID,
		arg.RuntimeNodeID,
		arg.ProviderSessionID,
		arg.AttestationType,
		arg.Status,
		arg.CommandArgv,
		arg.ExitCode,
		arg.DurationMs,
		arg.LogRef,
		arg.StdoutSha256,
		arg.StderrSha256,
		arg.ArtifactRefs,
		arg.ArtifactHashes,
		arg.GitBranch,
		arg.GitBaseRef,
		arg.GitHeadSha,
		arg.GitDiffSha256,
		arg.Metadata,
		arg.IdempotencyKey,
	)
	var i ProjectTaskAttestation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.ProjectTaskID,
		&i.AttemptID,
		&i.RuntimeNodeID,
		&i.ProviderSessionID,
		&i.AttestationType,
		&i.Status,
		&i.CommandArgv,
		&i.ExitCode,
		&i.DurationMs,
		&i.LogRef,
		&i.StdoutSha256,
		&i.StderrSha256,
		&i.ArtifactRefs,
		&i.ArtifactHashes,
		&i.GitBranch,
		&i.GitBaseRef,
		&i.GitHeadSha,
		&i.GitDiffSha256,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetActiveProjectPlacement = `-- name: GetActiveProjectPlacement :one
SELECT id, tenant_id, project_id, runtime_node_id, placement_status, placement_reason, assigned_at, released_at, created_at, updated_at
FROM project_placements
WHERE tenant_id = $1::uuid
  AND project_id = $2::uuid
  AND placement_status = 'active'
`

type GetActiveProjectPlacementParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetActiveProjectPlacement(ctx context.Context, arg GetActiveProjectPlacementParams) (ProjectPlacement, error) {
	row := q.db.QueryRow(ctx, GetActiveProjectPlacement, arg.TenantID, arg.ProjectID)
	var i ProjectPlacement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.RuntimeNodeID,
		&i.PlacementStatus,
		&i.PlacementReason,
		&i.AssignedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetProjectRepoBinding = `-- name: GetProjectRepoBinding :one
SELECT
    id,
    tenant_id,
    repo_url,
    repo_default_branch,
    repo_git_credential_ref,
    repo_scope,
    repo_binding_status
FROM projects
WHERE tenant_id = $1::uuid
  AND id = $2::uuid
`

type GetProjectRepoBindingParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

type GetProjectRepoBindingRow struct {
	ID                   uuid.UUID   `json:"id"`
	TenantID             uuid.UUID   `json:"tenant_id"`
	RepoUrl              pgtype.Text `json:"repo_url"`
	RepoDefaultBranch    pgtype.Text `json:"repo_default_branch"`
	RepoGitCredentialRef pgtype.Text `json:"repo_git_credential_ref"`
	RepoScope            []byte      `json:"repo_scope"`
	RepoBindingStatus    string      `json:"repo_binding_status"`
}

func (q *Queries) GetProjectRepoBinding(ctx context.Context, arg GetProjectRepoBindingParams) (GetProjectRepoBindingRow, error) {
	row := q.db.QueryRow(ctx, GetProjectRepoBinding, arg.TenantID, arg.ProjectID)
	var i GetProjectRepoBindingRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RepoUrl,
		&i.RepoDefaultBranch,
		&i.RepoGitCredentialRef,
		&i.RepoScope,
		&i.RepoBindingStatus,
	)
	return i, err
}

const ListProjectTaskAttestations = `-- name: ListProjectTaskAttestations :many
SELECT id, tenant_id, project_id, project_task_id, attempt_id, runtime_node_id, provider_session_id, attestation_type, status, command_argv, exit_code, duration_ms, log_ref, stdout_sha256, stderr_sha256, artifact_refs, artifact_hashes, git_branch, git_base_ref, git_head_sha, git_diff_sha256, metadata, idempotency_key, created_at, updated_at
FROM project_task_attestations
WHERE tenant_id = $1::uuid
  AND project_id = $2::uuid
  AND project_task_id = $3::uuid
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListProjectTaskAttestationsParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	ProjectID     uuid.UUID `json:"project_id"`
	ProjectTaskID uuid.UUID `json:"project_task_id"`
	Offset        int32     `json:"offset"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListProjectTaskAttestations(ctx context.Context, arg ListProjectTaskAttestationsParams) ([]ProjectTaskAttestation, error) {
	rows, err := q.db.Query(ctx, ListProjectTaskAttestations,
		arg.TenantID,
		arg.ProjectID,
		arg.ProjectTaskID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectTaskAttestation{}
	for rows.Next() {
		var i ProjectTaskAttestation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.ProjectTaskID,
			&i.AttemptID,
			&i.RuntimeNodeID,
			&i.ProviderSessionID,
			&i.AttestationType,
			&i.Status,
			&i.CommandArgv,
			&i.ExitCode,
			&i.DurationMs,
			&i.LogRef,
			&i.StdoutSha256,
			&i.StderrSha256,
			&i.ArtifactRefs,
			&i.ArtifactHashes,
			&i.GitBranch,
			&i.GitBaseRef,
			&i.GitHeadSha,
			&i.GitDiffSha256,
			&i.Metadata,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateProjectTaskAttemptBudgetHeartbeat = `-- name: UpdateProjectTaskAttemptBudgetHeartbeat :one
UPDATE project_task_attempts
SET
    budget_last_heartbeat_at = NOW(),
    budget_consumed_wall_clock_sec = $1::integer,
    budget_consumed_tokens = $2::integer,
    budget_tripped_at = CASE
        WHEN $3::varchar IS NULL THEN budget_tripped_at
        ELSE NOW()
    END,
    budget_trip_reason = COALESCE($3::varchar, budget_trip_reason)
WHERE tenant_id = $4::uuid
  AND project_task_id = $5::uuid
  AND id = $6::uuid
RETURNING id, tenant_id, project_task_id, attempt_no, status, digital_employee_run_id, runtime_task_id, runtime_node_id, provider_session_id, execution_context_packet, execution_context_packet_version, lease_token, lease_expires_at, renewed_at, lost_at, started_at, finished_at, timeout_at, retryable, failure_family, failure_message, idempotency_key, created_event_id, terminal_event_id, created_at, updated_at, dispatch_gate_result_id, budget_wall_clock_limit_sec, budget_last_heartbeat_at, budget_consumed_wall_clock_sec, budget_consumed_tokens, budget_tripped_at, budget_trip_reason
`

type UpdateProjectTaskAttemptBudgetHeartbeatParams struct {
	ConsumedWallClockSec int32       `json:"consumed_wall_clock_sec"`
	ConsumedTokens       int32       `json:"consumed_tokens"`
	TripReason           pgtype.Text `json:"trip_reason"`
	TenantID             uuid.UUID   `json:"tenant_id"`
	ProjectTaskID        uuid.UUID   `json:"project_task_id"`
	AttemptID            uuid.UUID   `json:"attempt_id"`
}

func (q *Queries) UpdateProjectTaskAttemptBudgetHeartbeat(ctx context.Context, arg UpdateProjectTaskAttemptBudgetHeartbeatParams) (ProjectTaskAttempt, error) {
	row := q.db.QueryRow(ctx, UpdateProjectTaskAttemptBudgetHeartbeat,
		arg.ConsumedWallClockSec,
		arg.ConsumedTokens,
		arg.TripReason,
		arg.TenantID,
		arg.ProjectTaskID,
		arg.AttemptID,
	)
	var i ProjectTaskAttempt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectTaskID,
		&i.AttemptNo,
		&i.Status,
		&i.DigitalEmployeeRunID,
		&i.RuntimeTaskID,
		&i.RuntimeNodeID,
		&i.ProviderSessionID,
		&i.ExecutionContextPacket,
		&i.ExecutionContextPacketVersion,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.RenewedAt,
		&i.LostAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TimeoutAt,
		&i.Retryable,
		&i.FailureFamily,
		&i.FailureMessage,
		&i.IdempotencyKey,
		&i.CreatedEventID,
		&i.TerminalEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DispatchGateResultID,
		&i.BudgetWallClockLimitSec,
		&i.BudgetLastHeartbeatAt,
		&i.BudgetConsumedWallClockSec,
		&i.BudgetConsumedTokens,
		&i.BudgetTrippedAt,
		&i.BudgetTripReason,
	)
	return i, err
}

const UpsertProjectPlacement = `-- name: UpsertProjectPlacement :one
INSERT INTO project_placements (
    tenant_id,
    project_id,
    runtime_node_id,
    placement_status,
    placement_reason
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    'active',
    $4::varchar
)
ON CONFLICT (tenant_id, project_id) WHERE placement_status = 'active'
DO UPDATE SET
    runtime_node_id = EXCLUDED.runtime_node_id,
    placement_reason = EXCLUDED.placement_reason,
    assigned_at = NOW(),
    updated_at = NOW()
RETURNING id, tenant_id, project_id, runtime_node_id, placement_status, placement_reason, assigned_at, released_at, created_at, updated_at
`

type UpsertProjectPlacementParams struct {
	TenantID        uuid.UUID   `json:"tenant_id"`
	ProjectID       uuid.UUID   `json:"project_id"`
	RuntimeNodeID   uuid.UUID   `json:"runtime_node_id"`
	PlacementReason pgtype.Text `json:"placement_reason"`
}

func (q *Queries) UpsertProjectPlacement(ctx context.Context, arg UpsertProjectPlacementParams) (ProjectPlacement, error) {
	row := q.db.QueryRow(ctx, UpsertProjectPlacement,
		arg.TenantID,
		arg.ProjectID,
		arg.RuntimeNodeID,
		arg.PlacementReason,
	)
	var i ProjectPlacement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.RuntimeNodeID,
		&i.PlacementStatus,
		&i.PlacementReason,
		&i.AssignedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
