// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: provider_session.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateProviderSession = `-- name: CreateProviderSession :one
INSERT INTO provider_sessions (
    tenant_id,
    provider_session_id,
    digital_employee_id,
    execution_instance_id,
    runtime_node_id,
    provider_type,
    status,
    recoverable,
    last_active_at,
    metadata
) SELECT
    dei.tenant_id,
    $1::varchar,
    dei.digital_employee_id,
    dei.id,
    dei.runtime_node_id,
    dei.provider_type,
    $2::varchar,
    $3::boolean,
    $4::timestamptz,
    COALESCE($5::jsonb, '{}'::jsonb)
FROM digital_employee_execution_instances dei
JOIN digital_employees de
  ON de.id = dei.digital_employee_id
 AND de.tenant_id = dei.tenant_id
 AND de.status NOT IN ('disabled', 'error')
 AND de.deleted_at IS NULL
 AND de.archived_at IS NULL
JOIN runtime_nodes rn
  ON rn.id = dei.runtime_node_id
 AND rn.tenant_id = dei.tenant_id
 AND rn.status = 'online'
 AND rn.disabled_at IS NULL
 AND rn.archived_at IS NULL
WHERE dei.id = $6::uuid
  AND dei.tenant_id = $7::uuid
  AND dei.digital_employee_id = $8::uuid
  AND dei.runtime_node_id = $9::uuid
  AND dei.provider_type = $10::varchar
  AND dei.status IN ('ready', 'active')
  AND dei.deleted_at IS NULL
  AND EXISTS (
      SELECT 1
      FROM runtime_sessions rs
      JOIN runtime_enrollments re
        ON re.id = rs.enrollment_id
       AND re.tenant_id = rs.tenant_id
       AND re.runtime_node_id = rs.runtime_node_id
       AND re.status = 'approved'
       AND re.revoked_at IS NULL
       AND re.rejected_at IS NULL
      WHERE rs.tenant_id = dei.tenant_id
        AND rs.runtime_node_id = rn.id
        AND rs.expires_at > NOW()
        AND rs.revoked_at IS NULL
  )
RETURNING id, tenant_id, provider_session_id, digital_employee_id, execution_instance_id, runtime_node_id, provider_type, status, recoverable, last_active_at, closed_at, error_message, metadata, created_at, updated_at, session_display_id, session_params, session_state, last_sequence_number, last_command_id, last_run_id, last_error_family, last_runtime_seen_at
`

type CreateProviderSessionParams struct {
	ProviderSessionID   string             `json:"provider_session_id"`
	Status              string             `json:"status"`
	Recoverable         bool               `json:"recoverable"`
	LastActiveAt        pgtype.Timestamptz `json:"last_active_at"`
	Metadata            []byte             `json:"metadata"`
	ExecutionInstanceID uuid.UUID          `json:"execution_instance_id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	DigitalEmployeeID   uuid.UUID          `json:"digital_employee_id"`
	RuntimeNodeID       uuid.UUID          `json:"runtime_node_id"`
	ProviderType        string             `json:"provider_type"`
}

func (q *Queries) CreateProviderSession(ctx context.Context, arg CreateProviderSessionParams) (ProviderSession, error) {
	row := q.db.QueryRow(ctx, CreateProviderSession,
		arg.ProviderSessionID,
		arg.Status,
		arg.Recoverable,
		arg.LastActiveAt,
		arg.Metadata,
		arg.ExecutionInstanceID,
		arg.TenantID,
		arg.DigitalEmployeeID,
		arg.RuntimeNodeID,
		arg.ProviderType,
	)
	var i ProviderSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderSessionID,
		&i.DigitalEmployeeID,
		&i.ExecutionInstanceID,
		&i.RuntimeNodeID,
		&i.ProviderType,
		&i.Status,
		&i.Recoverable,
		&i.LastActiveAt,
		&i.ClosedAt,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionDisplayID,
		&i.SessionParams,
		&i.SessionState,
		&i.LastSequenceNumber,
		&i.LastCommandID,
		&i.LastRunID,
		&i.LastErrorFamily,
		&i.LastRuntimeSeenAt,
	)
	return i, err
}

const CreateProviderSessionEvent = `-- name: CreateProviderSessionEvent :one
INSERT INTO provider_session_events (
    tenant_id,
    provider_session_id,
    digital_employee_id,
    execution_instance_id,
    runtime_node_id,
    provider_type,
    event_type,
    sequence_number,
    payload,
    request_id,
    command_id,
    raw_event_ref,
    metadata
) SELECT
    ps.tenant_id,
    ps.id,
    ps.digital_employee_id,
    ps.execution_instance_id,
    ps.runtime_node_id,
    ps.provider_type,
    $1::varchar,
    $2::integer,
    $3::jsonb,
    $4::varchar,
    $5::varchar,
    $6::text,
    COALESCE($7::jsonb, '{}'::jsonb)
FROM provider_sessions ps
JOIN digital_employee_execution_instances dei
  ON dei.id = ps.execution_instance_id
 AND dei.tenant_id = ps.tenant_id
 AND dei.digital_employee_id = ps.digital_employee_id
 AND dei.runtime_node_id = ps.runtime_node_id
 AND dei.provider_type = ps.provider_type
 AND dei.status IN ('ready', 'active')
 AND dei.deleted_at IS NULL
JOIN digital_employees de
  ON de.id = ps.digital_employee_id
 AND de.tenant_id = ps.tenant_id
 AND de.status NOT IN ('disabled', 'error')
 AND de.deleted_at IS NULL
 AND de.archived_at IS NULL
JOIN runtime_nodes rn
  ON rn.id = ps.runtime_node_id
 AND rn.tenant_id = ps.tenant_id
 AND rn.node_id = $8::varchar
 AND rn.status = 'online'
 AND rn.disabled_at IS NULL
 AND rn.archived_at IS NULL
WHERE ps.id = $9::uuid
  AND ps.tenant_id = $10::uuid
  AND ps.status IN ('running', 'idle')
  AND ps.closed_at IS NULL
  AND EXISTS (
      SELECT 1
      FROM runtime_sessions rs
      JOIN runtime_enrollments re
        ON re.id = rs.enrollment_id
       AND re.tenant_id = rs.tenant_id
       AND re.runtime_node_id = rs.runtime_node_id
       AND re.status = 'approved'
       AND re.revoked_at IS NULL
       AND re.rejected_at IS NULL
      WHERE rs.tenant_id = ps.tenant_id
        AND rs.runtime_node_id = rn.id
        AND rs.expires_at > NOW()
        AND rs.revoked_at IS NULL
  )
RETURNING id, tenant_id, provider_session_id, digital_employee_id, execution_instance_id, runtime_node_id, provider_type, event_type, sequence_number, payload, request_id, command_id, raw_event_ref, metadata, created_at, log_ref, session_state_patch
`

type CreateProviderSessionEventParams struct {
	EventType         string      `json:"event_type"`
	SequenceNumber    int32       `json:"sequence_number"`
	Payload           []byte      `json:"payload"`
	RequestID         pgtype.Text `json:"request_id"`
	CommandID         pgtype.Text `json:"command_id"`
	RawEventRef       pgtype.Text `json:"raw_event_ref"`
	Metadata          []byte      `json:"metadata"`
	NodeID            string      `json:"node_id"`
	ProviderSessionID uuid.UUID   `json:"provider_session_id"`
	TenantID          uuid.UUID   `json:"tenant_id"`
}

func (q *Queries) CreateProviderSessionEvent(ctx context.Context, arg CreateProviderSessionEventParams) (ProviderSessionEvent, error) {
	row := q.db.QueryRow(ctx, CreateProviderSessionEvent,
		arg.EventType,
		arg.SequenceNumber,
		arg.Payload,
		arg.RequestID,
		arg.CommandID,
		arg.RawEventRef,
		arg.Metadata,
		arg.NodeID,
		arg.ProviderSessionID,
		arg.TenantID,
	)
	var i ProviderSessionEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderSessionID,
		&i.DigitalEmployeeID,
		&i.ExecutionInstanceID,
		&i.RuntimeNodeID,
		&i.ProviderType,
		&i.EventType,
		&i.SequenceNumber,
		&i.Payload,
		&i.RequestID,
		&i.CommandID,
		&i.RawEventRef,
		&i.Metadata,
		&i.CreatedAt,
		&i.LogRef,
		&i.SessionStatePatch,
	)
	return i, err
}

const CreateProviderSessionEventIfAbsent = `-- name: CreateProviderSessionEventIfAbsent :one
WITH inserted AS (
    INSERT INTO provider_session_events (
        tenant_id,
        provider_session_id,
        digital_employee_id,
        execution_instance_id,
        runtime_node_id,
        provider_type,
        event_type,
        sequence_number,
        payload,
        request_id,
        command_id,
        raw_event_ref,
        log_ref,
        session_state_patch,
        metadata
    ) SELECT
        ps.tenant_id,
        ps.id,
        ps.digital_employee_id,
        ps.execution_instance_id,
        ps.runtime_node_id,
        ps.provider_type,
        $1::varchar,
        $2::integer,
        COALESCE($3::jsonb, '{}'::jsonb),
        $4::varchar,
        $5::varchar,
        $6::text,
        $7::text,
        COALESCE($8::jsonb, '{}'::jsonb),
        COALESCE($9::jsonb, '{}'::jsonb)
    FROM provider_sessions ps
    WHERE ps.id = $10::uuid
      AND ps.tenant_id = $11::uuid
    ON CONFLICT DO NOTHING
    RETURNING id, tenant_id, provider_session_id, digital_employee_id, execution_instance_id, runtime_node_id, provider_type, event_type, sequence_number, payload, request_id, command_id, raw_event_ref, metadata, created_at, log_ref, session_state_patch
)
SELECT id, tenant_id, provider_session_id, digital_employee_id, execution_instance_id, runtime_node_id, provider_type, event_type, sequence_number, payload, request_id, command_id, raw_event_ref, metadata, created_at, log_ref, session_state_patch FROM inserted
UNION ALL
SELECT id, tenant_id, provider_session_id, digital_employee_id, execution_instance_id, runtime_node_id, provider_type, event_type, sequence_number, payload, request_id, command_id, raw_event_ref, metadata, created_at, log_ref, session_state_patch
FROM provider_session_events
WHERE tenant_id = $11::uuid
  AND provider_session_id = $10::uuid
  AND sequence_number = $2::integer
  AND (
      (
          $5::varchar IS NOT NULL
          AND command_id = $5::varchar
      )
      OR (
          $5::varchar IS NULL
          AND $4::varchar IS NOT NULL
          AND request_id = $4::varchar
      )
  )
LIMIT 1
`

type CreateProviderSessionEventIfAbsentParams struct {
	EventType           string      `json:"event_type"`
	SequenceNumber      int32       `json:"sequence_number"`
	Payload             []byte      `json:"payload"`
	RequestID           pgtype.Text `json:"request_id"`
	CommandID           pgtype.Text `json:"command_id"`
	RawEventRef         pgtype.Text `json:"raw_event_ref"`
	LogRef              pgtype.Text `json:"log_ref"`
	SessionStatePatch   []byte      `json:"session_state_patch"`
	Metadata            []byte      `json:"metadata"`
	ProviderSessionUuid uuid.UUID   `json:"provider_session_uuid"`
	TenantID            uuid.UUID   `json:"tenant_id"`
}

type CreateProviderSessionEventIfAbsentRow struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	ProviderSessionID   uuid.UUID          `json:"provider_session_id"`
	DigitalEmployeeID   uuid.UUID          `json:"digital_employee_id"`
	ExecutionInstanceID uuid.UUID          `json:"execution_instance_id"`
	RuntimeNodeID       uuid.UUID          `json:"runtime_node_id"`
	ProviderType        string             `json:"provider_type"`
	EventType           string             `json:"event_type"`
	SequenceNumber      int32              `json:"sequence_number"`
	Payload             []byte             `json:"payload"`
	RequestID           pgtype.Text        `json:"request_id"`
	CommandID           pgtype.Text        `json:"command_id"`
	RawEventRef         pgtype.Text        `json:"raw_event_ref"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	LogRef              pgtype.Text        `json:"log_ref"`
	SessionStatePatch   []byte             `json:"session_state_patch"`
}

func (q *Queries) CreateProviderSessionEventIfAbsent(ctx context.Context, arg CreateProviderSessionEventIfAbsentParams) (CreateProviderSessionEventIfAbsentRow, error) {
	row := q.db.QueryRow(ctx, CreateProviderSessionEventIfAbsent,
		arg.EventType,
		arg.SequenceNumber,
		arg.Payload,
		arg.RequestID,
		arg.CommandID,
		arg.RawEventRef,
		arg.LogRef,
		arg.SessionStatePatch,
		arg.Metadata,
		arg.ProviderSessionUuid,
		arg.TenantID,
	)
	var i CreateProviderSessionEventIfAbsentRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderSessionID,
		&i.DigitalEmployeeID,
		&i.ExecutionInstanceID,
		&i.RuntimeNodeID,
		&i.ProviderType,
		&i.EventType,
		&i.SequenceNumber,
		&i.Payload,
		&i.RequestID,
		&i.CommandID,
		&i.RawEventRef,
		&i.Metadata,
		&i.CreatedAt,
		&i.LogRef,
		&i.SessionStatePatch,
	)
	return i, err
}

const GetLatestProviderSessionEventSequence = `-- name: GetLatestProviderSessionEventSequence :one
SELECT COALESCE(MAX(sequence_number), 0)::integer AS max_sequence
FROM provider_session_events
WHERE tenant_id = $1::uuid
  AND provider_session_id = $2::uuid
`

type GetLatestProviderSessionEventSequenceParams struct {
	TenantID          uuid.UUID `json:"tenant_id"`
	ProviderSessionID uuid.UUID `json:"provider_session_id"`
}

func (q *Queries) GetLatestProviderSessionEventSequence(ctx context.Context, arg GetLatestProviderSessionEventSequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, GetLatestProviderSessionEventSequence, arg.TenantID, arg.ProviderSessionID)
	var max_sequence int32
	err := row.Scan(&max_sequence)
	return max_sequence, err
}

const GetProviderSession = `-- name: GetProviderSession :one
SELECT id, tenant_id, provider_session_id, digital_employee_id, execution_instance_id, runtime_node_id, provider_type, status, recoverable, last_active_at, closed_at, error_message, metadata, created_at, updated_at, session_display_id, session_params, session_state, last_sequence_number, last_command_id, last_run_id, last_error_family, last_runtime_seen_at
FROM provider_sessions
WHERE id = $1::uuid
  AND tenant_id = $2::uuid
`

type GetProviderSessionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetProviderSession(ctx context.Context, arg GetProviderSessionParams) (ProviderSession, error) {
	row := q.db.QueryRow(ctx, GetProviderSession, arg.ID, arg.TenantID)
	var i ProviderSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderSessionID,
		&i.DigitalEmployeeID,
		&i.ExecutionInstanceID,
		&i.RuntimeNodeID,
		&i.ProviderType,
		&i.Status,
		&i.Recoverable,
		&i.LastActiveAt,
		&i.ClosedAt,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionDisplayID,
		&i.SessionParams,
		&i.SessionState,
		&i.LastSequenceNumber,
		&i.LastCommandID,
		&i.LastRunID,
		&i.LastErrorFamily,
		&i.LastRuntimeSeenAt,
	)
	return i, err
}

const GetProviderSessionByExternalID = `-- name: GetProviderSessionByExternalID :one
SELECT id, tenant_id, provider_session_id, digital_employee_id, execution_instance_id, runtime_node_id, provider_type, status, recoverable, last_active_at, closed_at, error_message, metadata, created_at, updated_at, session_display_id, session_params, session_state, last_sequence_number, last_command_id, last_run_id, last_error_family, last_runtime_seen_at
FROM provider_sessions
WHERE tenant_id = $1::uuid
  AND provider_type = $2::varchar
  AND provider_session_id = $3::varchar
`

type GetProviderSessionByExternalIDParams struct {
	TenantID          uuid.UUID `json:"tenant_id"`
	ProviderType      string    `json:"provider_type"`
	ProviderSessionID string    `json:"provider_session_id"`
}

func (q *Queries) GetProviderSessionByExternalID(ctx context.Context, arg GetProviderSessionByExternalIDParams) (ProviderSession, error) {
	row := q.db.QueryRow(ctx, GetProviderSessionByExternalID, arg.TenantID, arg.ProviderType, arg.ProviderSessionID)
	var i ProviderSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderSessionID,
		&i.DigitalEmployeeID,
		&i.ExecutionInstanceID,
		&i.RuntimeNodeID,
		&i.ProviderType,
		&i.Status,
		&i.Recoverable,
		&i.LastActiveAt,
		&i.ClosedAt,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionDisplayID,
		&i.SessionParams,
		&i.SessionState,
		&i.LastSequenceNumber,
		&i.LastCommandID,
		&i.LastRunID,
		&i.LastErrorFamily,
		&i.LastRuntimeSeenAt,
	)
	return i, err
}

const ListProviderSessionEvents = `-- name: ListProviderSessionEvents :many
SELECT id, tenant_id, provider_session_id, digital_employee_id, execution_instance_id, runtime_node_id, provider_type, event_type, sequence_number, payload, request_id, command_id, raw_event_ref, metadata, created_at, log_ref, session_state_patch
FROM provider_session_events
WHERE tenant_id = $1::uuid
  AND provider_session_id = $2::uuid
ORDER BY sequence_number ASC
`

type ListProviderSessionEventsParams struct {
	TenantID          uuid.UUID `json:"tenant_id"`
	ProviderSessionID uuid.UUID `json:"provider_session_id"`
}

func (q *Queries) ListProviderSessionEvents(ctx context.Context, arg ListProviderSessionEventsParams) ([]ProviderSessionEvent, error) {
	rows, err := q.db.Query(ctx, ListProviderSessionEvents, arg.TenantID, arg.ProviderSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderSessionEvent{}
	for rows.Next() {
		var i ProviderSessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProviderSessionID,
			&i.DigitalEmployeeID,
			&i.ExecutionInstanceID,
			&i.RuntimeNodeID,
			&i.ProviderType,
			&i.EventType,
			&i.SequenceNumber,
			&i.Payload,
			&i.RequestID,
			&i.CommandID,
			&i.RawEventRef,
			&i.Metadata,
			&i.CreatedAt,
			&i.LogRef,
			&i.SessionStatePatch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListProviderSessionsForDigitalEmployee = `-- name: ListProviderSessionsForDigitalEmployee :many
SELECT id, tenant_id, provider_session_id, digital_employee_id, execution_instance_id, runtime_node_id, provider_type, status, recoverable, last_active_at, closed_at, error_message, metadata, created_at, updated_at, session_display_id, session_params, session_state, last_sequence_number, last_command_id, last_run_id, last_error_family, last_runtime_seen_at
FROM provider_sessions
WHERE tenant_id = $1::uuid
  AND digital_employee_id = $2::uuid
  AND ($3::varchar IS NULL OR status = $3::varchar)
ORDER BY last_active_at DESC NULLS LAST, created_at DESC
LIMIT $5 OFFSET $4
`

type ListProviderSessionsForDigitalEmployeeParams struct {
	TenantID          uuid.UUID   `json:"tenant_id"`
	DigitalEmployeeID uuid.UUID   `json:"digital_employee_id"`
	Status            pgtype.Text `json:"status"`
	Offset            int32       `json:"offset"`
	Limit             int32       `json:"limit"`
}

func (q *Queries) ListProviderSessionsForDigitalEmployee(ctx context.Context, arg ListProviderSessionsForDigitalEmployeeParams) ([]ProviderSession, error) {
	rows, err := q.db.Query(ctx, ListProviderSessionsForDigitalEmployee,
		arg.TenantID,
		arg.DigitalEmployeeID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderSession{}
	for rows.Next() {
		var i ProviderSession
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProviderSessionID,
			&i.DigitalEmployeeID,
			&i.ExecutionInstanceID,
			&i.RuntimeNodeID,
			&i.ProviderType,
			&i.Status,
			&i.Recoverable,
			&i.LastActiveAt,
			&i.ClosedAt,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionDisplayID,
			&i.SessionParams,
			&i.SessionState,
			&i.LastSequenceNumber,
			&i.LastCommandID,
			&i.LastRunID,
			&i.LastErrorFamily,
			&i.LastRuntimeSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateProviderSessionStatus = `-- name: UpdateProviderSessionStatus :one
UPDATE provider_sessions
SET status = $1::varchar,
    last_active_at = NOW(),
    closed_at = CASE
        WHEN $1::varchar IN ('completed', 'failed', 'stopped') THEN COALESCE(closed_at, NOW())
        ELSE closed_at
    END,
    error_message = CASE
        WHEN $1::varchar = 'failed' THEN COALESCE($2::text, error_message)
        WHEN $1::varchar IN ('running', 'idle', 'completed', 'stopped') THEN NULL
        ELSE error_message
    END,
    updated_at = NOW()
WHERE id = $3::uuid
  AND tenant_id = $4::uuid
RETURNING id, tenant_id, provider_session_id, digital_employee_id, execution_instance_id, runtime_node_id, provider_type, status, recoverable, last_active_at, closed_at, error_message, metadata, created_at, updated_at, session_display_id, session_params, session_state, last_sequence_number, last_command_id, last_run_id, last_error_family, last_runtime_seen_at
`

type UpdateProviderSessionStatusParams struct {
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
}

func (q *Queries) UpdateProviderSessionStatus(ctx context.Context, arg UpdateProviderSessionStatusParams) (ProviderSession, error) {
	row := q.db.QueryRow(ctx, UpdateProviderSessionStatus,
		arg.Status,
		arg.ErrorMessage,
		arg.ID,
		arg.TenantID,
	)
	var i ProviderSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderSessionID,
		&i.DigitalEmployeeID,
		&i.ExecutionInstanceID,
		&i.RuntimeNodeID,
		&i.ProviderType,
		&i.Status,
		&i.Recoverable,
		&i.LastActiveAt,
		&i.ClosedAt,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionDisplayID,
		&i.SessionParams,
		&i.SessionState,
		&i.LastSequenceNumber,
		&i.LastCommandID,
		&i.LastRunID,
		&i.LastErrorFamily,
		&i.LastRuntimeSeenAt,
	)
	return i, err
}

const UpsertProviderSessionByExternalID = `-- name: UpsertProviderSessionByExternalID :one
INSERT INTO provider_sessions (
    tenant_id,
    provider_session_id,
    digital_employee_id,
    execution_instance_id,
    runtime_node_id,
    provider_type,
    status,
    recoverable,
    last_active_at,
    session_display_id,
    session_params,
    session_state,
    last_sequence_number,
    last_command_id,
    last_run_id,
    last_error_family,
    last_runtime_seen_at,
    metadata
) VALUES (
    $1::uuid,
    $2::varchar,
    $3::uuid,
    $4::uuid,
    $5::uuid,
    $6::varchar,
    $7::varchar,
    $8::boolean,
    NOW(),
    $9::varchar,
    COALESCE($10::jsonb, '{}'::jsonb),
    COALESCE($11::jsonb, '{}'::jsonb),
    $12::integer,
    $13::varchar,
    $14::uuid,
    $15::varchar,
    NOW(),
    COALESCE($16::jsonb, '{}'::jsonb)
)
ON CONFLICT (tenant_id, provider_type, provider_session_id) DO UPDATE SET
    status = CASE
        WHEN EXCLUDED.last_sequence_number >= provider_sessions.last_sequence_number THEN EXCLUDED.status
        ELSE provider_sessions.status
    END,
    last_active_at = CASE
        WHEN EXCLUDED.last_sequence_number >= provider_sessions.last_sequence_number THEN NOW()
        ELSE provider_sessions.last_active_at
    END,
    session_display_id = CASE
        WHEN EXCLUDED.last_sequence_number >= provider_sessions.last_sequence_number THEN COALESCE(EXCLUDED.session_display_id, provider_sessions.session_display_id)
        ELSE provider_sessions.session_display_id
    END,
    session_params = CASE
        WHEN EXCLUDED.last_sequence_number >= provider_sessions.last_sequence_number THEN EXCLUDED.session_params
        ELSE provider_sessions.session_params
    END,
    session_state = CASE
        WHEN EXCLUDED.last_sequence_number >= provider_sessions.last_sequence_number THEN EXCLUDED.session_state
        ELSE provider_sessions.session_state
    END,
    last_sequence_number = GREATEST(provider_sessions.last_sequence_number, EXCLUDED.last_sequence_number),
    last_command_id = CASE
        WHEN EXCLUDED.last_sequence_number >= provider_sessions.last_sequence_number THEN EXCLUDED.last_command_id
        ELSE provider_sessions.last_command_id
    END,
    last_run_id = CASE
        WHEN EXCLUDED.last_sequence_number >= provider_sessions.last_sequence_number THEN EXCLUDED.last_run_id
        ELSE provider_sessions.last_run_id
    END,
    last_error_family = CASE
        WHEN EXCLUDED.last_sequence_number >= provider_sessions.last_sequence_number THEN EXCLUDED.last_error_family
        ELSE provider_sessions.last_error_family
    END,
    last_runtime_seen_at = CASE
        WHEN EXCLUDED.last_sequence_number >= provider_sessions.last_sequence_number THEN NOW()
        ELSE provider_sessions.last_runtime_seen_at
    END,
    metadata = CASE
        WHEN EXCLUDED.last_sequence_number >= provider_sessions.last_sequence_number THEN EXCLUDED.metadata
        ELSE provider_sessions.metadata
    END,
    updated_at = CASE
        WHEN EXCLUDED.last_sequence_number >= provider_sessions.last_sequence_number THEN NOW()
        ELSE provider_sessions.updated_at
    END
RETURNING id, tenant_id, provider_session_id, digital_employee_id, execution_instance_id, runtime_node_id, provider_type, status, recoverable, last_active_at, closed_at, error_message, metadata, created_at, updated_at, session_display_id, session_params, session_state, last_sequence_number, last_command_id, last_run_id, last_error_family, last_runtime_seen_at
`

type UpsertProviderSessionByExternalIDParams struct {
	TenantID            uuid.UUID     `json:"tenant_id"`
	ProviderSessionID   string        `json:"provider_session_id"`
	DigitalEmployeeID   uuid.UUID     `json:"digital_employee_id"`
	ExecutionInstanceID uuid.UUID     `json:"execution_instance_id"`
	RuntimeNodeID       uuid.UUID     `json:"runtime_node_id"`
	ProviderType        string        `json:"provider_type"`
	Status              string        `json:"status"`
	Recoverable         bool          `json:"recoverable"`
	SessionDisplayID    pgtype.Text   `json:"session_display_id"`
	SessionParams       []byte        `json:"session_params"`
	SessionState        []byte        `json:"session_state"`
	LastSequenceNumber  int32         `json:"last_sequence_number"`
	LastCommandID       pgtype.Text   `json:"last_command_id"`
	LastRunID           uuid.NullUUID `json:"last_run_id"`
	LastErrorFamily     pgtype.Text   `json:"last_error_family"`
	Metadata            []byte        `json:"metadata"`
}

func (q *Queries) UpsertProviderSessionByExternalID(ctx context.Context, arg UpsertProviderSessionByExternalIDParams) (ProviderSession, error) {
	row := q.db.QueryRow(ctx, UpsertProviderSessionByExternalID,
		arg.TenantID,
		arg.ProviderSessionID,
		arg.DigitalEmployeeID,
		arg.ExecutionInstanceID,
		arg.RuntimeNodeID,
		arg.ProviderType,
		arg.Status,
		arg.Recoverable,
		arg.SessionDisplayID,
		arg.SessionParams,
		arg.SessionState,
		arg.LastSequenceNumber,
		arg.LastCommandID,
		arg.LastRunID,
		arg.LastErrorFamily,
		arg.Metadata,
	)
	var i ProviderSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderSessionID,
		&i.DigitalEmployeeID,
		&i.ExecutionInstanceID,
		&i.RuntimeNodeID,
		&i.ProviderType,
		&i.Status,
		&i.Recoverable,
		&i.LastActiveAt,
		&i.ClosedAt,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionDisplayID,
		&i.SessionParams,
		&i.SessionState,
		&i.LastSequenceNumber,
		&i.LastCommandID,
		&i.LastRunID,
		&i.LastErrorFamily,
		&i.LastRuntimeSeenAt,
	)
	return i, err
}
