// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package queries

import (
	"context"
)

const CountRetentionCandidates = `-- name: CountRetentionCandidates :one
SELECT
    (SELECT COUNT(*) FROM runtime_events WHERE created_at < NOW() - make_interval(days => $1::int))::bigint AS runtime_events,
    (SELECT COUNT(*) FROM web_operation_logs WHERE module = 'authz' AND result = 'succeeded')::bigint AS authz_allow_logs,
    (SELECT COUNT(*) FROM auth_sessions WHERE expires_at < NOW())::bigint AS expired_sessions
`

type CountRetentionCandidatesRow struct {
	RuntimeEvents   int64 `json:"runtime_events"`
	AuthzAllowLogs  int64 `json:"authz_allow_logs"`
	ExpiredSessions int64 `json:"expired_sessions"`
}

// 观测用:不删,只报当前各类超期行的规模,供日志与人工核对。
func (q *Queries) CountRetentionCandidates(ctx context.Context, runtimeDays int32) (CountRetentionCandidatesRow, error) {
	row := q.db.QueryRow(ctx, CountRetentionCandidates, runtimeDays)
	var i CountRetentionCandidatesRow
	err := row.Scan(&i.RuntimeEvents, &i.AuthzAllowLogs, &i.ExpiredSessions)
	return i, err
}

const DeleteExecutionLedgerEventsForPurgedProjects = `-- name: DeleteExecutionLedgerEventsForPurgedProjects :execrows
DELETE FROM execution_ledger_events
WHERE ctid IN (
    SELECT e.ctid FROM execution_ledger_events e
    JOIN projects p ON p.id = e.project_id
    WHERE p.deleted_at IS NOT NULL
      AND p.deleted_at < NOW() - make_interval(days => $1::int)
    LIMIT $2
)
`

type DeleteExecutionLedgerEventsForPurgedProjectsParams struct {
	RetentionDays int32 `json:"retention_days"`
	BatchSize     int32 `json:"batch_size"`
}

func (q *Queries) DeleteExecutionLedgerEventsForPurgedProjects(ctx context.Context, arg DeleteExecutionLedgerEventsForPurgedProjectsParams) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExecutionLedgerEventsForPurgedProjects, arg.RetentionDays, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteExpiredAuthSessions = `-- name: DeleteExpiredAuthSessions :execrows
DELETE FROM auth_sessions
WHERE ctid IN (
    SELECT ctid FROM auth_sessions
    WHERE expires_at < NOW()
    LIMIT $1
)
`

func (q *Queries) DeleteExpiredAuthSessions(ctx context.Context, batchSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExpiredAuthSessions, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteExpiredAuthzAllowOperationLogs = `-- name: DeleteExpiredAuthzAllowOperationLogs :execrows
DELETE FROM web_operation_logs
WHERE ctid IN (
    SELECT ctid FROM web_operation_logs
    WHERE module = 'authz'
      AND result = 'succeeded'
      AND created_at < NOW() - make_interval(days => $1::int)
    LIMIT $2
)
`

type DeleteExpiredAuthzAllowOperationLogsParams struct {
	RetentionDays int32 `json:"retention_days"`
	BatchSize     int32 `json:"batch_size"`
}

// authz 放行日志单独一条更短的保留期:实测 177,090 条 succeeded 对 19 条 failed,
// 放行记录几乎没有审计价值,拒绝记录才是信号。拒绝走下面的通用规则。
func (q *Queries) DeleteExpiredAuthzAllowOperationLogs(ctx context.Context, arg DeleteExpiredAuthzAllowOperationLogsParams) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExpiredAuthzAllowOperationLogs, arg.RetentionDays, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteExpiredOperationLogs = `-- name: DeleteExpiredOperationLogs :execrows
DELETE FROM web_operation_logs
WHERE ctid IN (
    SELECT ctid FROM web_operation_logs
    WHERE NOT (module = 'authz' AND result = 'succeeded')
      AND created_at < NOW() - make_interval(days => $1::int)
    LIMIT $2
)
`

type DeleteExpiredOperationLogsParams struct {
	RetentionDays int32 `json:"retention_days"`
	BatchSize     int32 `json:"batch_size"`
}

func (q *Queries) DeleteExpiredOperationLogs(ctx context.Context, arg DeleteExpiredOperationLogsParams) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExpiredOperationLogs, arg.RetentionDays, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteExpiredProviderSessionEvents = `-- name: DeleteExpiredProviderSessionEvents :execrows
DELETE FROM provider_session_events
WHERE ctid IN (
    SELECT ctid FROM provider_session_events
    WHERE created_at < NOW() - make_interval(days => $1::int)
    LIMIT $2
)
`

type DeleteExpiredProviderSessionEventsParams struct {
	RetentionDays int32 `json:"retention_days"`
	BatchSize     int32 `json:"batch_size"`
}

func (q *Queries) DeleteExpiredProviderSessionEvents(ctx context.Context, arg DeleteExpiredProviderSessionEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExpiredProviderSessionEvents, arg.RetentionDays, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteExpiredRuntimeCommandReceipts = `-- name: DeleteExpiredRuntimeCommandReceipts :execrows
DELETE FROM runtime_command_receipts
WHERE ctid IN (
    SELECT ctid FROM runtime_command_receipts
    WHERE created_at < NOW() - make_interval(days => $1::int)
    LIMIT $2
)
`

type DeleteExpiredRuntimeCommandReceiptsParams struct {
	RetentionDays int32 `json:"retention_days"`
	BatchSize     int32 `json:"batch_size"`
}

func (q *Queries) DeleteExpiredRuntimeCommandReceipts(ctx context.Context, arg DeleteExpiredRuntimeCommandReceiptsParams) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExpiredRuntimeCommandReceipts, arg.RetentionDays, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteExpiredRuntimeEvents = `-- name: DeleteExpiredRuntimeEvents :execrows

DELETE FROM runtime_events
WHERE ctid IN (
    SELECT ctid FROM runtime_events
    WHERE created_at < NOW() - make_interval(days => $1::int)
    LIMIT $2
)
`

type DeleteExpiredRuntimeEventsParams struct {
	RetentionDays int32 `json:"retention_days"`
	BatchSize     int32 `json:"batch_size"`
}

// 数据保留清理查询(P1-B)。
//
// 每张表一条静态语句而不是一条动态 SQL:表名不进参数,既避免注入面,也让 sqlc
// 保持类型检查。保留策略的"表驱动"体现在 internal/retention 的注册表上,注册表项
// 各自挂一条本文件里的语句。
//
// 全部按批删除(LIMIT + ctid 子查询):远程库上一次性删几十万行会拖长事务、放大锁
// 竞争,分批让每个事务都很短。调用方循环到单批删不满为止。
//
// 业务事实表(project_events / execution_ledger_events / audit_events)不按时间删,
// 只在其所属项目已软删且超期后随项目一起清(见文件末尾)。
func (q *Queries) DeleteExpiredRuntimeEvents(ctx context.Context, arg DeleteExpiredRuntimeEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExpiredRuntimeEvents, arg.RetentionDays, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteExpiredTaskEvents = `-- name: DeleteExpiredTaskEvents :execrows
DELETE FROM task_events
WHERE ctid IN (
    SELECT ctid FROM task_events
    WHERE created_at < NOW() - make_interval(days => $1::int)
    LIMIT $2
)
`

type DeleteExpiredTaskEventsParams struct {
	RetentionDays int32 `json:"retention_days"`
	BatchSize     int32 `json:"batch_size"`
}

func (q *Queries) DeleteExpiredTaskEvents(ctx context.Context, arg DeleteExpiredTaskEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExpiredTaskEvents, arg.RetentionDays, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteProjectEventsForPurgedProjects = `-- name: DeleteProjectEventsForPurgedProjects :execrows

DELETE FROM project_events
WHERE ctid IN (
    SELECT e.ctid FROM project_events e
    JOIN projects p ON p.id = e.project_id
    WHERE p.deleted_at IS NOT NULL
      AND p.deleted_at < NOW() - make_interval(days => $1::int)
    LIMIT $2
)
`

type DeleteProjectEventsForPurgedProjectsParams struct {
	RetentionDays int32 `json:"retention_days"`
	BatchSize     int32 `json:"batch_size"`
}

// 以下三条清理"已软删且超期项目"的事实行。项目软删只置 deleted_at、不清行
// (SoftDeleteProject),这些行在应用层已完全不可见,却是最大的一块死重。
func (q *Queries) DeleteProjectEventsForPurgedProjects(ctx context.Context, arg DeleteProjectEventsForPurgedProjectsParams) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteProjectEventsForPurgedProjects, arg.RetentionDays, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
