// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_vocabulary.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateRoleVocabulary = `-- name: CreateRoleVocabulary :one
INSERT INTO role_vocabulary (
    id,
    tenant_id,
    role_key,
    title,
    description,
    status
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::text,
    COALESCE($5::text, ''),
    COALESCE($6::varchar, 'active')
) RETURNING id, tenant_id, role_key, title, description, status, deleted_at, created_at, updated_at
`

type CreateRoleVocabularyParams struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	RoleKey     string      `json:"role_key"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      pgtype.Text `json:"status"`
}

func (q *Queries) CreateRoleVocabulary(ctx context.Context, arg CreateRoleVocabularyParams) (RoleVocabulary, error) {
	row := q.db.QueryRow(ctx, CreateRoleVocabulary,
		arg.ID,
		arg.TenantID,
		arg.RoleKey,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i RoleVocabulary
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoleKey,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetActiveRoleVocabularyByKeys = `-- name: GetActiveRoleVocabularyByKeys :many
SELECT id, tenant_id, role_key, title, description, status, deleted_at, created_at, updated_at FROM role_vocabulary
WHERE tenant_id = $1::uuid
  AND role_key = ANY($2::text[])
  AND deleted_at IS NULL
  AND status = 'active'
`

type GetActiveRoleVocabularyByKeysParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	RoleKeys []string  `json:"role_keys"`
}

func (q *Queries) GetActiveRoleVocabularyByKeys(ctx context.Context, arg GetActiveRoleVocabularyByKeysParams) ([]RoleVocabulary, error) {
	rows, err := q.db.Query(ctx, GetActiveRoleVocabularyByKeys, arg.TenantID, arg.RoleKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleVocabulary{}
	for rows.Next() {
		var i RoleVocabulary
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RoleKey,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRoleVocabularyByKey = `-- name: GetRoleVocabularyByKey :one
SELECT id, tenant_id, role_key, title, description, status, deleted_at, created_at, updated_at FROM role_vocabulary
WHERE tenant_id = $1::uuid
  AND role_key = $2::text
  AND deleted_at IS NULL
`

type GetRoleVocabularyByKeyParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	RoleKey  string    `json:"role_key"`
}

func (q *Queries) GetRoleVocabularyByKey(ctx context.Context, arg GetRoleVocabularyByKeyParams) (RoleVocabulary, error) {
	row := q.db.QueryRow(ctx, GetRoleVocabularyByKey, arg.TenantID, arg.RoleKey)
	var i RoleVocabulary
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoleKey,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListActiveRoleVocabulary = `-- name: ListActiveRoleVocabulary :many
SELECT id, tenant_id, role_key, title, description, status, deleted_at, created_at, updated_at FROM role_vocabulary
WHERE tenant_id = $1::uuid
  AND deleted_at IS NULL
  AND status = 'active'
ORDER BY role_key ASC
`

func (q *Queries) ListActiveRoleVocabulary(ctx context.Context, tenantID uuid.UUID) ([]RoleVocabulary, error) {
	rows, err := q.db.Query(ctx, ListActiveRoleVocabulary, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleVocabulary{}
	for rows.Next() {
		var i RoleVocabulary
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RoleKey,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRoleVocabulary = `-- name: ListRoleVocabulary :many
SELECT id, tenant_id, role_key, title, description, status, deleted_at, created_at, updated_at FROM role_vocabulary
WHERE tenant_id = $1::uuid
  AND deleted_at IS NULL
ORDER BY role_key ASC
`

func (q *Queries) ListRoleVocabulary(ctx context.Context, tenantID uuid.UUID) ([]RoleVocabulary, error) {
	rows, err := q.db.Query(ctx, ListRoleVocabulary, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleVocabulary{}
	for rows.Next() {
		var i RoleVocabulary
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RoleKey,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateRoleVocabulary = `-- name: UpdateRoleVocabulary :one
UPDATE role_vocabulary
SET
    title = COALESCE($1::text, title),
    description = COALESCE($2::text, description),
    status = COALESCE($3::varchar, status),
    updated_at = NOW()
WHERE tenant_id = $4::uuid
  AND role_key = $5::text
  AND deleted_at IS NULL
RETURNING id, tenant_id, role_key, title, description, status, deleted_at, created_at, updated_at
`

type UpdateRoleVocabularyParams struct {
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      pgtype.Text `json:"status"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	RoleKey     string      `json:"role_key"`
}

func (q *Queries) UpdateRoleVocabulary(ctx context.Context, arg UpdateRoleVocabularyParams) (RoleVocabulary, error) {
	row := q.db.QueryRow(ctx, UpdateRoleVocabulary,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.TenantID,
		arg.RoleKey,
	)
	var i RoleVocabulary
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoleKey,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
