// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: runtime.sql

package queries

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const createRuntimeNode = `-- name: CreateRuntimeNode :one

INSERT INTO runtime_nodes (
    node_id,
    name,
    supported_providers,
    max_slots,
    current_load,
    status,
    metadata,
    last_heartbeat_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, node_id, name, supported_providers, max_slots, current_load, status, metadata, last_heartbeat_at, created_at, updated_at
`

type CreateRuntimeNodeParams struct {
	NodeID             string                `json:"node_id"`
	Name               string                `json:"name"`
	SupportedProviders json.RawMessage       `json:"supported_providers"`
	MaxSlots           int32                 `json:"max_slots"`
	CurrentLoad        int32                 `json:"current_load"`
	Status             string                `json:"status"`
	Metadata           pqtype.NullRawMessage `json:"metadata"`
	LastHeartbeatAt    sql.NullTime          `json:"last_heartbeat_at"`
}

// Runtime Node Queries
func (q *Queries) CreateRuntimeNode(ctx context.Context, arg CreateRuntimeNodeParams) (RuntimeNode, error) {
	row := q.db.QueryRowContext(ctx, createRuntimeNode,
		arg.NodeID,
		arg.Name,
		arg.SupportedProviders,
		arg.MaxSlots,
		arg.CurrentLoad,
		arg.Status,
		arg.Metadata,
		arg.LastHeartbeatAt,
	)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.SupportedProviders,
		&i.MaxSlots,
		&i.CurrentLoad,
		&i.Status,
		&i.Metadata,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRuntimeNode = `-- name: DeleteRuntimeNode :exec
DELETE FROM runtime_nodes
WHERE node_id = $1
`

func (q *Queries) DeleteRuntimeNode(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, deleteRuntimeNode, nodeID)
	return err
}

const getRuntimeNode = `-- name: GetRuntimeNode :one
SELECT id, node_id, name, supported_providers, max_slots, current_load, status, metadata, last_heartbeat_at, created_at, updated_at FROM runtime_nodes
WHERE node_id = $1
`

func (q *Queries) GetRuntimeNode(ctx context.Context, nodeID string) (RuntimeNode, error) {
	row := q.db.QueryRowContext(ctx, getRuntimeNode, nodeID)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.SupportedProviders,
		&i.MaxSlots,
		&i.CurrentLoad,
		&i.Status,
		&i.Metadata,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntimeNodeByID = `-- name: GetRuntimeNodeByID :one
SELECT id, node_id, name, supported_providers, max_slots, current_load, status, metadata, last_heartbeat_at, created_at, updated_at FROM runtime_nodes
WHERE id = $1
`

func (q *Queries) GetRuntimeNodeByID(ctx context.Context, id int64) (RuntimeNode, error) {
	row := q.db.QueryRowContext(ctx, getRuntimeNodeByID, id)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.SupportedProviders,
		&i.MaxSlots,
		&i.CurrentLoad,
		&i.Status,
		&i.Metadata,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOnlineNodes = `-- name: ListOnlineNodes :many
SELECT id, node_id, name, supported_providers, max_slots, current_load, status, metadata, last_heartbeat_at, created_at, updated_at FROM runtime_nodes
WHERE status = 'online'
  AND last_heartbeat_at > NOW() - INTERVAL '2 minutes'
  AND ($1::varchar IS NULL OR supported_providers::jsonb ? $1)
ORDER BY current_load ASC, created_at ASC
`

func (q *Queries) ListOnlineNodes(ctx context.Context, dollar_1 string) ([]RuntimeNode, error) {
	rows, err := q.db.QueryContext(ctx, listOnlineNodes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeNode{}
	for rows.Next() {
		var i RuntimeNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.SupportedProviders,
			&i.MaxSlots,
			&i.CurrentLoad,
			&i.Status,
			&i.Metadata,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeNodes = `-- name: ListRuntimeNodes :many
SELECT id, node_id, name, supported_providers, max_slots, current_load, status, metadata, last_heartbeat_at, created_at, updated_at FROM runtime_nodes
WHERE ($1::varchar IS NULL OR status = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRuntimeNodesParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListRuntimeNodes(ctx context.Context, arg ListRuntimeNodesParams) ([]RuntimeNode, error) {
	rows, err := q.db.QueryContext(ctx, listRuntimeNodes, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeNode{}
	for rows.Next() {
		var i RuntimeNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.SupportedProviders,
			&i.MaxSlots,
			&i.CurrentLoad,
			&i.Status,
			&i.Metadata,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRuntimeNodeHeartbeat = `-- name: UpdateRuntimeNodeHeartbeat :one
UPDATE runtime_nodes
SET last_heartbeat_at = $2,
    status = $3,
    updated_at = NOW()
WHERE node_id = $1
RETURNING id, node_id, name, supported_providers, max_slots, current_load, status, metadata, last_heartbeat_at, created_at, updated_at
`

type UpdateRuntimeNodeHeartbeatParams struct {
	NodeID          string       `json:"node_id"`
	LastHeartbeatAt sql.NullTime `json:"last_heartbeat_at"`
	Status          string       `json:"status"`
}

func (q *Queries) UpdateRuntimeNodeHeartbeat(ctx context.Context, arg UpdateRuntimeNodeHeartbeatParams) (RuntimeNode, error) {
	row := q.db.QueryRowContext(ctx, updateRuntimeNodeHeartbeat, arg.NodeID, arg.LastHeartbeatAt, arg.Status)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.SupportedProviders,
		&i.MaxSlots,
		&i.CurrentLoad,
		&i.Status,
		&i.Metadata,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRuntimeNodeLoad = `-- name: UpdateRuntimeNodeLoad :one
UPDATE runtime_nodes
SET current_load = $2,
    updated_at = NOW()
WHERE node_id = $1
RETURNING id, node_id, name, supported_providers, max_slots, current_load, status, metadata, last_heartbeat_at, created_at, updated_at
`

type UpdateRuntimeNodeLoadParams struct {
	NodeID      string `json:"node_id"`
	CurrentLoad int32  `json:"current_load"`
}

func (q *Queries) UpdateRuntimeNodeLoad(ctx context.Context, arg UpdateRuntimeNodeLoadParams) (RuntimeNode, error) {
	row := q.db.QueryRowContext(ctx, updateRuntimeNodeLoad, arg.NodeID, arg.CurrentLoad)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.SupportedProviders,
		&i.MaxSlots,
		&i.CurrentLoad,
		&i.Status,
		&i.Metadata,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRuntimeNodeStatus = `-- name: UpdateRuntimeNodeStatus :one
UPDATE runtime_nodes
SET status = $2,
    updated_at = NOW()
WHERE node_id = $1
RETURNING id, node_id, name, supported_providers, max_slots, current_load, status, metadata, last_heartbeat_at, created_at, updated_at
`

type UpdateRuntimeNodeStatusParams struct {
	NodeID string `json:"node_id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateRuntimeNodeStatus(ctx context.Context, arg UpdateRuntimeNodeStatusParams) (RuntimeNode, error) {
	row := q.db.QueryRowContext(ctx, updateRuntimeNodeStatus, arg.NodeID, arg.Status)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.SupportedProviders,
		&i.MaxSlots,
		&i.CurrentLoad,
		&i.Status,
		&i.Metadata,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
