// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_enrollment.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ApproveRuntimeEnrollment = `-- name: ApproveRuntimeEnrollment :one
UPDATE runtime_enrollments
SET status = 'approved',
    runtime_node_id = $1::uuid,
    approved_by = $2::uuid,
    approved_at = NOW(),
    rejected_by = NULL,
    rejected_at = NULL,
    reject_reason = NULL,
    revoked_by = NULL,
    revoked_at = NULL,
    revoke_reason = NULL,
    updated_at = NOW()
WHERE id = $3::uuid
  AND tenant_id = $4::uuid
  AND status = 'pending'
  AND EXISTS (
      SELECT 1
      FROM runtime_nodes rn
      WHERE rn.id = $1::uuid
        AND rn.tenant_id = runtime_enrollments.tenant_id
        AND rn.node_id = runtime_enrollments.node_id
        AND rn.disabled_at IS NULL
        AND rn.archived_at IS NULL
  )
RETURNING id, tenant_id, runtime_node_id, node_id, bootstrap_key_id, status, request_payload, approved_by, approved_at, rejected_by, rejected_at, reject_reason, revoked_by, revoked_at, revoke_reason, last_hello_at, created_at, updated_at
`

type ApproveRuntimeEnrollmentParams struct {
	RuntimeNodeID uuid.UUID     `json:"runtime_node_id"`
	ApprovedBy    uuid.NullUUID `json:"approved_by"`
	ID            uuid.UUID     `json:"id"`
	TenantID      uuid.UUID     `json:"tenant_id"`
}

func (q *Queries) ApproveRuntimeEnrollment(ctx context.Context, arg ApproveRuntimeEnrollmentParams) (RuntimeEnrollment, error) {
	row := q.db.QueryRow(ctx, ApproveRuntimeEnrollment,
		arg.RuntimeNodeID,
		arg.ApprovedBy,
		arg.ID,
		arg.TenantID,
	)
	var i RuntimeEnrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeNodeID,
		&i.NodeID,
		&i.BootstrapKeyID,
		&i.Status,
		&i.RequestPayload,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectReason,
		&i.RevokedBy,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.LastHelloAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ApproveRuntimeEnrollmentWithNode = `-- name: ApproveRuntimeEnrollmentWithNode :one
WITH pending_enrollment AS (
    SELECT id, tenant_id, runtime_node_id, node_id, bootstrap_key_id, status, request_payload, approved_by, approved_at, rejected_by, rejected_at, reject_reason, revoked_by, revoked_at, revoke_reason, last_hello_at, created_at, updated_at
    FROM runtime_enrollments
    WHERE id = $2::uuid
      AND tenant_id = $3::uuid
      AND status = 'pending'
    FOR UPDATE
),
upserted_node AS (
    INSERT INTO runtime_nodes (
        tenant_id,
        node_id,
        name,
        supported_providers,
        max_slots,
        current_load,
        status,
        metadata,
        last_heartbeat_at
    )
    SELECT
        pe.tenant_id,
        pe.node_id,
        $4::varchar,
        $5::jsonb,
        $6::integer,
        $7::integer,
        $8::varchar,
        COALESCE($9::jsonb, '{}'::jsonb),
        $10::timestamptz
    FROM pending_enrollment pe
    ON CONFLICT (node_id) DO UPDATE SET
        name = EXCLUDED.name,
        supported_providers = EXCLUDED.supported_providers,
        max_slots = EXCLUDED.max_slots,
        current_load = EXCLUDED.current_load,
        status = EXCLUDED.status,
        metadata = EXCLUDED.metadata,
        last_heartbeat_at = EXCLUDED.last_heartbeat_at,
        disabled_at = NULL,
        archived_at = NULL,
        updated_at = NOW()
    WHERE runtime_nodes.tenant_id = EXCLUDED.tenant_id
    RETURNING id, tenant_id, node_id, name, supported_providers, max_slots, current_load, status, metadata, last_heartbeat_at, disabled_at, archived_at, created_at, updated_at
)
UPDATE runtime_enrollments re
SET status = 'approved',
    runtime_node_id = un.id,
    approved_by = $1::uuid,
    approved_at = NOW(),
    rejected_by = NULL,
    rejected_at = NULL,
    reject_reason = NULL,
    revoked_by = NULL,
    revoked_at = NULL,
    revoke_reason = NULL,
    updated_at = NOW()
FROM pending_enrollment pe
JOIN upserted_node un
  ON un.tenant_id = pe.tenant_id
 AND un.node_id = pe.node_id
WHERE re.id = pe.id
  AND re.tenant_id = pe.tenant_id
  AND re.status = 'pending'
RETURNING re.id, re.tenant_id, re.runtime_node_id, re.node_id, re.bootstrap_key_id, re.status, re.request_payload, re.approved_by, re.approved_at, re.rejected_by, re.rejected_at, re.reject_reason, re.revoked_by, re.revoked_at, re.revoke_reason, re.last_hello_at, re.created_at, re.updated_at
`

type ApproveRuntimeEnrollmentWithNodeParams struct {
	ApprovedBy         uuid.NullUUID      `json:"approved_by"`
	ID                 uuid.UUID          `json:"id"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	Name               string             `json:"name"`
	SupportedProviders []byte             `json:"supported_providers"`
	MaxSlots           int32              `json:"max_slots"`
	CurrentLoad        int32              `json:"current_load"`
	NodeStatus         string             `json:"node_status"`
	Metadata           []byte             `json:"metadata"`
	LastHeartbeatAt    pgtype.Timestamptz `json:"last_heartbeat_at"`
}

func (q *Queries) ApproveRuntimeEnrollmentWithNode(ctx context.Context, arg ApproveRuntimeEnrollmentWithNodeParams) (RuntimeEnrollment, error) {
	row := q.db.QueryRow(ctx, ApproveRuntimeEnrollmentWithNode,
		arg.ApprovedBy,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.SupportedProviders,
		arg.MaxSlots,
		arg.CurrentLoad,
		arg.NodeStatus,
		arg.Metadata,
		arg.LastHeartbeatAt,
	)
	var i RuntimeEnrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeNodeID,
		&i.NodeID,
		&i.BootstrapKeyID,
		&i.Status,
		&i.RequestPayload,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectReason,
		&i.RevokedBy,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.LastHelloAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CountRuntimeEnrollmentsForTenant = `-- name: CountRuntimeEnrollmentsForTenant :one
SELECT COUNT(*)::bigint
FROM runtime_enrollments
WHERE tenant_id = $1::uuid
  AND ($2::varchar IS NULL OR status = $2::varchar)
`

type CountRuntimeEnrollmentsForTenantParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Status   pgtype.Text `json:"status"`
}

func (q *Queries) CountRuntimeEnrollmentsForTenant(ctx context.Context, arg CountRuntimeEnrollmentsForTenantParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountRuntimeEnrollmentsForTenant, arg.TenantID, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const CreateRuntimeBootstrapKey = `-- name: CreateRuntimeBootstrapKey :one
INSERT INTO runtime_bootstrap_keys (
    tenant_id,
    name,
    key_hash,
    status,
    description,
    expires_at,
    created_by,
    metadata
) VALUES (
    COALESCE($1::uuid, '00000000-0000-0000-0000-000000000001'::uuid),
    $2::varchar,
    $3::varchar,
    $4::varchar,
    $5::text,
    $6::timestamptz,
    $7::uuid,
    COALESCE($8::jsonb, '{}'::jsonb)
) RETURNING id, tenant_id, name, key_hash, status, description, expires_at, created_by, revoked_at, revoked_by, revoked_reason, metadata, created_at, updated_at
`

type CreateRuntimeBootstrapKeyParams struct {
	TenantID    uuid.NullUUID      `json:"tenant_id"`
	Name        string             `json:"name"`
	KeyHash     string             `json:"key_hash"`
	Status      string             `json:"status"`
	Description pgtype.Text        `json:"description"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedBy   uuid.NullUUID      `json:"created_by"`
	Metadata    []byte             `json:"metadata"`
}

func (q *Queries) CreateRuntimeBootstrapKey(ctx context.Context, arg CreateRuntimeBootstrapKeyParams) (RuntimeBootstrapKey, error) {
	row := q.db.QueryRow(ctx, CreateRuntimeBootstrapKey,
		arg.TenantID,
		arg.Name,
		arg.KeyHash,
		arg.Status,
		arg.Description,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.Metadata,
	)
	var i RuntimeBootstrapKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyHash,
		&i.Status,
		&i.Description,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokedReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateRuntimeSession = `-- name: CreateRuntimeSession :one
INSERT INTO runtime_sessions (
    tenant_id,
    runtime_node_id,
    enrollment_id,
    token_lookup_hash,
    token_secret_hash,
    expires_at
) SELECT
    re.tenant_id,
    rn.id,
    re.id,
    $1::varchar,
    $2::varchar,
    $3::timestamptz
FROM runtime_enrollments re
JOIN runtime_nodes rn
  ON rn.id = re.runtime_node_id
 AND rn.tenant_id = re.tenant_id
 AND rn.archived_at IS NULL
WHERE re.id = $4::uuid
  AND re.tenant_id = $5::uuid
  AND re.status = 'approved'
  AND re.runtime_node_id IS NOT NULL
  AND rn.id = $6::uuid
RETURNING id, tenant_id, runtime_node_id, enrollment_id, token_lookup_hash, token_secret_hash, expires_at, last_seen_at, revoked_at, revoked_reason, created_at, updated_at
`

type CreateRuntimeSessionParams struct {
	TokenLookupHash string             `json:"token_lookup_hash"`
	TokenSecretHash string             `json:"token_secret_hash"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	EnrollmentID    uuid.NullUUID      `json:"enrollment_id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	RuntimeNodeID   uuid.UUID          `json:"runtime_node_id"`
}

func (q *Queries) CreateRuntimeSession(ctx context.Context, arg CreateRuntimeSessionParams) (RuntimeSession, error) {
	row := q.db.QueryRow(ctx, CreateRuntimeSession,
		arg.TokenLookupHash,
		arg.TokenSecretHash,
		arg.ExpiresAt,
		arg.EnrollmentID,
		arg.TenantID,
		arg.RuntimeNodeID,
	)
	var i RuntimeSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeNodeID,
		&i.EnrollmentID,
		&i.TokenLookupHash,
		&i.TokenSecretHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetActiveRuntimeBootstrapKeyByHash = `-- name: GetActiveRuntimeBootstrapKeyByHash :one
SELECT id, tenant_id, name, key_hash, status, description, expires_at, created_by, revoked_at, revoked_by, revoked_reason, metadata, created_at, updated_at
FROM runtime_bootstrap_keys
WHERE tenant_id = $1::uuid
  AND key_hash = $2::varchar
  AND status = 'active'
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
`

type GetActiveRuntimeBootstrapKeyByHashParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	KeyHash  string    `json:"key_hash"`
}

func (q *Queries) GetActiveRuntimeBootstrapKeyByHash(ctx context.Context, arg GetActiveRuntimeBootstrapKeyByHashParams) (RuntimeBootstrapKey, error) {
	row := q.db.QueryRow(ctx, GetActiveRuntimeBootstrapKeyByHash, arg.TenantID, arg.KeyHash)
	var i RuntimeBootstrapKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyHash,
		&i.Status,
		&i.Description,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokedReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetActiveRuntimeSessionByLookupHash = `-- name: GetActiveRuntimeSessionByLookupHash :one
SELECT rs.id, rs.tenant_id, rs.runtime_node_id, rs.enrollment_id, rs.token_lookup_hash, rs.token_secret_hash, rs.expires_at, rs.last_seen_at, rs.revoked_at, rs.revoked_reason, rs.created_at, rs.updated_at,
       rn.node_id
FROM runtime_sessions rs
JOIN runtime_enrollments re
  ON re.id = rs.enrollment_id
 AND re.tenant_id = rs.tenant_id
 AND re.runtime_node_id = rs.runtime_node_id
 AND re.status = 'approved'
 AND re.rejected_at IS NULL
 AND re.revoked_at IS NULL
JOIN runtime_nodes rn
  ON rn.id = rs.runtime_node_id
 AND rn.tenant_id = rs.tenant_id
 AND rn.archived_at IS NULL
WHERE rs.token_lookup_hash = $1::varchar
  AND rs.expires_at > NOW()
  AND rs.revoked_at IS NULL
`

type GetActiveRuntimeSessionByLookupHashRow struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	RuntimeNodeID   uuid.UUID          `json:"runtime_node_id"`
	EnrollmentID    uuid.NullUUID      `json:"enrollment_id"`
	TokenLookupHash string             `json:"token_lookup_hash"`
	TokenSecretHash string             `json:"token_secret_hash"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason   pgtype.Text        `json:"revoked_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	NodeID          string             `json:"node_id"`
}

func (q *Queries) GetActiveRuntimeSessionByLookupHash(ctx context.Context, tokenLookupHash string) (GetActiveRuntimeSessionByLookupHashRow, error) {
	row := q.db.QueryRow(ctx, GetActiveRuntimeSessionByLookupHash, tokenLookupHash)
	var i GetActiveRuntimeSessionByLookupHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeNodeID,
		&i.EnrollmentID,
		&i.TokenLookupHash,
		&i.TokenSecretHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NodeID,
	)
	return i, err
}

const GetRuntimeCapability = `-- name: GetRuntimeCapability :one
SELECT id, tenant_id, runtime_node_id, capability_type, capability_key, provider_type, provider_version, binary_path, available, workspace_base_dir, capacity, labels, status, details, health_status, metadata, last_seen_at, disabled_at, archived_at, created_at, updated_at
FROM runtime_capabilities
WHERE tenant_id = $1::uuid
  AND runtime_node_id = $2::uuid
  AND capability_type = $3::varchar
  AND capability_key = $4::varchar
  AND archived_at IS NULL
`

type GetRuntimeCapabilityParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	RuntimeNodeID  uuid.UUID `json:"runtime_node_id"`
	CapabilityType string    `json:"capability_type"`
	CapabilityKey  string    `json:"capability_key"`
}

func (q *Queries) GetRuntimeCapability(ctx context.Context, arg GetRuntimeCapabilityParams) (RuntimeCapability, error) {
	row := q.db.QueryRow(ctx, GetRuntimeCapability,
		arg.TenantID,
		arg.RuntimeNodeID,
		arg.CapabilityType,
		arg.CapabilityKey,
	)
	var i RuntimeCapability
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeNodeID,
		&i.CapabilityType,
		&i.CapabilityKey,
		&i.ProviderType,
		&i.ProviderVersion,
		&i.BinaryPath,
		&i.Available,
		&i.WorkspaceBaseDir,
		&i.Capacity,
		&i.Labels,
		&i.Status,
		&i.Details,
		&i.HealthStatus,
		&i.Metadata,
		&i.LastSeenAt,
		&i.DisabledAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetRuntimeEnrollment = `-- name: GetRuntimeEnrollment :one
SELECT id, tenant_id, runtime_node_id, node_id, bootstrap_key_id, status, request_payload, approved_by, approved_at, rejected_by, rejected_at, reject_reason, revoked_by, revoked_at, revoke_reason, last_hello_at, created_at, updated_at
FROM runtime_enrollments
WHERE tenant_id = $1::uuid
  AND id = $2::uuid
`

type GetRuntimeEnrollmentParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) GetRuntimeEnrollment(ctx context.Context, arg GetRuntimeEnrollmentParams) (RuntimeEnrollment, error) {
	row := q.db.QueryRow(ctx, GetRuntimeEnrollment, arg.TenantID, arg.ID)
	var i RuntimeEnrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeNodeID,
		&i.NodeID,
		&i.BootstrapKeyID,
		&i.Status,
		&i.RequestPayload,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectReason,
		&i.RevokedBy,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.LastHelloAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetRuntimeEnrollmentByNodeID = `-- name: GetRuntimeEnrollmentByNodeID :one
SELECT id, tenant_id, runtime_node_id, node_id, bootstrap_key_id, status, request_payload, approved_by, approved_at, rejected_by, rejected_at, reject_reason, revoked_by, revoked_at, revoke_reason, last_hello_at, created_at, updated_at
FROM runtime_enrollments
WHERE tenant_id = $1::uuid
  AND node_id = $2::varchar
`

type GetRuntimeEnrollmentByNodeIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	NodeID   string    `json:"node_id"`
}

func (q *Queries) GetRuntimeEnrollmentByNodeID(ctx context.Context, arg GetRuntimeEnrollmentByNodeIDParams) (RuntimeEnrollment, error) {
	row := q.db.QueryRow(ctx, GetRuntimeEnrollmentByNodeID, arg.TenantID, arg.NodeID)
	var i RuntimeEnrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeNodeID,
		&i.NodeID,
		&i.BootstrapKeyID,
		&i.Status,
		&i.RequestPayload,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectReason,
		&i.RevokedBy,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.LastHelloAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListActiveRuntimeBootstrapKeys = `-- name: ListActiveRuntimeBootstrapKeys :many
SELECT id, tenant_id, name, key_hash, status, description, expires_at, created_by, revoked_at, revoked_by, revoked_reason, metadata, created_at, updated_at
FROM runtime_bootstrap_keys
WHERE tenant_id = $1::uuid
  AND status = 'active'
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) ListActiveRuntimeBootstrapKeys(ctx context.Context, tenantID uuid.UUID) ([]RuntimeBootstrapKey, error) {
	rows, err := q.db.Query(ctx, ListActiveRuntimeBootstrapKeys, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeBootstrapKey{}
	for rows.Next() {
		var i RuntimeBootstrapKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.KeyHash,
			&i.Status,
			&i.Description,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokedReason,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRuntimeCapabilities = `-- name: ListRuntimeCapabilities :many
SELECT id, tenant_id, runtime_node_id, capability_type, capability_key, provider_type, provider_version, binary_path, available, workspace_base_dir, capacity, labels, status, details, health_status, metadata, last_seen_at, disabled_at, archived_at, created_at, updated_at
FROM runtime_capabilities
WHERE tenant_id = $1::uuid
  AND runtime_node_id = $2::uuid
  AND archived_at IS NULL
ORDER BY provider_type ASC
`

type ListRuntimeCapabilitiesParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	RuntimeNodeID uuid.UUID `json:"runtime_node_id"`
}

func (q *Queries) ListRuntimeCapabilities(ctx context.Context, arg ListRuntimeCapabilitiesParams) ([]RuntimeCapability, error) {
	rows, err := q.db.Query(ctx, ListRuntimeCapabilities, arg.TenantID, arg.RuntimeNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeCapability{}
	for rows.Next() {
		var i RuntimeCapability
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RuntimeNodeID,
			&i.CapabilityType,
			&i.CapabilityKey,
			&i.ProviderType,
			&i.ProviderVersion,
			&i.BinaryPath,
			&i.Available,
			&i.WorkspaceBaseDir,
			&i.Capacity,
			&i.Labels,
			&i.Status,
			&i.Details,
			&i.HealthStatus,
			&i.Metadata,
			&i.LastSeenAt,
			&i.DisabledAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRuntimeEnrollments = `-- name: ListRuntimeEnrollments :many
SELECT id, tenant_id, runtime_node_id, node_id, bootstrap_key_id, status, request_payload, approved_by, approved_at, rejected_by, rejected_at, reject_reason, revoked_by, revoked_at, revoke_reason, last_hello_at, created_at, updated_at
FROM runtime_enrollments
WHERE tenant_id = $1::uuid
  AND ($2::varchar IS NULL OR status = $2::varchar)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListRuntimeEnrollmentsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Status   pgtype.Text `json:"status"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListRuntimeEnrollments(ctx context.Context, arg ListRuntimeEnrollmentsParams) ([]RuntimeEnrollment, error) {
	rows, err := q.db.Query(ctx, ListRuntimeEnrollments,
		arg.TenantID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeEnrollment{}
	for rows.Next() {
		var i RuntimeEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RuntimeNodeID,
			&i.NodeID,
			&i.BootstrapKeyID,
			&i.Status,
			&i.RequestPayload,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectedBy,
			&i.RejectedAt,
			&i.RejectReason,
			&i.RevokedBy,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.LastHelloAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RejectRuntimeEnrollment = `-- name: RejectRuntimeEnrollment :one
UPDATE runtime_enrollments
SET status = 'rejected',
    rejected_by = $1::uuid,
    rejected_at = NOW(),
    reject_reason = $2::text,
    updated_at = NOW()
WHERE id = $3::uuid
  AND tenant_id = $4::uuid
  AND status = 'pending'
RETURNING id, tenant_id, runtime_node_id, node_id, bootstrap_key_id, status, request_payload, approved_by, approved_at, rejected_by, rejected_at, reject_reason, revoked_by, revoked_at, revoke_reason, last_hello_at, created_at, updated_at
`

type RejectRuntimeEnrollmentParams struct {
	RejectedBy   uuid.NullUUID `json:"rejected_by"`
	RejectReason pgtype.Text   `json:"reject_reason"`
	ID           uuid.UUID     `json:"id"`
	TenantID     uuid.UUID     `json:"tenant_id"`
}

func (q *Queries) RejectRuntimeEnrollment(ctx context.Context, arg RejectRuntimeEnrollmentParams) (RuntimeEnrollment, error) {
	row := q.db.QueryRow(ctx, RejectRuntimeEnrollment,
		arg.RejectedBy,
		arg.RejectReason,
		arg.ID,
		arg.TenantID,
	)
	var i RuntimeEnrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeNodeID,
		&i.NodeID,
		&i.BootstrapKeyID,
		&i.Status,
		&i.RequestPayload,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectReason,
		&i.RevokedBy,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.LastHelloAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const RenewRuntimeSession = `-- name: RenewRuntimeSession :one
UPDATE runtime_sessions
SET expires_at = $1::timestamptz,
    last_seen_at = NOW(),
    updated_at = NOW()
WHERE id = $2::uuid
  AND tenant_id = $3::uuid
  AND expires_at > NOW()
  AND revoked_at IS NULL
  AND EXISTS (
      SELECT 1
      FROM runtime_enrollments re
      WHERE re.id = runtime_sessions.enrollment_id
        AND re.tenant_id = runtime_sessions.tenant_id
        AND re.runtime_node_id = runtime_sessions.runtime_node_id
        AND re.status = 'approved'
        AND re.rejected_at IS NULL
        AND re.revoked_at IS NULL
  )
RETURNING id, tenant_id, runtime_node_id, enrollment_id, token_lookup_hash, token_secret_hash, expires_at, last_seen_at, revoked_at, revoked_reason, created_at, updated_at
`

type RenewRuntimeSessionParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
}

func (q *Queries) RenewRuntimeSession(ctx context.Context, arg RenewRuntimeSessionParams) (RuntimeSession, error) {
	row := q.db.QueryRow(ctx, RenewRuntimeSession, arg.ExpiresAt, arg.ID, arg.TenantID)
	var i RuntimeSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeNodeID,
		&i.EnrollmentID,
		&i.TokenLookupHash,
		&i.TokenSecretHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const RevokeRuntimeBootstrapKey = `-- name: RevokeRuntimeBootstrapKey :one
UPDATE runtime_bootstrap_keys
SET status = 'revoked',
    revoked_at = COALESCE(revoked_at, NOW()),
    revoked_by = $1::uuid,
    revoked_reason = $2::text,
    updated_at = NOW()
WHERE id = $3::uuid
  AND tenant_id = $4::uuid
RETURNING id, tenant_id, name, key_hash, status, description, expires_at, created_by, revoked_at, revoked_by, revoked_reason, metadata, created_at, updated_at
`

type RevokeRuntimeBootstrapKeyParams struct {
	RevokedBy     uuid.NullUUID `json:"revoked_by"`
	RevokedReason pgtype.Text   `json:"revoked_reason"`
	ID            uuid.UUID     `json:"id"`
	TenantID      uuid.UUID     `json:"tenant_id"`
}

func (q *Queries) RevokeRuntimeBootstrapKey(ctx context.Context, arg RevokeRuntimeBootstrapKeyParams) (RuntimeBootstrapKey, error) {
	row := q.db.QueryRow(ctx, RevokeRuntimeBootstrapKey,
		arg.RevokedBy,
		arg.RevokedReason,
		arg.ID,
		arg.TenantID,
	)
	var i RuntimeBootstrapKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyHash,
		&i.Status,
		&i.Description,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokedReason,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const RevokeRuntimeEnrollment = `-- name: RevokeRuntimeEnrollment :one
WITH revoked_enrollment AS (
    UPDATE runtime_enrollments
    SET status = 'revoked',
        revoked_by = $1::uuid,
        revoked_at = NOW(),
        revoke_reason = $2::text,
        updated_at = NOW()
    WHERE id = $3::uuid
      AND tenant_id = $4::uuid
      AND status IN ('pending', 'approved')
    RETURNING id, tenant_id, runtime_node_id, node_id, bootstrap_key_id, status, request_payload, approved_by, approved_at, rejected_by, rejected_at, reject_reason, revoked_by, revoked_at, revoke_reason, last_hello_at, created_at, updated_at
),
revoked_sessions AS (
    UPDATE runtime_sessions rs
    SET revoked_at = COALESCE(rs.revoked_at, NOW()),
        revoked_reason = COALESCE($2::text, rs.revoked_reason),
        updated_at = NOW()
    FROM revoked_enrollment re
    WHERE rs.tenant_id = re.tenant_id
      AND rs.runtime_node_id = re.runtime_node_id
      AND rs.expires_at > NOW()
      AND rs.revoked_at IS NULL
    RETURNING rs.id
)
SELECT id, tenant_id, runtime_node_id, node_id, bootstrap_key_id, status, request_payload, approved_by, approved_at, rejected_by, rejected_at, reject_reason, revoked_by, revoked_at, revoke_reason, last_hello_at, created_at, updated_at
FROM revoked_enrollment
`

type RevokeRuntimeEnrollmentParams struct {
	RevokedBy    uuid.NullUUID `json:"revoked_by"`
	RevokeReason pgtype.Text   `json:"revoke_reason"`
	ID           uuid.UUID     `json:"id"`
	TenantID     uuid.UUID     `json:"tenant_id"`
}

type RevokeRuntimeEnrollmentRow struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	RuntimeNodeID  uuid.NullUUID      `json:"runtime_node_id"`
	NodeID         string             `json:"node_id"`
	BootstrapKeyID uuid.UUID          `json:"bootstrap_key_id"`
	Status         string             `json:"status"`
	RequestPayload []byte             `json:"request_payload"`
	ApprovedBy     uuid.NullUUID      `json:"approved_by"`
	ApprovedAt     pgtype.Timestamptz `json:"approved_at"`
	RejectedBy     uuid.NullUUID      `json:"rejected_by"`
	RejectedAt     pgtype.Timestamptz `json:"rejected_at"`
	RejectReason   pgtype.Text        `json:"reject_reason"`
	RevokedBy      uuid.NullUUID      `json:"revoked_by"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason   pgtype.Text        `json:"revoke_reason"`
	LastHelloAt    pgtype.Timestamptz `json:"last_hello_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RevokeRuntimeEnrollment(ctx context.Context, arg RevokeRuntimeEnrollmentParams) (RevokeRuntimeEnrollmentRow, error) {
	row := q.db.QueryRow(ctx, RevokeRuntimeEnrollment,
		arg.RevokedBy,
		arg.RevokeReason,
		arg.ID,
		arg.TenantID,
	)
	var i RevokeRuntimeEnrollmentRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeNodeID,
		&i.NodeID,
		&i.BootstrapKeyID,
		&i.Status,
		&i.RequestPayload,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectReason,
		&i.RevokedBy,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.LastHelloAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const RevokeRuntimeSession = `-- name: RevokeRuntimeSession :one
UPDATE runtime_sessions
SET revoked_at = COALESCE(revoked_at, NOW()),
    revoked_reason = $1::text,
    updated_at = NOW()
WHERE id = $2::uuid
  AND tenant_id = $3::uuid
RETURNING id, tenant_id, runtime_node_id, enrollment_id, token_lookup_hash, token_secret_hash, expires_at, last_seen_at, revoked_at, revoked_reason, created_at, updated_at
`

type RevokeRuntimeSessionParams struct {
	RevokedReason pgtype.Text `json:"revoked_reason"`
	ID            uuid.UUID   `json:"id"`
	TenantID      uuid.UUID   `json:"tenant_id"`
}

func (q *Queries) RevokeRuntimeSession(ctx context.Context, arg RevokeRuntimeSessionParams) (RuntimeSession, error) {
	row := q.db.QueryRow(ctx, RevokeRuntimeSession, arg.RevokedReason, arg.ID, arg.TenantID)
	var i RuntimeSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeNodeID,
		&i.EnrollmentID,
		&i.TokenLookupHash,
		&i.TokenSecretHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const TouchRuntimeSessionLastSeen = `-- name: TouchRuntimeSessionLastSeen :one
UPDATE runtime_sessions
SET last_seen_at = NOW(),
    updated_at = NOW()
WHERE id = $1::uuid
  AND tenant_id = $2::uuid
  AND expires_at > NOW()
  AND revoked_at IS NULL
  AND EXISTS (
      SELECT 1
      FROM runtime_enrollments re
      WHERE re.id = runtime_sessions.enrollment_id
        AND re.tenant_id = runtime_sessions.tenant_id
        AND re.runtime_node_id = runtime_sessions.runtime_node_id
        AND re.status = 'approved'
        AND re.rejected_at IS NULL
        AND re.revoked_at IS NULL
  )
RETURNING id, tenant_id, runtime_node_id, enrollment_id, token_lookup_hash, token_secret_hash, expires_at, last_seen_at, revoked_at, revoked_reason, created_at, updated_at
`

type TouchRuntimeSessionLastSeenParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) TouchRuntimeSessionLastSeen(ctx context.Context, arg TouchRuntimeSessionLastSeenParams) (RuntimeSession, error) {
	row := q.db.QueryRow(ctx, TouchRuntimeSessionLastSeen, arg.ID, arg.TenantID)
	var i RuntimeSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeNodeID,
		&i.EnrollmentID,
		&i.TokenLookupHash,
		&i.TokenSecretHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpsertRuntimeCapability = `-- name: UpsertRuntimeCapability :one
INSERT INTO runtime_capabilities (
    tenant_id,
    runtime_node_id,
    capability_type,
    capability_key,
    provider_type,
    provider_version,
    binary_path,
    available,
    workspace_base_dir,
    capacity,
    labels,
    status,
    details,
    health_status,
    metadata,
    last_seen_at
) SELECT
    rn.tenant_id,
    rn.id,
    $1::varchar,
    $2::varchar,
    $3::varchar,
    $4::varchar,
    $5::text,
    $6::boolean,
    $7::text,
    COALESCE($8::jsonb, '{}'::jsonb),
    COALESCE($9::jsonb, '{}'::jsonb),
    $10::varchar,
    COALESCE($11::jsonb, '{}'::jsonb),
    $12::varchar,
    COALESCE($13::jsonb, '{}'::jsonb),
    $14::timestamptz
FROM runtime_nodes rn
WHERE rn.id = $15::uuid
  AND rn.tenant_id = $16::uuid
  AND rn.archived_at IS NULL
ON CONFLICT (tenant_id, runtime_node_id, capability_type, capability_key) DO UPDATE SET
    provider_type = EXCLUDED.provider_type,
    provider_version = EXCLUDED.provider_version,
    binary_path = EXCLUDED.binary_path,
    available = EXCLUDED.available,
    workspace_base_dir = EXCLUDED.workspace_base_dir,
    capacity = EXCLUDED.capacity,
    labels = EXCLUDED.labels,
    status = EXCLUDED.status,
    details = EXCLUDED.details,
    health_status = EXCLUDED.health_status,
    metadata = EXCLUDED.metadata,
    last_seen_at = EXCLUDED.last_seen_at,
    updated_at = NOW()
RETURNING id, tenant_id, runtime_node_id, capability_type, capability_key, provider_type, provider_version, binary_path, available, workspace_base_dir, capacity, labels, status, details, health_status, metadata, last_seen_at, disabled_at, archived_at, created_at, updated_at
`

type UpsertRuntimeCapabilityParams struct {
	CapabilityType   string             `json:"capability_type"`
	CapabilityKey    string             `json:"capability_key"`
	ProviderType     string             `json:"provider_type"`
	ProviderVersion  pgtype.Text        `json:"provider_version"`
	BinaryPath       pgtype.Text        `json:"binary_path"`
	Available        bool               `json:"available"`
	WorkspaceBaseDir pgtype.Text        `json:"workspace_base_dir"`
	Capacity         []byte             `json:"capacity"`
	Labels           []byte             `json:"labels"`
	Status           string             `json:"status"`
	Details          []byte             `json:"details"`
	HealthStatus     string             `json:"health_status"`
	Metadata         []byte             `json:"metadata"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	RuntimeNodeID    uuid.UUID          `json:"runtime_node_id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
}

func (q *Queries) UpsertRuntimeCapability(ctx context.Context, arg UpsertRuntimeCapabilityParams) (RuntimeCapability, error) {
	row := q.db.QueryRow(ctx, UpsertRuntimeCapability,
		arg.CapabilityType,
		arg.CapabilityKey,
		arg.ProviderType,
		arg.ProviderVersion,
		arg.BinaryPath,
		arg.Available,
		arg.WorkspaceBaseDir,
		arg.Capacity,
		arg.Labels,
		arg.Status,
		arg.Details,
		arg.HealthStatus,
		arg.Metadata,
		arg.LastSeenAt,
		arg.RuntimeNodeID,
		arg.TenantID,
	)
	var i RuntimeCapability
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeNodeID,
		&i.CapabilityType,
		&i.CapabilityKey,
		&i.ProviderType,
		&i.ProviderVersion,
		&i.BinaryPath,
		&i.Available,
		&i.WorkspaceBaseDir,
		&i.Capacity,
		&i.Labels,
		&i.Status,
		&i.Details,
		&i.HealthStatus,
		&i.Metadata,
		&i.LastSeenAt,
		&i.DisabledAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpsertRuntimeEnrollment = `-- name: UpsertRuntimeEnrollment :one
INSERT INTO runtime_enrollments (
    tenant_id,
    runtime_node_id,
    node_id,
    bootstrap_key_id,
    status,
    request_payload,
    last_hello_at
) SELECT
    rbk.tenant_id,
    NULL::uuid,
    $1::varchar,
    rbk.id,
    'pending'::varchar,
    COALESCE($2::jsonb, '{}'::jsonb),
    $3::timestamptz
FROM runtime_bootstrap_keys rbk
WHERE rbk.id = $4::uuid
  AND rbk.tenant_id = $5::uuid
  AND rbk.status = 'active'
  AND rbk.revoked_at IS NULL
  AND (rbk.expires_at IS NULL OR rbk.expires_at > NOW())
ON CONFLICT (tenant_id, node_id) DO UPDATE SET
    runtime_node_id = CASE
        WHEN runtime_enrollments.status IN ('approved', 'rejected', 'revoked') THEN runtime_enrollments.runtime_node_id
        ELSE EXCLUDED.runtime_node_id
    END,
    bootstrap_key_id = CASE
        WHEN runtime_enrollments.status IN ('approved', 'rejected', 'revoked') THEN runtime_enrollments.bootstrap_key_id
        ELSE EXCLUDED.bootstrap_key_id
    END,
    status = CASE
        WHEN runtime_enrollments.status IN ('approved', 'rejected', 'revoked') THEN runtime_enrollments.status
        ELSE 'pending'
    END,
    request_payload = CASE
        WHEN runtime_enrollments.status IN ('approved', 'rejected', 'revoked') THEN runtime_enrollments.request_payload
        ELSE EXCLUDED.request_payload
    END,
    last_hello_at = EXCLUDED.last_hello_at,
    updated_at = NOW()
RETURNING id, tenant_id, runtime_node_id, node_id, bootstrap_key_id, status, request_payload, approved_by, approved_at, rejected_by, rejected_at, reject_reason, revoked_by, revoked_at, revoke_reason, last_hello_at, created_at, updated_at
`

type UpsertRuntimeEnrollmentParams struct {
	NodeID         string             `json:"node_id"`
	RequestPayload []byte             `json:"request_payload"`
	LastHelloAt    pgtype.Timestamptz `json:"last_hello_at"`
	BootstrapKeyID uuid.UUID          `json:"bootstrap_key_id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
}

func (q *Queries) UpsertRuntimeEnrollment(ctx context.Context, arg UpsertRuntimeEnrollmentParams) (RuntimeEnrollment, error) {
	row := q.db.QueryRow(ctx, UpsertRuntimeEnrollment,
		arg.NodeID,
		arg.RequestPayload,
		arg.LastHelloAt,
		arg.BootstrapKeyID,
		arg.TenantID,
	)
	var i RuntimeEnrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuntimeNodeID,
		&i.NodeID,
		&i.BootstrapKeyID,
		&i.Status,
		&i.RequestPayload,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectReason,
		&i.RevokedBy,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.LastHelloAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
