// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_command.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateRuntimeCommandReceipt = `-- name: CreateRuntimeCommandReceipt :one
WITH inserted AS (
    INSERT INTO runtime_command_receipts (
        tenant_id,
        command_id,
        command_type,
        runtime_node_id,
        node_id,
        resource_type,
        resource_id,
        status,
        payload,
        dispatched_at
    ) VALUES (
        $1::uuid,
        $2::varchar,
        $3::varchar,
        $4::uuid,
        $5::varchar,
        $6::varchar,
        $7::uuid,
        $8::varchar,
        COALESCE($9::jsonb, '{}'::jsonb),
        $10::timestamptz
    )
    ON CONFLICT (tenant_id, command_id) DO UPDATE SET
        command_id = runtime_command_receipts.command_id
    RETURNING id, tenant_id, command_id, command_type, runtime_node_id, node_id, resource_type, resource_id, status, payload, result, error_message, dispatched_at, completed_at, created_at, updated_at
)
SELECT id, tenant_id, command_id, command_type, runtime_node_id, node_id, resource_type, resource_id, status, payload, result, error_message, dispatched_at, completed_at, created_at, updated_at FROM inserted
`

type CreateRuntimeCommandReceiptParams struct {
	TenantID      uuid.UUID          `json:"tenant_id"`
	CommandID     string             `json:"command_id"`
	CommandType   string             `json:"command_type"`
	RuntimeNodeID uuid.UUID          `json:"runtime_node_id"`
	NodeID        string             `json:"node_id"`
	ResourceType  string             `json:"resource_type"`
	ResourceID    uuid.UUID          `json:"resource_id"`
	Status        string             `json:"status"`
	Payload       []byte             `json:"payload"`
	DispatchedAt  pgtype.Timestamptz `json:"dispatched_at"`
}

type CreateRuntimeCommandReceiptRow struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	CommandID     string             `json:"command_id"`
	CommandType   string             `json:"command_type"`
	RuntimeNodeID uuid.UUID          `json:"runtime_node_id"`
	NodeID        string             `json:"node_id"`
	ResourceType  string             `json:"resource_type"`
	ResourceID    uuid.UUID          `json:"resource_id"`
	Status        string             `json:"status"`
	Payload       []byte             `json:"payload"`
	Result        []byte             `json:"result"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	DispatchedAt  pgtype.Timestamptz `json:"dispatched_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateRuntimeCommandReceipt(ctx context.Context, arg CreateRuntimeCommandReceiptParams) (CreateRuntimeCommandReceiptRow, error) {
	row := q.db.QueryRow(ctx, CreateRuntimeCommandReceipt,
		arg.TenantID,
		arg.CommandID,
		arg.CommandType,
		arg.RuntimeNodeID,
		arg.NodeID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Status,
		arg.Payload,
		arg.DispatchedAt,
	)
	var i CreateRuntimeCommandReceiptRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CommandID,
		&i.CommandType,
		&i.RuntimeNodeID,
		&i.NodeID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Payload,
		&i.Result,
		&i.ErrorMessage,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetRuntimeCommandReceiptByCommandID = `-- name: GetRuntimeCommandReceiptByCommandID :one
SELECT id, tenant_id, command_id, command_type, runtime_node_id, node_id, resource_type, resource_id, status, payload, result, error_message, dispatched_at, completed_at, created_at, updated_at
FROM runtime_command_receipts
WHERE tenant_id = $1::uuid
  AND command_id = $2::varchar
`

type GetRuntimeCommandReceiptByCommandIDParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	CommandID string    `json:"command_id"`
}

func (q *Queries) GetRuntimeCommandReceiptByCommandID(ctx context.Context, arg GetRuntimeCommandReceiptByCommandIDParams) (RuntimeCommandReceipt, error) {
	row := q.db.QueryRow(ctx, GetRuntimeCommandReceiptByCommandID, arg.TenantID, arg.CommandID)
	var i RuntimeCommandReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CommandID,
		&i.CommandType,
		&i.RuntimeNodeID,
		&i.NodeID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Payload,
		&i.Result,
		&i.ErrorMessage,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetRuntimeCommandReceiptByCommandIDForUpdate = `-- name: GetRuntimeCommandReceiptByCommandIDForUpdate :one
SELECT id, tenant_id, command_id, command_type, runtime_node_id, node_id, resource_type, resource_id, status, payload, result, error_message, dispatched_at, completed_at, created_at, updated_at
FROM runtime_command_receipts
WHERE tenant_id = $1::uuid
  AND command_id = $2::varchar
FOR UPDATE
`

type GetRuntimeCommandReceiptByCommandIDForUpdateParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	CommandID string    `json:"command_id"`
}

func (q *Queries) GetRuntimeCommandReceiptByCommandIDForUpdate(ctx context.Context, arg GetRuntimeCommandReceiptByCommandIDForUpdateParams) (RuntimeCommandReceipt, error) {
	row := q.db.QueryRow(ctx, GetRuntimeCommandReceiptByCommandIDForUpdate, arg.TenantID, arg.CommandID)
	var i RuntimeCommandReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CommandID,
		&i.CommandType,
		&i.RuntimeNodeID,
		&i.NodeID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Payload,
		&i.Result,
		&i.ErrorMessage,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateRuntimeCommandReceiptStatus = `-- name: UpdateRuntimeCommandReceiptStatus :one
UPDATE runtime_command_receipts
SET status = $1::varchar,
    result = COALESCE($2::jsonb, result),
    error_message = $3::text,
    completed_at = CASE
        WHEN $1::varchar IN ('completed', 'failed', 'cancelled', 'timed_out') THEN COALESCE(completed_at, NOW())
        ELSE completed_at
    END,
    updated_at = NOW()
WHERE tenant_id = $4::uuid
  AND command_id = $5::varchar
RETURNING id, tenant_id, command_id, command_type, runtime_node_id, node_id, resource_type, resource_id, status, payload, result, error_message, dispatched_at, completed_at, created_at, updated_at
`

type UpdateRuntimeCommandReceiptStatusParams struct {
	Status       string      `json:"status"`
	Result       []byte      `json:"result"`
	ErrorMessage pgtype.Text `json:"error_message"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	CommandID    string      `json:"command_id"`
}

func (q *Queries) UpdateRuntimeCommandReceiptStatus(ctx context.Context, arg UpdateRuntimeCommandReceiptStatusParams) (RuntimeCommandReceipt, error) {
	row := q.db.QueryRow(ctx, UpdateRuntimeCommandReceiptStatus,
		arg.Status,
		arg.Result,
		arg.ErrorMessage,
		arg.TenantID,
		arg.CommandID,
	)
	var i RuntimeCommandReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CommandID,
		&i.CommandType,
		&i.RuntimeNodeID,
		&i.NodeID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Payload,
		&i.Result,
		&i.ErrorMessage,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
