// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tasks.sql

package queries

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const cancelTask = `-- name: CancelTask :one
UPDATE tasks
SET status = 'cancelled',
    updated_at = NOW()
WHERE id = $1
  AND status NOT IN ('completed', 'failed', 'cancelled')
RETURNING id, title, description, creator_id, provider_type, target_node_id, assigned_node_id, status, workspace_path, params, priority, created_at, updated_at
`

func (q *Queries) CancelTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, cancelTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatorID,
		&i.ProviderType,
		&i.TargetNodeID,
		&i.AssignedNodeID,
		&i.Status,
		&i.WorkspacePath,
		&i.Params,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (
    title,
    description,
    creator_id,
    provider_type,
    target_node_id,
    status,
    workspace_path,
    params,
    priority
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, title, description, creator_id, provider_type, target_node_id, assigned_node_id, status, workspace_path, params, priority, created_at, updated_at
`

type CreateTaskParams struct {
	Title         string          `json:"title"`
	Description   sql.NullString  `json:"description"`
	CreatorID     sql.NullInt64   `json:"creator_id"`
	ProviderType  string          `json:"provider_type"`
	TargetNodeID  sql.NullString  `json:"target_node_id"`
	Status        string          `json:"status"`
	WorkspacePath sql.NullString  `json:"workspace_path"`
	Params        json.RawMessage `json:"params"`
	Priority      int32           `json:"priority"`
}

// Task Queries
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.CreatorID,
		arg.ProviderType,
		arg.TargetNodeID,
		arg.Status,
		arg.WorkspacePath,
		arg.Params,
		arg.Priority,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatorID,
		&i.ProviderType,
		&i.TargetNodeID,
		&i.AssignedNodeID,
		&i.Status,
		&i.WorkspacePath,
		&i.Params,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskArtifact = `-- name: CreateTaskArtifact :one

INSERT INTO task_artifacts (
    task_id,
    execution_id,
    artifact_type,
    name,
    storage_url,
    size_bytes,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, task_id, execution_id, artifact_type, name, storage_url, size_bytes, metadata, created_at
`

type CreateTaskArtifactParams struct {
	TaskID       int64                 `json:"task_id"`
	ExecutionID  sql.NullInt64         `json:"execution_id"`
	ArtifactType string                `json:"artifact_type"`
	Name         string                `json:"name"`
	StorageUrl   string                `json:"storage_url"`
	SizeBytes    sql.NullInt64         `json:"size_bytes"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
}

// Task Artifact Queries
func (q *Queries) CreateTaskArtifact(ctx context.Context, arg CreateTaskArtifactParams) (TaskArtifact, error) {
	row := q.db.QueryRowContext(ctx, createTaskArtifact,
		arg.TaskID,
		arg.ExecutionID,
		arg.ArtifactType,
		arg.Name,
		arg.StorageUrl,
		arg.SizeBytes,
		arg.Metadata,
	)
	var i TaskArtifact
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ExecutionID,
		&i.ArtifactType,
		&i.Name,
		&i.StorageUrl,
		&i.SizeBytes,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createTaskEvent = `-- name: CreateTaskEvent :one

INSERT INTO task_events (
    task_id,
    execution_id,
    event_type,
    sequence_number,
    payload
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, task_id, execution_id, event_type, sequence_number, payload, created_at
`

type CreateTaskEventParams struct {
	TaskID         int64           `json:"task_id"`
	ExecutionID    sql.NullInt64   `json:"execution_id"`
	EventType      string          `json:"event_type"`
	SequenceNumber int32           `json:"sequence_number"`
	Payload        json.RawMessage `json:"payload"`
}

// Task Event Queries
func (q *Queries) CreateTaskEvent(ctx context.Context, arg CreateTaskEventParams) (TaskEvent, error) {
	row := q.db.QueryRowContext(ctx, createTaskEvent,
		arg.TaskID,
		arg.ExecutionID,
		arg.EventType,
		arg.SequenceNumber,
		arg.Payload,
	)
	var i TaskEvent
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ExecutionID,
		&i.EventType,
		&i.SequenceNumber,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const createTaskExecution = `-- name: CreateTaskExecution :one

INSERT INTO task_executions (
    task_id,
    node_id,
    provider_session_id,
    status,
    started_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, task_id, node_id, provider_session_id, status, started_at, completed_at, result, error_message, created_at
`

type CreateTaskExecutionParams struct {
	TaskID            int64          `json:"task_id"`
	NodeID            string         `json:"node_id"`
	ProviderSessionID sql.NullString `json:"provider_session_id"`
	Status            string         `json:"status"`
	StartedAt         time.Time      `json:"started_at"`
}

// Task Execution Queries
func (q *Queries) CreateTaskExecution(ctx context.Context, arg CreateTaskExecutionParams) (TaskExecution, error) {
	row := q.db.QueryRowContext(ctx, createTaskExecution,
		arg.TaskID,
		arg.NodeID,
		arg.ProviderSessionID,
		arg.Status,
		arg.StartedAt,
	)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.NodeID,
		&i.ProviderSessionID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Result,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const createTaskStateHistory = `-- name: CreateTaskStateHistory :one

INSERT INTO task_state_history (
    task_id,
    from_status,
    to_status,
    changed_by,
    reason
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, task_id, from_status, to_status, changed_by, reason, created_at
`

type CreateTaskStateHistoryParams struct {
	TaskID     int64          `json:"task_id"`
	FromStatus sql.NullString `json:"from_status"`
	ToStatus   string         `json:"to_status"`
	ChangedBy  sql.NullString `json:"changed_by"`
	Reason     sql.NullString `json:"reason"`
}

// Task State History Queries
func (q *Queries) CreateTaskStateHistory(ctx context.Context, arg CreateTaskStateHistoryParams) (TaskStateHistory, error) {
	row := q.db.QueryRowContext(ctx, createTaskStateHistory,
		arg.TaskID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ChangedBy,
		arg.Reason,
	)
	var i TaskStateHistory
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ChangedBy,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTaskArtifact = `-- name: DeleteTaskArtifact :exec
DELETE FROM task_artifacts
WHERE id = $1
`

func (q *Queries) DeleteTaskArtifact(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTaskArtifact, id)
	return err
}

const getLatestTaskEventSequence = `-- name: GetLatestTaskEventSequence :one
SELECT COALESCE(MAX(sequence_number), 0) as max_sequence
FROM task_events
WHERE task_id = $1
`

func (q *Queries) GetLatestTaskEventSequence(ctx context.Context, taskID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestTaskEventSequence, taskID)
	var max_sequence interface{}
	err := row.Scan(&max_sequence)
	return max_sequence, err
}

const getLatestTaskExecution = `-- name: GetLatestTaskExecution :one
SELECT id, task_id, node_id, provider_session_id, status, started_at, completed_at, result, error_message, created_at FROM task_executions
WHERE task_id = $1
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestTaskExecution(ctx context.Context, taskID int64) (TaskExecution, error) {
	row := q.db.QueryRowContext(ctx, getLatestTaskExecution, taskID)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.NodeID,
		&i.ProviderSessionID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Result,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, title, description, creator_id, provider_type, target_node_id, assigned_node_id, status, workspace_path, params, priority, created_at, updated_at FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatorID,
		&i.ProviderType,
		&i.TargetNodeID,
		&i.AssignedNodeID,
		&i.Status,
		&i.WorkspacePath,
		&i.Params,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskArtifact = `-- name: GetTaskArtifact :one
SELECT id, task_id, execution_id, artifact_type, name, storage_url, size_bytes, metadata, created_at FROM task_artifacts
WHERE id = $1
`

func (q *Queries) GetTaskArtifact(ctx context.Context, id int64) (TaskArtifact, error) {
	row := q.db.QueryRowContext(ctx, getTaskArtifact, id)
	var i TaskArtifact
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ExecutionID,
		&i.ArtifactType,
		&i.Name,
		&i.StorageUrl,
		&i.SizeBytes,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskExecution = `-- name: GetTaskExecution :one
SELECT id, task_id, node_id, provider_session_id, status, started_at, completed_at, result, error_message, created_at FROM task_executions
WHERE id = $1
`

func (q *Queries) GetTaskExecution(ctx context.Context, id int64) (TaskExecution, error) {
	row := q.db.QueryRowContext(ctx, getTaskExecution, id)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.NodeID,
		&i.ProviderSessionID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Result,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingTasks = `-- name: ListPendingTasks :many
SELECT id, title, description, creator_id, provider_type, target_node_id, assigned_node_id, status, workspace_path, params, priority, created_at, updated_at FROM tasks
WHERE status = 'pending'
  AND ($1::varchar IS NULL OR provider_type = $1)
  AND (target_node_id IS NULL OR target_node_id = $2::varchar)
ORDER BY priority DESC, created_at ASC
LIMIT $3
`

type ListPendingTasksParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) ListPendingTasks(ctx context.Context, arg ListPendingTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTasks, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatorID,
			&i.ProviderType,
			&i.TargetNodeID,
			&i.AssignedNodeID,
			&i.Status,
			&i.WorkspacePath,
			&i.Params,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskArtifacts = `-- name: ListTaskArtifacts :many
SELECT id, task_id, execution_id, artifact_type, name, storage_url, size_bytes, metadata, created_at FROM task_artifacts
WHERE task_id = $1
  AND ($2::bigint IS NULL OR execution_id = $2)
  AND ($3::varchar IS NULL OR artifact_type = $3)
ORDER BY created_at DESC
`

type ListTaskArtifactsParams struct {
	TaskID  int64  `json:"task_id"`
	Column2 int64  `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) ListTaskArtifacts(ctx context.Context, arg ListTaskArtifactsParams) ([]TaskArtifact, error) {
	rows, err := q.db.QueryContext(ctx, listTaskArtifacts, arg.TaskID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskArtifact{}
	for rows.Next() {
		var i TaskArtifact
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ExecutionID,
			&i.ArtifactType,
			&i.Name,
			&i.StorageUrl,
			&i.SizeBytes,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskEvents = `-- name: ListTaskEvents :many
SELECT id, task_id, execution_id, event_type, sequence_number, payload, created_at FROM task_events
WHERE task_id = $1
  AND ($2::bigint IS NULL OR execution_id = $2)
ORDER BY sequence_number ASC
LIMIT $3 OFFSET $4
`

type ListTaskEventsParams struct {
	TaskID  int64 `json:"task_id"`
	Column2 int64 `json:"column_2"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListTaskEvents(ctx context.Context, arg ListTaskEventsParams) ([]TaskEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTaskEvents,
		arg.TaskID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskEvent{}
	for rows.Next() {
		var i TaskEvent
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ExecutionID,
			&i.EventType,
			&i.SequenceNumber,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskExecutions = `-- name: ListTaskExecutions :many
SELECT id, task_id, node_id, provider_session_id, status, started_at, completed_at, result, error_message, created_at FROM task_executions
WHERE task_id = $1
ORDER BY started_at DESC
`

func (q *Queries) ListTaskExecutions(ctx context.Context, taskID int64) ([]TaskExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTaskExecutions, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskExecution{}
	for rows.Next() {
		var i TaskExecution
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.NodeID,
			&i.ProviderSessionID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Result,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskStateHistory = `-- name: ListTaskStateHistory :many
SELECT id, task_id, from_status, to_status, changed_by, reason, created_at FROM task_state_history
WHERE task_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTaskStateHistory(ctx context.Context, taskID int64) ([]TaskStateHistory, error) {
	rows, err := q.db.QueryContext(ctx, listTaskStateHistory, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskStateHistory{}
	for rows.Next() {
		var i TaskStateHistory
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ChangedBy,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, creator_id, provider_type, target_node_id, assigned_node_id, status, workspace_path, params, priority, created_at, updated_at FROM tasks
WHERE ($1::varchar IS NULL OR status = $1)
  AND ($2::bigint IS NULL OR creator_id = $2)
  AND ($3::varchar IS NULL OR provider_type = $3)
ORDER BY priority DESC, created_at DESC
LIMIT $4 OFFSET $5
`

type ListTasksParams struct {
	Column1 string `json:"column_1"`
	Column2 int64  `json:"column_2"`
	Column3 string `json:"column_3"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatorID,
			&i.ProviderType,
			&i.TargetNodeID,
			&i.AssignedNodeID,
			&i.Status,
			&i.WorkspacePath,
			&i.Params,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskAssignment = `-- name: UpdateTaskAssignment :one
UPDATE tasks
SET assigned_node_id = $2,
    status = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, creator_id, provider_type, target_node_id, assigned_node_id, status, workspace_path, params, priority, created_at, updated_at
`

type UpdateTaskAssignmentParams struct {
	ID             int64          `json:"id"`
	AssignedNodeID sql.NullString `json:"assigned_node_id"`
	Status         string         `json:"status"`
}

func (q *Queries) UpdateTaskAssignment(ctx context.Context, arg UpdateTaskAssignmentParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskAssignment, arg.ID, arg.AssignedNodeID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatorID,
		&i.ProviderType,
		&i.TargetNodeID,
		&i.AssignedNodeID,
		&i.Status,
		&i.WorkspacePath,
		&i.Params,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskExecution = `-- name: UpdateTaskExecution :one
UPDATE task_executions
SET status = $2,
    completed_at = $3,
    result = $4,
    error_message = $5
WHERE id = $1
RETURNING id, task_id, node_id, provider_session_id, status, started_at, completed_at, result, error_message, created_at
`

type UpdateTaskExecutionParams struct {
	ID           int64                 `json:"id"`
	Status       string                `json:"status"`
	CompletedAt  sql.NullTime          `json:"completed_at"`
	Result       pqtype.NullRawMessage `json:"result"`
	ErrorMessage sql.NullString        `json:"error_message"`
}

func (q *Queries) UpdateTaskExecution(ctx context.Context, arg UpdateTaskExecutionParams) (TaskExecution, error) {
	row := q.db.QueryRowContext(ctx, updateTaskExecution,
		arg.ID,
		arg.Status,
		arg.CompletedAt,
		arg.Result,
		arg.ErrorMessage,
	)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.NodeID,
		&i.ProviderSessionID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Result,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, creator_id, provider_type, target_node_id, assigned_node_id, status, workspace_path, params, priority, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatorID,
		&i.ProviderType,
		&i.TargetNodeID,
		&i.AssignedNodeID,
		&i.Status,
		&i.WorkspacePath,
		&i.Params,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskWorkspace = `-- name: UpdateTaskWorkspace :one
UPDATE tasks
SET workspace_path = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, creator_id, provider_type, target_node_id, assigned_node_id, status, workspace_path, params, priority, created_at, updated_at
`

type UpdateTaskWorkspaceParams struct {
	ID            int64          `json:"id"`
	WorkspacePath sql.NullString `json:"workspace_path"`
}

func (q *Queries) UpdateTaskWorkspace(ctx context.Context, arg UpdateTaskWorkspaceParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskWorkspace, arg.ID, arg.WorkspacePath)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatorID,
		&i.ProviderType,
		&i.TargetNodeID,
		&i.AssignedNodeID,
		&i.Status,
		&i.WorkspacePath,
		&i.Params,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
