// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_team_config.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const AddTeamMember = `-- name: AddTeamMember :one
INSERT INTO tenant_members (
    tenant_id,
    team_id,
    principal_type,
    principal_id,
    role,
    status
)
VALUES (
    $1::uuid,
    $2::uuid,
    'user',
    $3::uuid,
    $4::varchar,
    'active'
)
ON CONFLICT (tenant_id, team_id, principal_type, principal_id, role)
DO UPDATE SET
    status = 'active',
    disabled_at = NULL,
    updated_at = NOW()
RETURNING id, tenant_id, team_id, principal_type, principal_id, role, status, disabled_at, created_at, updated_at
`

type AddTeamMemberParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	TeamID   uuid.UUID `json:"team_id"`
	UserID   uuid.UUID `json:"user_id"`
	Role     string    `json:"role"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TenantMember, error) {
	row := q.db.QueryRow(ctx, AddTeamMember,
		arg.TenantID,
		arg.TeamID,
		arg.UserID,
		arg.Role,
	)
	var i TenantMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Role,
		&i.Status,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const AddTeamOwnerMembership = `-- name: AddTeamOwnerMembership :one
INSERT INTO tenant_members (
    tenant_id,
    team_id,
    principal_type,
    principal_id,
    role,
    status
) VALUES (
    $1::uuid,
    $2::uuid,
    'user',
    $3::uuid,
    'owner',
    'active'
)
ON CONFLICT (tenant_id, team_id, principal_type, principal_id, role)
DO UPDATE SET
    status = 'active',
    disabled_at = NULL,
    updated_at = NOW()
RETURNING id, tenant_id, team_id, principal_type, principal_id, role, status, disabled_at, created_at, updated_at
`

type AddTeamOwnerMembershipParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	TeamID   uuid.UUID `json:"team_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) AddTeamOwnerMembership(ctx context.Context, arg AddTeamOwnerMembershipParams) (TenantMember, error) {
	row := q.db.QueryRow(ctx, AddTeamOwnerMembership, arg.TenantID, arg.TeamID, arg.UserID)
	var i TenantMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Role,
		&i.Status,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CountTeamOwners = `-- name: CountTeamOwners :one
SELECT COUNT(*)::integer
FROM tenant_members
WHERE tenant_id = $1::uuid
  AND team_id = $2::uuid
  AND principal_type = 'user'
  AND role = 'owner'
  AND status = 'active'
  AND disabled_at IS NULL
`

type CountTeamOwnersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	TeamID   uuid.UUID `json:"team_id"`
}

func (q *Queries) CountTeamOwners(ctx context.Context, arg CountTeamOwnersParams) (int32, error) {
	row := q.db.QueryRow(ctx, CountTeamOwners, arg.TenantID, arg.TeamID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const CreateTeamMemberRoleRequest = `-- name: CreateTeamMemberRoleRequest :one
INSERT INTO tenant_team_member_role_requests (
    tenant_id,
    team_id,
    target_user_id,
    requested_role,
    requested_by,
    reason
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::varchar,
    $5::uuid,
    $6::text
)
RETURNING id, tenant_id, team_id, target_user_id, requested_role, requested_by, status, reason, decided_by, decided_at, decision_reason, created_at, updated_at
`

type CreateTeamMemberRoleRequestParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	TeamID        uuid.UUID `json:"team_id"`
	TargetUserID  uuid.UUID `json:"target_user_id"`
	RequestedRole string    `json:"requested_role"`
	RequestedBy   uuid.UUID `json:"requested_by"`
	Reason        string    `json:"reason"`
}

func (q *Queries) CreateTeamMemberRoleRequest(ctx context.Context, arg CreateTeamMemberRoleRequestParams) (TenantTeamMemberRoleRequest, error) {
	row := q.db.QueryRow(ctx, CreateTeamMemberRoleRequest,
		arg.TenantID,
		arg.TeamID,
		arg.TargetUserID,
		arg.RequestedRole,
		arg.RequestedBy,
		arg.Reason,
	)
	var i TenantTeamMemberRoleRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.TargetUserID,
		&i.RequestedRole,
		&i.RequestedBy,
		&i.Status,
		&i.Reason,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateTenantTeam = `-- name: CreateTenantTeam :one
INSERT INTO tenant_teams (tenant_id, slug, name, status, human_owner_user_ids, metadata)
VALUES (
    $1::uuid,
    $2::varchar,
    $3::varchar,
    $4::varchar,
    $5::uuid[],
    COALESCE($6::jsonb, '{}'::jsonb)
)
RETURNING id, tenant_id, slug, name, status, metadata, archived_at, disabled_at, deleted_at, created_at, updated_at, human_owner_user_ids, constitution, delete_requested_by
`

type CreateTenantTeamParams struct {
	TenantID          uuid.UUID   `json:"tenant_id"`
	Slug              string      `json:"slug"`
	Name              string      `json:"name"`
	Status            string      `json:"status"`
	HumanOwnerUserIds []uuid.UUID `json:"human_owner_user_ids"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) CreateTenantTeam(ctx context.Context, arg CreateTenantTeamParams) (TenantTeam, error) {
	row := q.db.QueryRow(ctx, CreateTenantTeam,
		arg.TenantID,
		arg.Slug,
		arg.Name,
		arg.Status,
		arg.HumanOwnerUserIds,
		arg.Metadata,
	)
	var i TenantTeam
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.ArchivedAt,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HumanOwnerUserIds,
		&i.Constitution,
		&i.DeleteRequestedBy,
	)
	return i, err
}

const DecideTeamMemberRoleRequest = `-- name: DecideTeamMemberRoleRequest :one
UPDATE tenant_team_member_role_requests
SET
  status = $1::varchar,
  decided_by = $2::uuid,
  decided_at = NOW(),
  decision_reason = $3::text,
  updated_at = NOW()
WHERE id = $4::uuid
  AND tenant_id = $5::uuid
  AND team_id = $6::uuid
  AND status = 'pending'
  AND $1::varchar IN ('approved', 'rejected')
RETURNING id, tenant_id, team_id, target_user_id, requested_role, requested_by, status, reason, decided_by, decided_at, decision_reason, created_at, updated_at
`

type DecideTeamMemberRoleRequestParams struct {
	Status         string    `json:"status"`
	DecidedBy      uuid.UUID `json:"decided_by"`
	DecisionReason string    `json:"decision_reason"`
	ID             uuid.UUID `json:"id"`
	TenantID       uuid.UUID `json:"tenant_id"`
	TeamID         uuid.UUID `json:"team_id"`
}

func (q *Queries) DecideTeamMemberRoleRequest(ctx context.Context, arg DecideTeamMemberRoleRequestParams) (TenantTeamMemberRoleRequest, error) {
	row := q.db.QueryRow(ctx, DecideTeamMemberRoleRequest,
		arg.Status,
		arg.DecidedBy,
		arg.DecisionReason,
		arg.ID,
		arg.TenantID,
		arg.TeamID,
	)
	var i TenantTeamMemberRoleRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.TargetUserID,
		&i.RequestedRole,
		&i.RequestedBy,
		&i.Status,
		&i.Reason,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DisableTeamMemberRole = `-- name: DisableTeamMemberRole :one
UPDATE tenant_members
SET
  status = 'disabled',
  disabled_at = COALESCE(disabled_at, NOW()),
  updated_at = NOW()
WHERE id = $1::uuid
  AND tenant_id = $2::uuid
  AND team_id = $3::uuid
  AND principal_type = 'user'
  AND disabled_at IS NULL
RETURNING id, tenant_id, team_id, principal_type, principal_id, role, status, disabled_at, created_at, updated_at
`

type DisableTeamMemberRoleParams struct {
	MembershipID uuid.UUID `json:"membership_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	TeamID       uuid.UUID `json:"team_id"`
}

func (q *Queries) DisableTeamMemberRole(ctx context.Context, arg DisableTeamMemberRoleParams) (TenantMember, error) {
	row := q.db.QueryRow(ctx, DisableTeamMemberRole, arg.MembershipID, arg.TenantID, arg.TeamID)
	var i TenantMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Role,
		&i.Status,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetActiveTenantUserForTeamCreate = `-- name: GetActiveTenantUserForTeamCreate :one
SELECT au.id, au.username, au.display_name, au.email, au.status
FROM auth_users au
JOIN tenant_members tm ON tm.principal_id = au.id
WHERE au.id = $1::uuid
  AND au.status = 'active'
  AND au.deleted_at IS NULL
  AND tm.tenant_id = $2::uuid
  AND tm.principal_type = 'user'
  AND tm.status = 'active'
  AND tm.disabled_at IS NULL
LIMIT 1
`

type GetActiveTenantUserForTeamCreateParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetActiveTenantUserForTeamCreateRow struct {
	ID          uuid.UUID   `json:"id"`
	Username    string      `json:"username"`
	DisplayName pgtype.Text `json:"display_name"`
	Email       pgtype.Text `json:"email"`
	Status      string      `json:"status"`
}

func (q *Queries) GetActiveTenantUserForTeamCreate(ctx context.Context, arg GetActiveTenantUserForTeamCreateParams) (GetActiveTenantUserForTeamCreateRow, error) {
	row := q.db.QueryRow(ctx, GetActiveTenantUserForTeamCreate, arg.ID, arg.TenantID)
	var i GetActiveTenantUserForTeamCreateRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Status,
	)
	return i, err
}

const GetTeamMember = `-- name: GetTeamMember :one
SELECT
  tm.id AS membership_id,
  tm.tenant_id,
  tm.team_id,
  tm.principal_id AS user_id,
  au.username,
  au.display_name,
  au.email,
  au.status AS account_status,
  au.avatar_provider,
  au.avatar_style,
  au.avatar_seed,
  au.avatar_options,
  tm.role,
  tm.status AS membership_status,
  tm.disabled_at,
  tm.created_at,
  tm.updated_at
FROM tenant_members tm
JOIN auth_users au ON au.id = tm.principal_id
WHERE tm.id = $1::uuid
  AND tm.tenant_id = $2::uuid
  AND tm.team_id = $3::uuid
  AND tm.principal_type = 'user'
  AND tm.status = 'active'
  AND tm.disabled_at IS NULL
  AND au.deleted_at IS NULL
`

type GetTeamMemberParams struct {
	MembershipID uuid.UUID `json:"membership_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	TeamID       uuid.UUID `json:"team_id"`
}

type GetTeamMemberRow struct {
	MembershipID     uuid.UUID          `json:"membership_id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	TeamID           uuid.NullUUID      `json:"team_id"`
	UserID           uuid.UUID          `json:"user_id"`
	Username         string             `json:"username"`
	DisplayName      pgtype.Text        `json:"display_name"`
	Email            pgtype.Text        `json:"email"`
	AccountStatus    string             `json:"account_status"`
	AvatarProvider   string             `json:"avatar_provider"`
	AvatarStyle      string             `json:"avatar_style"`
	AvatarSeed       pgtype.Text        `json:"avatar_seed"`
	AvatarOptions    []byte             `json:"avatar_options"`
	Role             string             `json:"role"`
	MembershipStatus string             `json:"membership_status"`
	DisabledAt       pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (GetTeamMemberRow, error) {
	row := q.db.QueryRow(ctx, GetTeamMember, arg.MembershipID, arg.TenantID, arg.TeamID)
	var i GetTeamMemberRow
	err := row.Scan(
		&i.MembershipID,
		&i.TenantID,
		&i.TeamID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.AccountStatus,
		&i.AvatarProvider,
		&i.AvatarStyle,
		&i.AvatarSeed,
		&i.AvatarOptions,
		&i.Role,
		&i.MembershipStatus,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetTeamMemberRoleRequest = `-- name: GetTeamMemberRoleRequest :one
SELECT id, tenant_id, team_id, target_user_id, requested_role, requested_by, status, reason, decided_by, decided_at, decision_reason, created_at, updated_at
FROM tenant_team_member_role_requests
WHERE id = $1::uuid
  AND tenant_id = $2::uuid
  AND team_id = $3::uuid
  AND status = 'pending'
`

type GetTeamMemberRoleRequestParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	TeamID   uuid.UUID `json:"team_id"`
}

func (q *Queries) GetTeamMemberRoleRequest(ctx context.Context, arg GetTeamMemberRoleRequestParams) (TenantTeamMemberRoleRequest, error) {
	row := q.db.QueryRow(ctx, GetTeamMemberRoleRequest, arg.ID, arg.TenantID, arg.TeamID)
	var i TenantTeamMemberRoleRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.TargetUserID,
		&i.RequestedRole,
		&i.RequestedBy,
		&i.Status,
		&i.Reason,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetTenantTeam = `-- name: GetTenantTeam :one
SELECT id, tenant_id, slug, name, status, metadata, archived_at, disabled_at, deleted_at, created_at, updated_at, human_owner_user_ids, constitution, delete_requested_by
FROM tenant_teams
WHERE id = $1::uuid
  AND tenant_id = $2::uuid
  AND deleted_at IS NULL
`

type GetTenantTeamParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTenantTeam(ctx context.Context, arg GetTenantTeamParams) (TenantTeam, error) {
	row := q.db.QueryRow(ctx, GetTenantTeam, arg.ID, arg.TenantID)
	var i TenantTeam
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.ArchivedAt,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HumanOwnerUserIds,
		&i.Constitution,
		&i.DeleteRequestedBy,
	)
	return i, err
}

const GetTenantTeamSummary = `-- name: GetTenantTeamSummary :one
WITH member_counts AS (
  SELECT tenant_id, team_id, COUNT(DISTINCT principal_id)::integer AS member_count
  FROM tenant_members
  WHERE team_id IS NOT NULL
    AND principal_type = 'user'
    AND status = 'active'
    AND disabled_at IS NULL
  GROUP BY tenant_id, team_id
),
employee_counts AS (
  SELECT tenant_id, team_id, COUNT(*)::integer AS digital_employee_count
  FROM digital_employees
  WHERE team_id IS NOT NULL
    AND deleted_at IS NULL
    AND archived_at IS NULL
  GROUP BY tenant_id, team_id
)
SELECT
  tt.id, tt.tenant_id, tt.slug, tt.name, tt.status, tt.metadata, tt.archived_at, tt.disabled_at, tt.deleted_at, tt.created_at, tt.updated_at, tt.human_owner_user_ids, tt.constitution, tt.delete_requested_by,
  COALESCE(owner_agg.owners, '[]'::json) AS human_owners,
  COALESCE(mc.member_count, 0)::integer AS member_count,
  COALESCE(ec.digital_employee_count, 0)::integer AS digital_employee_count,
  0::integer AS capability_count,
  0::integer AS pending_draft_count,
  CASE
    WHEN tt.constitution = '{}'::jsonb THEN 'not_configured'
    ELSE 'active'
  END::varchar AS governance_status,
  ''::varchar AS risk_summary
FROM tenant_teams tt
LEFT JOIN member_counts mc ON mc.tenant_id = tt.tenant_id AND mc.team_id = tt.id
LEFT JOIN employee_counts ec ON ec.tenant_id = tt.tenant_id AND ec.team_id = tt.id
LEFT JOIN LATERAL (
  SELECT json_agg(json_build_object(
    'id', o.id,
    'username', o.username,
    'display_name', o.display_name,
    'email', o.email,
    'status', o.status,
    'avatar_provider', o.avatar_provider,
    'avatar_style', o.avatar_style,
    'avatar_seed', o.avatar_seed,
    'avatar_options', o.avatar_options
  )) AS owners
  FROM auth_users o
  WHERE o.id = ANY(tt.human_owner_user_ids)
    AND o.deleted_at IS NULL
) owner_agg ON true
WHERE tt.id = $1::uuid
  AND tt.tenant_id = $2::uuid
  AND tt.deleted_at IS NULL
`

type GetTenantTeamSummaryParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetTenantTeamSummaryRow struct {
	ID                   uuid.UUID          `json:"id"`
	TenantID             uuid.UUID          `json:"tenant_id"`
	Slug                 string             `json:"slug"`
	Name                 string             `json:"name"`
	Status               string             `json:"status"`
	Metadata             []byte             `json:"metadata"`
	ArchivedAt           pgtype.Timestamptz `json:"archived_at"`
	DisabledAt           pgtype.Timestamptz `json:"disabled_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	HumanOwnerUserIds    []uuid.UUID        `json:"human_owner_user_ids"`
	Constitution         []byte             `json:"constitution"`
	DeleteRequestedBy    uuid.NullUUID      `json:"delete_requested_by"`
	HumanOwners          []byte             `json:"human_owners"`
	MemberCount          int32              `json:"member_count"`
	DigitalEmployeeCount int32              `json:"digital_employee_count"`
	CapabilityCount      int32              `json:"capability_count"`
	PendingDraftCount    int32              `json:"pending_draft_count"`
	GovernanceStatus     string             `json:"governance_status"`
	RiskSummary          string             `json:"risk_summary"`
}

func (q *Queries) GetTenantTeamSummary(ctx context.Context, arg GetTenantTeamSummaryParams) (GetTenantTeamSummaryRow, error) {
	row := q.db.QueryRow(ctx, GetTenantTeamSummary, arg.ID, arg.TenantID)
	var i GetTenantTeamSummaryRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.ArchivedAt,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HumanOwnerUserIds,
		&i.Constitution,
		&i.DeleteRequestedBy,
		&i.HumanOwners,
		&i.MemberCount,
		&i.DigitalEmployeeCount,
		&i.CapabilityCount,
		&i.PendingDraftCount,
		&i.GovernanceStatus,
		&i.RiskSummary,
	)
	return i, err
}

const ListTeamMemberRoleRequests = `-- name: ListTeamMemberRoleRequests :many
SELECT id, tenant_id, team_id, target_user_id, requested_role, requested_by, status, reason, decided_by, decided_at, decision_reason, created_at, updated_at
FROM tenant_team_member_role_requests
WHERE tenant_id = $1::uuid
  AND team_id = $2::uuid
  AND ($3::varchar IS NULL OR status = $3::varchar)
ORDER BY created_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListTeamMemberRoleRequestsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	TeamID   uuid.UUID   `json:"team_id"`
	Status   pgtype.Text `json:"status"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListTeamMemberRoleRequests(ctx context.Context, arg ListTeamMemberRoleRequestsParams) ([]TenantTeamMemberRoleRequest, error) {
	rows, err := q.db.Query(ctx, ListTeamMemberRoleRequests,
		arg.TenantID,
		arg.TeamID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantTeamMemberRoleRequest{}
	for rows.Next() {
		var i TenantTeamMemberRoleRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TeamID,
			&i.TargetUserID,
			&i.RequestedRole,
			&i.RequestedBy,
			&i.Status,
			&i.Reason,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecisionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTeamMembers = `-- name: ListTeamMembers :many
SELECT
  tm.id AS membership_id,
  tm.tenant_id,
  tm.team_id,
  tm.principal_id AS user_id,
  au.username,
  au.display_name,
  au.email,
  au.status AS account_status,
  au.avatar_provider,
  au.avatar_style,
  au.avatar_seed,
  au.avatar_options,
  tm.role,
  tm.status AS membership_status,
  tm.disabled_at,
  tm.created_at,
  tm.updated_at
FROM tenant_members tm
JOIN auth_users au ON au.id = tm.principal_id
WHERE tm.tenant_id = $1::uuid
  AND tm.team_id = $2::uuid
  AND tm.principal_type = 'user'
  AND tm.status = 'active'
  AND tm.disabled_at IS NULL
  AND au.deleted_at IS NULL
ORDER BY
  CASE tm.role WHEN 'owner' THEN 1 WHEN 'admin' THEN 2 WHEN 'approver' THEN 3 WHEN 'member' THEN 4 WHEN 'viewer' THEN 5 ELSE 6 END,
  au.display_name NULLS LAST,
  au.username
LIMIT $4 OFFSET $3
`

type ListTeamMembersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	TeamID   uuid.UUID `json:"team_id"`
	Offset   int32     `json:"offset"`
	Limit    int32     `json:"limit"`
}

type ListTeamMembersRow struct {
	MembershipID     uuid.UUID          `json:"membership_id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	TeamID           uuid.NullUUID      `json:"team_id"`
	UserID           uuid.UUID          `json:"user_id"`
	Username         string             `json:"username"`
	DisplayName      pgtype.Text        `json:"display_name"`
	Email            pgtype.Text        `json:"email"`
	AccountStatus    string             `json:"account_status"`
	AvatarProvider   string             `json:"avatar_provider"`
	AvatarStyle      string             `json:"avatar_style"`
	AvatarSeed       pgtype.Text        `json:"avatar_seed"`
	AvatarOptions    []byte             `json:"avatar_options"`
	Role             string             `json:"role"`
	MembershipStatus string             `json:"membership_status"`
	DisabledAt       pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, arg ListTeamMembersParams) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, ListTeamMembers,
		arg.TenantID,
		arg.TeamID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.TenantID,
			&i.TeamID,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.AccountStatus,
			&i.AvatarProvider,
			&i.AvatarStyle,
			&i.AvatarSeed,
			&i.AvatarOptions,
			&i.Role,
			&i.MembershipStatus,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTenantTeamSummaries = `-- name: ListTenantTeamSummaries :many
WITH member_counts AS (
  SELECT tenant_id, team_id, COUNT(DISTINCT principal_id)::integer AS member_count
  FROM tenant_members
  WHERE team_id IS NOT NULL
    AND principal_type = 'user'
    AND status = 'active'
    AND disabled_at IS NULL
  GROUP BY tenant_id, team_id
),
employee_counts AS (
  SELECT tenant_id, team_id, COUNT(*)::integer AS digital_employee_count
  FROM digital_employees
  WHERE team_id IS NOT NULL
    AND deleted_at IS NULL
    AND archived_at IS NULL
  GROUP BY tenant_id, team_id
)
SELECT
  tt.id, tt.tenant_id, tt.slug, tt.name, tt.status, tt.metadata, tt.archived_at, tt.disabled_at, tt.deleted_at, tt.created_at, tt.updated_at, tt.human_owner_user_ids, tt.constitution, tt.delete_requested_by,
  COALESCE(owner_agg.owners, '[]'::json) AS human_owners,
  COALESCE(mc.member_count, 0)::integer AS member_count,
  COALESCE(ec.digital_employee_count, 0)::integer AS digital_employee_count,
  0::integer AS capability_count,
  0::integer AS pending_draft_count,
  CASE
    WHEN tt.constitution = '{}'::jsonb THEN 'not_configured'
    ELSE 'active'
  END::varchar AS governance_status,
  ''::varchar AS risk_summary
FROM tenant_teams tt
LEFT JOIN member_counts mc ON mc.tenant_id = tt.tenant_id AND mc.team_id = tt.id
LEFT JOIN employee_counts ec ON ec.tenant_id = tt.tenant_id AND ec.team_id = tt.id
LEFT JOIN LATERAL (
  SELECT json_agg(json_build_object(
    'id', o.id,
    'username', o.username,
    'display_name', o.display_name,
    'email', o.email,
    'status', o.status,
    'avatar_provider', o.avatar_provider,
    'avatar_style', o.avatar_style,
    'avatar_seed', o.avatar_seed,
    'avatar_options', o.avatar_options
  )) AS owners
  FROM auth_users o
  WHERE o.id = ANY(tt.human_owner_user_ids)
    AND o.deleted_at IS NULL
) owner_agg ON true
WHERE tt.tenant_id = $1::uuid
  AND tt.deleted_at IS NULL
  AND ($2::varchar IS NULL OR tt.status = $2::varchar)
  AND ($2::varchar IS NOT NULL OR tt.status <> 'archived')
  AND (
    $3::varchar IS NULL
    OR CASE
      WHEN tt.constitution = '{}'::jsonb THEN 'not_configured'
      ELSE 'active'
    END = $3::varchar
  )
  AND (
    $4::varchar IS NULL
    OR tt.name ILIKE '%' || $4::varchar || '%'
    OR tt.slug ILIKE '%' || $4::varchar || '%'
    OR EXISTS (
      SELECT 1 FROM auth_users o
      WHERE o.id = ANY(tt.human_owner_user_ids)
        AND o.deleted_at IS NULL
        AND (
          o.username ILIKE '%' || $4::varchar || '%'
          OR o.display_name ILIKE '%' || $4::varchar || '%'
          OR o.email ILIKE '%' || $4::varchar || '%'
        )
    )
  )
ORDER BY tt.updated_at DESC, tt.created_at DESC
LIMIT $6 OFFSET $5
`

type ListTenantTeamSummariesParams struct {
	TenantID         uuid.UUID   `json:"tenant_id"`
	Status           pgtype.Text `json:"status"`
	GovernanceStatus pgtype.Text `json:"governance_status"`
	Q                pgtype.Text `json:"q"`
	Offset           int32       `json:"offset"`
	Limit            int32       `json:"limit"`
}

type ListTenantTeamSummariesRow struct {
	ID                   uuid.UUID          `json:"id"`
	TenantID             uuid.UUID          `json:"tenant_id"`
	Slug                 string             `json:"slug"`
	Name                 string             `json:"name"`
	Status               string             `json:"status"`
	Metadata             []byte             `json:"metadata"`
	ArchivedAt           pgtype.Timestamptz `json:"archived_at"`
	DisabledAt           pgtype.Timestamptz `json:"disabled_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	HumanOwnerUserIds    []uuid.UUID        `json:"human_owner_user_ids"`
	Constitution         []byte             `json:"constitution"`
	DeleteRequestedBy    uuid.NullUUID      `json:"delete_requested_by"`
	HumanOwners          []byte             `json:"human_owners"`
	MemberCount          int32              `json:"member_count"`
	DigitalEmployeeCount int32              `json:"digital_employee_count"`
	CapabilityCount      int32              `json:"capability_count"`
	PendingDraftCount    int32              `json:"pending_draft_count"`
	GovernanceStatus     string             `json:"governance_status"`
	RiskSummary          string             `json:"risk_summary"`
}

func (q *Queries) ListTenantTeamSummaries(ctx context.Context, arg ListTenantTeamSummariesParams) ([]ListTenantTeamSummariesRow, error) {
	rows, err := q.db.Query(ctx, ListTenantTeamSummaries,
		arg.TenantID,
		arg.Status,
		arg.GovernanceStatus,
		arg.Q,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantTeamSummariesRow{}
	for rows.Next() {
		var i ListTenantTeamSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.Metadata,
			&i.ArchivedAt,
			&i.DisabledAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HumanOwnerUserIds,
			&i.Constitution,
			&i.DeleteRequestedBy,
			&i.HumanOwners,
			&i.MemberCount,
			&i.DigitalEmployeeCount,
			&i.CapabilityCount,
			&i.PendingDraftCount,
			&i.GovernanceStatus,
			&i.RiskSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTenantTeams = `-- name: ListTenantTeams :many
SELECT id, tenant_id, slug, name, status, metadata, archived_at, disabled_at, deleted_at, created_at, updated_at, human_owner_user_ids, constitution, delete_requested_by
FROM tenant_teams
WHERE tenant_id = $1::uuid
  AND deleted_at IS NULL
  AND ($2::varchar IS NULL OR status = $2::varchar)
  AND ($2::varchar IS NOT NULL OR status <> 'archived')
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListTenantTeamsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Status   pgtype.Text `json:"status"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListTenantTeams(ctx context.Context, arg ListTenantTeamsParams) ([]TenantTeam, error) {
	rows, err := q.db.Query(ctx, ListTenantTeams,
		arg.TenantID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantTeam{}
	for rows.Next() {
		var i TenantTeam
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.Metadata,
			&i.ArchivedAt,
			&i.DisabledAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HumanOwnerUserIds,
			&i.Constitution,
			&i.DeleteRequestedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateTenantTeam = `-- name: UpdateTenantTeam :one
UPDATE tenant_teams
SET
  slug = $1::varchar,
  name = $2::varchar,
  human_owner_user_ids = COALESCE($3::uuid[], human_owner_user_ids),
  metadata = COALESCE($4::jsonb, '{}'::jsonb),
  updated_at = NOW()
WHERE id = $5::uuid
  AND tenant_id = $6::uuid
  AND deleted_at IS NULL
RETURNING id, tenant_id, slug, name, status, metadata, archived_at, disabled_at, deleted_at, created_at, updated_at, human_owner_user_ids, constitution, delete_requested_by
`

type UpdateTenantTeamParams struct {
	Slug              string      `json:"slug"`
	Name              string      `json:"name"`
	HumanOwnerUserIds []uuid.UUID `json:"human_owner_user_ids"`
	Metadata          []byte      `json:"metadata"`
	ID                uuid.UUID   `json:"id"`
	TenantID          uuid.UUID   `json:"tenant_id"`
}

func (q *Queries) UpdateTenantTeam(ctx context.Context, arg UpdateTenantTeamParams) (TenantTeam, error) {
	row := q.db.QueryRow(ctx, UpdateTenantTeam,
		arg.Slug,
		arg.Name,
		arg.HumanOwnerUserIds,
		arg.Metadata,
		arg.ID,
		arg.TenantID,
	)
	var i TenantTeam
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.ArchivedAt,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HumanOwnerUserIds,
		&i.Constitution,
		&i.DeleteRequestedBy,
	)
	return i, err
}

const UpdateTenantTeamConstitution = `-- name: UpdateTenantTeamConstitution :one
UPDATE tenant_teams
SET
  constitution = COALESCE($1::jsonb, '{}'::jsonb),
  updated_at = NOW()
WHERE id = $2::uuid
  AND tenant_id = $3::uuid
  AND deleted_at IS NULL
RETURNING id, tenant_id, slug, name, status, metadata, archived_at, disabled_at, deleted_at, created_at, updated_at, human_owner_user_ids, constitution, delete_requested_by
`

type UpdateTenantTeamConstitutionParams struct {
	Constitution []byte    `json:"constitution"`
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateTenantTeamConstitution(ctx context.Context, arg UpdateTenantTeamConstitutionParams) (TenantTeam, error) {
	row := q.db.QueryRow(ctx, UpdateTenantTeamConstitution, arg.Constitution, arg.ID, arg.TenantID)
	var i TenantTeam
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.ArchivedAt,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HumanOwnerUserIds,
		&i.Constitution,
		&i.DeleteRequestedBy,
	)
	return i, err
}
