// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_membership.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const CountActiveTenantLevelMemberships = `-- name: CountActiveTenantLevelMemberships :one
SELECT COUNT(*)::integer AS member_count
FROM tenant_members
WHERE tenant_id = $1::uuid
  AND team_id IS NULL
  AND principal_type = 'user'
  AND status = 'active'
  AND disabled_at IS NULL
`

func (q *Queries) CountActiveTenantLevelMemberships(ctx context.Context, tenantID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, CountActiveTenantLevelMemberships, tenantID)
	var member_count int32
	err := row.Scan(&member_count)
	return member_count, err
}

const CountActiveTenantLevelOwners = `-- name: CountActiveTenantLevelOwners :one
SELECT COUNT(*)::integer AS owner_count
FROM tenant_members
WHERE tenant_id = $1::uuid
  AND team_id IS NULL
  AND principal_type = 'user'
  AND role = 'owner'
  AND status = 'active'
  AND disabled_at IS NULL
`

func (q *Queries) CountActiveTenantLevelOwners(ctx context.Context, tenantID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, CountActiveTenantLevelOwners, tenantID)
	var owner_count int32
	err := row.Scan(&owner_count)
	return owner_count, err
}

const CountActiveUsersWithoutTenantMembership = `-- name: CountActiveUsersWithoutTenantMembership :one
SELECT COUNT(*)::integer AS ghost_count
FROM auth_users au
WHERE au.deleted_at IS NULL
  AND au.status = 'active'
  AND NOT EXISTS (
    SELECT 1
    FROM tenant_members tm
    WHERE tm.principal_type = 'user'
      AND tm.principal_id = au.id
      AND tm.tenant_id = $1::uuid
      AND tm.team_id IS NULL
      AND tm.status = 'active'
      AND tm.disabled_at IS NULL
  )
`

func (q *Queries) CountActiveUsersWithoutTenantMembership(ctx context.Context, tenantID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, CountActiveUsersWithoutTenantMembership, tenantID)
	var ghost_count int32
	err := row.Scan(&ghost_count)
	return ghost_count, err
}

const DisableTenantLevelMembership = `-- name: DisableTenantLevelMembership :one
UPDATE tenant_members
SET
  status = 'disabled',
  disabled_at = COALESCE(disabled_at, NOW()),
  updated_at = NOW()
WHERE id = $1::uuid
  AND tenant_id = $2::uuid
  AND team_id IS NULL
  AND disabled_at IS NULL
RETURNING id, tenant_id, team_id, principal_type, principal_id, role, status, disabled_at, created_at, updated_at
`

type DisableTenantLevelMembershipParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DisableTenantLevelMembership(ctx context.Context, arg DisableTenantLevelMembershipParams) (TenantMember, error) {
	row := q.db.QueryRow(ctx, DisableTenantLevelMembership, arg.ID, arg.TenantID)
	var i TenantMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Role,
		&i.Status,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetActiveTenantLevelMembership = `-- name: GetActiveTenantLevelMembership :one
SELECT id, tenant_id, team_id, principal_type, principal_id, role, status, disabled_at, created_at, updated_at
FROM tenant_members
WHERE tenant_id = $1::uuid
  AND team_id IS NULL
  AND principal_type = 'user'
  AND principal_id = $2::uuid
  AND status = 'active'
  AND disabled_at IS NULL
ORDER BY
  CASE role
    WHEN 'owner' THEN 1
    WHEN 'admin' THEN 2
    WHEN 'member' THEN 3
    WHEN 'viewer' THEN 4
    ELSE 5
  END
LIMIT 1
`

type GetActiveTenantLevelMembershipParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetActiveTenantLevelMembership(ctx context.Context, arg GetActiveTenantLevelMembershipParams) (TenantMember, error) {
	row := q.db.QueryRow(ctx, GetActiveTenantLevelMembership, arg.TenantID, arg.UserID)
	var i TenantMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Role,
		&i.Status,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const InsertTenantLevelMembership = `-- name: InsertTenantLevelMembership :one
INSERT INTO tenant_members (
    tenant_id,
    team_id,
    principal_type,
    principal_id,
    role,
    status
) VALUES (
    $1::uuid,
    NULL,
    'user',
    $2::uuid,
    $3::varchar,
    'active'
)
RETURNING id, tenant_id, team_id, principal_type, principal_id, role, status, disabled_at, created_at, updated_at
`

type InsertTenantLevelMembershipParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	Role     string    `json:"role"`
}

func (q *Queries) InsertTenantLevelMembership(ctx context.Context, arg InsertTenantLevelMembershipParams) (TenantMember, error) {
	row := q.db.QueryRow(ctx, InsertTenantLevelMembership, arg.TenantID, arg.UserID, arg.Role)
	var i TenantMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Role,
		&i.Status,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateTenantLevelMembershipRole = `-- name: UpdateTenantLevelMembershipRole :one
UPDATE tenant_members
SET
  role = $1::varchar,
  status = 'active',
  disabled_at = NULL,
  updated_at = NOW()
WHERE id = $2::uuid
  AND tenant_id = $3::uuid
  AND team_id IS NULL
RETURNING id, tenant_id, team_id, principal_type, principal_id, role, status, disabled_at, created_at, updated_at
`

type UpdateTenantLevelMembershipRoleParams struct {
	Role     string    `json:"role"`
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateTenantLevelMembershipRole(ctx context.Context, arg UpdateTenantLevelMembershipRoleParams) (TenantMember, error) {
	row := q.db.QueryRow(ctx, UpdateTenantLevelMembershipRole, arg.Role, arg.ID, arg.TenantID)
	var i TenantMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Role,
		&i.Status,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
