// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_team.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const BindDigitalEmployeeToTeam = `-- name: BindDigitalEmployeeToTeam :one
UPDATE digital_employees
SET team_id = $1::uuid,
    updated_at = NOW()
WHERE id = $2::uuid
  AND tenant_id = $3::uuid
  AND team_id IS NULL
  AND deleted_at IS NULL
RETURNING id
`

type BindDigitalEmployeeToTeamParams struct {
	TeamID     uuid.UUID `json:"team_id"`
	EmployeeID uuid.UUID `json:"employee_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

func (q *Queries) BindDigitalEmployeeToTeam(ctx context.Context, arg BindDigitalEmployeeToTeamParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, BindDigitalEmployeeToTeam, arg.TeamID, arg.EmployeeID, arg.TenantID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const SoftDeleteTeam = `-- name: SoftDeleteTeam :one
UPDATE tenant_teams
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1::uuid
  AND tenant_id = $2::uuid
  AND deleted_at IS NULL
RETURNING id, tenant_id, slug, name, status, metadata, archived_at, disabled_at, deleted_at, created_at, updated_at, human_owner_user_ids, constitution
`

type SoftDeleteTeamParams struct {
	TeamID   uuid.UUID `json:"team_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) SoftDeleteTeam(ctx context.Context, arg SoftDeleteTeamParams) (TenantTeam, error) {
	row := q.db.QueryRow(ctx, SoftDeleteTeam, arg.TeamID, arg.TenantID)
	var i TenantTeam
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.ArchivedAt,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HumanOwnerUserIds,
		&i.Constitution,
	)
	return i, err
}

const UnbindTeamDigitalEmployees = `-- name: UnbindTeamDigitalEmployees :exec
UPDATE digital_employees
SET team_id = NULL,
    updated_at = NOW()
WHERE team_id = $1::uuid
  AND tenant_id = $2::uuid
  AND deleted_at IS NULL
`

type UnbindTeamDigitalEmployeesParams struct {
	TeamID   uuid.UUID `json:"team_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UnbindTeamDigitalEmployees(ctx context.Context, arg UnbindTeamDigitalEmployeesParams) error {
	_, err := q.db.Exec(ctx, UnbindTeamDigitalEmployees, arg.TeamID, arg.TenantID)
	return err
}
