// Package auth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package auth

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for LoginLogRecordEventType.
const (
	LoginFailed     LoginLogRecordEventType = "login_failed"
	LoginSucceeded  LoginLogRecordEventType = "login_succeeded"
	LogoutSucceeded LoginLogRecordEventType = "logout_succeeded"
)

// Valid indicates whether the value is a known member of the LoginLogRecordEventType enum.
func (e LoginLogRecordEventType) Valid() bool {
	switch e {
	case LoginFailed:
		return true
	case LoginSucceeded:
		return true
	case LogoutSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for LoginLogRecordResult.
const (
	Failed    LoginLogRecordResult = "failed"
	Succeeded LoginLogRecordResult = "succeeded"
)

// Valid indicates whether the value is a known member of the LoginLogRecordResult enum.
func (e LoginLogRecordResult) Valid() bool {
	switch e {
	case Failed:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Defines values for UpdateUserStatusRequestStatus.
const (
	UpdateUserStatusRequestStatusActive   UpdateUserStatusRequestStatus = "active"
	UpdateUserStatusRequestStatusDisabled UpdateUserStatusRequestStatus = "disabled"
)

// Valid indicates whether the value is a known member of the UpdateUserStatusRequestStatus enum.
func (e UpdateUserStatusRequestStatus) Valid() bool {
	switch e {
	case UpdateUserStatusRequestStatusActive:
		return true
	case UpdateUserStatusRequestStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for UserAvatarProvider.
const (
	Dicebear UserAvatarProvider = "dicebear"
)

// Valid indicates whether the value is a known member of the UserAvatarProvider enum.
func (e UserAvatarProvider) Valid() bool {
	switch e {
	case Dicebear:
		return true
	default:
		return false
	}
}

// Defines values for UserAvatarStyle.
const (
	Adventurer UserAvatarStyle = "adventurer"
)

// Valid indicates whether the value is a known member of the UserAvatarStyle enum.
func (e UserAvatarStyle) Valid() bool {
	switch e {
	case Adventurer:
		return true
	default:
		return false
	}
}

// Defines values for UserSummaryStatus.
const (
	UserSummaryStatusActive   UserSummaryStatus = "active"
	UserSummaryStatusDisabled UserSummaryStatus = "disabled"
)

// Valid indicates whether the value is a known member of the UserSummaryStatus enum.
func (e UserSummaryStatus) Valid() bool {
	switch e {
	case UserSummaryStatusActive:
		return true
	case UserSummaryStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for ListUsersParamsStatus.
const (
	Active   ListUsersParamsStatus = "active"
	Disabled ListUsersParamsStatus = "disabled"
)

// Valid indicates whether the value is a known member of the ListUsersParamsStatus enum.
func (e ListUsersParamsStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Disabled:
		return true
	default:
		return false
	}
}

// ChangeCurrentUserPasswordRequest defines model for ChangeCurrentUserPasswordRequest.
type ChangeCurrentUserPasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	Password        string `json:"password"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Avatar   *UserAvatar `json:"avatar,omitempty"`
	Password string      `json:"password"`
	Username string      `json:"username"`
}

// CurrentUserResponse defines model for CurrentUserResponse.
type CurrentUserResponse struct {
	User UserSummary `json:"user"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code  *string `json:"code,omitempty"`
	Error string  `json:"error"`
}

// LoginLogListResponse defines model for LoginLogListResponse.
type LoginLogListResponse struct {
	Items []LoginLogRecord `json:"items"`
}

// LoginLogRecord defines model for LoginLogRecord.
type LoginLogRecord struct {
	ClientIp      *string                 `json:"client_ip,omitempty"`
	CreatedAt     time.Time               `json:"created_at"`
	EventType     LoginLogRecordEventType `json:"event_type"`
	FailureReason *string                 `json:"failure_reason,omitempty"`
	Id            openapi_types.UUID      `json:"id"`
	Result        LoginLogRecordResult    `json:"result"`
	SessionId     *openapi_types.UUID     `json:"session_id,omitempty"`
	UserAgent     *string                 `json:"user_agent,omitempty"`
	UserId        *openapi_types.UUID     `json:"user_id,omitempty"`
	Username      string                  `json:"username"`
}

// LoginLogRecordEventType defines model for LoginLogRecord.EventType.
type LoginLogRecordEventType string

// LoginLogRecordResult defines model for LoginLogRecord.Result.
type LoginLogRecordResult string

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	User UserSummary `json:"user"`
}

// ResetUserPasswordRequest defines model for ResetUserPasswordRequest.
type ResetUserPasswordRequest struct {
	Password string `json:"password"`
}

// UpdateCurrentUserProfileRequest defines model for UpdateCurrentUserProfileRequest.
type UpdateCurrentUserProfileRequest struct {
	Avatar      *UserAvatar          `json:"avatar,omitempty"`
	DisplayName *string              `json:"display_name,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
}

// UpdateUserStatusRequest defines model for UpdateUserStatusRequest.
type UpdateUserStatusRequest struct {
	Status UpdateUserStatusRequestStatus `json:"status"`
}

// UpdateUserStatusRequestStatus defines model for UpdateUserStatusRequest.Status.
type UpdateUserStatusRequestStatus string

// UserAvatar defines model for UserAvatar.
type UserAvatar struct {
	Options  *map[string]interface{} `json:"options,omitempty"`
	Provider UserAvatarProvider      `json:"provider"`
	Seed     string                  `json:"seed"`
	Style    UserAvatarStyle         `json:"style"`
}

// UserAvatarProvider defines model for UserAvatar.Provider.
type UserAvatarProvider string

// UserAvatarStyle defines model for UserAvatar.Style.
type UserAvatarStyle string

// UserListResponse defines model for UserListResponse.
type UserListResponse struct {
	Items []UserSummary `json:"items"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	User UserSummary `json:"user"`
}

// UserSummary defines model for UserSummary.
type UserSummary struct {
	Avatar      UserAvatar         `json:"avatar"`
	DisplayName *string            `json:"display_name,omitempty"`
	Email       *string            `json:"email,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Status      UserSummaryStatus  `json:"status"`
	Username    string             `json:"username"`
}

// UserSummaryStatus defines model for UserSummary.Status.
type UserSummaryStatus string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// ListCurrentUserLoginLogsParams defines parameters for ListCurrentUserLoginLogs.
type ListCurrentUserLoginLogsParams struct {
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// ListLoginLogsParams defines parameters for ListLoginLogs.
type ListLoginLogsParams struct {
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Q 按用户名、显示名称或邮箱搜索
	Q      *string                `form:"q,omitempty" json:"q,omitempty"`
	Status *ListUsersParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int32                 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32                 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListUsersParamsStatus defines parameters for ListUsers.
type ListUsersParamsStatus string

// ChangeCurrentUserPasswordJSONRequestBody defines body for ChangeCurrentUserPassword for application/json ContentType.
type ChangeCurrentUserPasswordJSONRequestBody = ChangeCurrentUserPasswordRequest

// UpdateCurrentUserProfileJSONRequestBody defines body for UpdateCurrentUserProfile for application/json ContentType.
type UpdateCurrentUserProfileJSONRequestBody = UpdateCurrentUserProfileRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// ResetUserPasswordJSONRequestBody defines body for ResetUserPassword for application/json ContentType.
type ResetUserPasswordJSONRequestBody = ResetUserPasswordRequest

// UpdateUserStatusJSONRequestBody defines body for UpdateUserStatus for application/json ContentType.
type UpdateUserStatusJSONRequestBody = UpdateUserStatusRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 查询当前登录用户登录日志
	// (GET /api/auth/account/login-logs)
	ListCurrentUserLoginLogs(w http.ResponseWriter, r *http.Request, params ListCurrentUserLoginLogsParams)
	// 修改当前登录用户密码
	// (POST /api/auth/account/password)
	ChangeCurrentUserPassword(w http.ResponseWriter, r *http.Request)
	// 修改当前登录用户资料
	// (PATCH /api/auth/account/profile)
	UpdateCurrentUserProfile(w http.ResponseWriter, r *http.Request)
	// 用户登录
	// (POST /api/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// 查询 Web 控制台登录日志
	// (GET /api/auth/login-logs)
	ListLoginLogs(w http.ResponseWriter, r *http.Request, params ListLoginLogsParams)
	// 用户登出
	// (POST /api/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// 获取当前登录用户信息
	// (GET /api/auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// 查询平台用户列表
	// (GET /api/auth/users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)
	// 创建平台用户
	// (POST /api/auth/users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// 重置平台用户密码
	// (POST /api/auth/users/{id}/reset-password)
	ResetUserPassword(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// 启用或禁用平台用户
	// (PATCH /api/auth/users/{id}/status)
	UpdateUserStatus(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// 查询当前登录用户登录日志
// (GET /api/auth/account/login-logs)
func (_ Unimplemented) ListCurrentUserLoginLogs(w http.ResponseWriter, r *http.Request, params ListCurrentUserLoginLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 修改当前登录用户密码
// (POST /api/auth/account/password)
func (_ Unimplemented) ChangeCurrentUserPassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 修改当前登录用户资料
// (PATCH /api/auth/account/profile)
func (_ Unimplemented) UpdateCurrentUserProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 用户登录
// (POST /api/auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 查询 Web 控制台登录日志
// (GET /api/auth/login-logs)
func (_ Unimplemented) ListLoginLogs(w http.ResponseWriter, r *http.Request, params ListLoginLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 用户登出
// (POST /api/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 获取当前登录用户信息
// (GET /api/auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 查询平台用户列表
// (GET /api/auth/users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 创建平台用户
// (POST /api/auth/users)
func (_ Unimplemented) CreateUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 重置平台用户密码
// (POST /api/auth/users/{id}/reset-password)
func (_ Unimplemented) ResetUserPassword(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 启用或禁用平台用户
// (PATCH /api/auth/users/{id}/status)
func (_ Unimplemented) UpdateUserStatus(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCurrentUserLoginLogs operation middleware
func (siw *ServerInterfaceWrapper) ListCurrentUserLoginLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCurrentUserLoginLogsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCurrentUserLoginLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangeCurrentUserPassword operation middleware
func (siw *ServerInterfaceWrapper) ChangeCurrentUserPassword(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangeCurrentUserPassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCurrentUserProfile operation middleware
func (siw *ServerInterfaceWrapper) UpdateCurrentUserProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCurrentUserProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLoginLogs operation middleware
func (siw *ServerInterfaceWrapper) ListLoginLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLoginLogsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLoginLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetUserPassword operation middleware
func (siw *ServerInterfaceWrapper) ResetUserPassword(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetUserPassword(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUserStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateUserStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUserStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/auth/account/login-logs", wrapper.ListCurrentUserLoginLogs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/account/password", wrapper.ChangeCurrentUserPassword)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/auth/account/profile", wrapper.UpdateCurrentUserProfile)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/auth/login-logs", wrapper.ListLoginLogs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/auth/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/users", wrapper.CreateUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/users/{id}/reset-password", wrapper.ResetUserPassword)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/auth/users/{id}/status", wrapper.UpdateUserStatus)
	})

	return r
}
